### ISSUE TITLE
terkselverdier A-kriteriet og B-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#101]
Her er det foreløpig feil på terskelverdien. 

På A-kriteriet hopper den fra delkategori/skår 3 til 4 på 645, ikke på 650 som det skal:

![image](https://user-images.githubusercontent.com/58254444/132209371-47ccb00b-ec96-4ebf-ad50-440280a9f13e.png)

Samme feil på B-kriteriet, hvor skåren går fra 3 til 4 på 495 og ikke på 500, som den skal (ser ikke selve skåren i denne screenshoten, men ser hvor jeg har lagt inn tallet): 

![image](https://user-images.githubusercontent.com/58254444/132210316-9842e508-cf1a-48f7-9739-0f11ff34629c.png)

**Comment by bugdriven** [comment]
I Hanno sine script blir median levetid redusert til 2 desimaler. Mulig dette bør gjøres etter at kategori er beregnet. I så fall kan man lure på om det bør være mulig å registrere med mer enn 2 signifikante siffer. Kanskje denne avrundingen er kun tenkt for utdata. Ikke vet jeg.

**Comment by sindrely** [comment]
Jeg er ikke helt sikker på om jeg skjønner hvordan avrunding spiller inn her, men akkurat nå er ståa at:

A-kriteriet er helt låst, det skjer ingenting uansett hvilken verdi som settes inn:

![bilde](https://user-images.githubusercontent.com/91675679/138243822-1403742d-48a9-4d62-9241-c5f66c72621a.png)

B- kriteriet virker til å bare ha feil terskelverdier for "Skår og usikkerhet"  2 og 3:

![bilde](https://user-images.githubusercontent.com/91675679/138244483-8a2bc668-0070-446a-a8b9-744338e34218.png)

fra 155 og opp går man over på skår 3, der skal terskelverdien være 159,
og fra 495 og opp går man over på skår 4, der skal terskelverdien være 499.

**Comment by bugdriven** [comment]
> @bugdriven Ja, vi må ta en titt på hvor han har sett for seg av avrundingen skal skje. Men selve avrundingen forklarer antagelig ikke at skåren hopper til ny kategori på feil heltall? @sindrely ser du på hvordan dette fungerer nå?

Jo. Det er avrundingen som gjør at vi ender med ny kategori. Man kan tenke seg at man gjør avrundingen **etter** at man har beregnet kategori, men da vil jo den verdien vi lagrer på vurderingen tilsi at vi egentlig burde hatt annen kategori!

**Comment by sindrely** [comment]
Denne du tenker på?
![bilde](https://user-images.githubusercontent.com/91675679/146783906-a86ce68f-e7cf-4582-871a-719bb1e22a9e.png)

Den har fått en liten oppdatering.

![bilde](https://user-images.githubusercontent.com/91675679/146784007-12d7497d-7a03-4cc3-a1ed-d4bbcbbf171b.png)

**Comment by bugdriven** [comment]
fixed
