### ISSUE TITLE
Risikovurdering - Lagreknapper 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#102]
Vi har konkludert med at vi ikke ønsker lagreknapper etter hvert kriterium. Inne på både invasjonspotensialet, og økologisk effekt kan dermed lagreknappene som står i tilknytning til hvert kriterium slettes.

Slik som denne:
![image](https://user-images.githubusercontent.com/58254444/132213084-3073cf60-743f-4a0e-a64a-714b7deedf2f.png)

**Comment by svetlnaumova** [comment]
Har fjernet knappen, men det er en lignende komponent som brukes i naturtypefanen, så knappene har blitt fjernet derfra også. Regner med at det er ok, men gi beskjed hvis dere vil ha dem tilbake :)
