### ISSUE TITLE
Underfane-bar - scrolling

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#104]
Når jeg skroller nedover en side med underfaner nå, så dukker det opp en liten "luftspalte" mellom underfanene og fanene. Her ser man tekst som flyter forbi når man skroller. Jeg tror ikke det var slik før? 

![image](https://user-images.githubusercontent.com/58254444/132300433-49c84169-e739-492a-bb46-cee46bcb35bb.png)

**Comment by svetlnaumova** [comment]
Jeg kan dessverre (eller heldigvis?) ikke gjenskape det hos meg og ser ikke det heller i test. Kan du sjekke en gang til og se om det har blitt bedre hos deg?

**Comment by AneMarlene** [comment]
Jøss, i dag er det på magisk vis borte her også - hurra :D
