### ISSUE TITLE
Markering av fanevalg

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#105]
Her kommer et forslag til justering på layout for å markere hvilken fane/underfane man er inne på. 

![image](https://user-images.githubusercontent.com/58254444/132301614-98bbcef9-90e9-4a98-b17a-629eca46bc4e.png)

Kan vi få det til å se ca slik ut i stedet: 

![image](https://user-images.githubusercontent.com/58254444/132304535-dbf073f4-e873-41e9-953f-0f79d39aaf77.png)

**Comment by svetlnaumova** [comment]
Har fikset, men når man bare holder pekeren over faner (hover) er de fortsatt mørke - gi beskjed om det skulle også endres.

**Comment by AneMarlene** [comment]
Usikker på det med pekeren over - vi kan vurdere å endre om vi får sabla god tid og trenger noe å gjøre :D Ellers veldig pent nå ;)
