### ISSUE TITLE
Spredningsveier - småtterier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#106]
Her kommer noen småting på fanen spredningsveier. 

1. Vi ønsker at de ulike temaene her inne kommer i separate grå bolker (slik som på f.eks. økologisk effekt). Sjekker du også at underoverskriftene (overskrift for hver bolk) er stylet som på øvrige faner (horisontskanning mfl.)? 

![image](https://user-images.githubusercontent.com/58254444/132309179-ed1dd9bd-7295-4e21-b255-33565bcb9c1d.png)

2. Vi ønsker at alle boksene for å velge spredningsvei (inne på alle temaene) skal være like lange. Fint om de også har en slik "v" til høyre (vist på en av boksene under) som tydeliggjør at det et flere valg under denne menyen. Mellomrommet mellom boksene kan også være mindre. Tilslutt, det ser ut som det er noe skygge bak knappene (indikert med en rød pil). Om det er tilfelle ønsker vi gjerne å fjerne det også ;) 

![image](https://user-images.githubusercontent.com/58254444/132310960-dc93d203-2f4f-487d-936b-e672d83d07d8.png)

For å vise med en litt penere figur:

![image](https://user-images.githubusercontent.com/58254444/132314084-6b922cbf-bfee-4446-95d4-01ad5d68f45d.png)

**Comment by AneMarlene** [comment]
Litt mer småtterier: 

Når man åpner en spredningsvei, er det fint om valgene under rammes litt inn (markert med grå ramme). Også her kan alle valgene være like store, og så tror jeg det kan være finere om disse valgene ikke har så tydelig svart innramming rundt det hvite (markert med rød pil). Kanskje heller bare en lys grå ramme`? Eller evt ingen? 

![image](https://user-images.githubusercontent.com/58254444/132313583-0dba4e53-df94-45f2-9f16-20c75a5e25fd.png)

**Comment by AneMarlene** [comment]
@svetlnaumova underkategoriene har forflyttet seg til venstre, slik at de starter på linje med hovedkategoriene. Det gjør skillet mellom underkategoriene og neste hovedkategori litt utydelig. Kan du dytte de et hakk eller to inn mot høyre igjen (slik de var på screenshoten over her)? Eventuelt endre bakgrunnsfarge på underkategoriene, så de skilles fra hovedkategoriene på det viset?  

![image](https://user-images.githubusercontent.com/58254444/133398820-e5a7eed9-451d-4a91-9355-00908d1c1277.png)


I tillegg er det ønskelig at feltene for hyppighet, abundans og tidsrom (ikke tidspunkt) er blanke/tomme som default (som vist i skjermbildet over). Altså, at valget "ukjent" ikke er default. Også, valget "ukjent" på Abundans kan flyttes ned i lista slik at det samsvarer med hyppighet og tidsrom :) Se også noen relaterte ting som havnet i issue #23. 

![image](https://user-images.githubusercontent.com/58254444/133398216-8f355c76-384e-423e-93de-611ee8f3d7d0.png)

**Comment by svetlnaumova** [comment]
Tror denne er fikset nå, men bare å åpne igjen hvis det er noe som er gjenglemt.
