### ISSUE TITLE
Visning av gamle naturtypedata

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#107]
Data fra tidligere vurderinger (der det eksisterer) skal vises i tabeller.

**Comment by EveliinaP** [comment]
Skal hver data tabell ligge under hver tema (truete naturtyper, øvrige naturtyper, livsmedium) eller nederst i side? Hva tenker du @AneMarlene? Kanskje bedre hvis de er knyttet til hver slik at ekspertene kan lettere bruke det når de gjør vurderinger? Også, har du noe mal allerede for hvordan disse dataene skal vises slik at det er tydelig at det er data fra tidligere vurdering? Jeg kan tenke på det men bør hvert fall være samkjørt hvis det er noe andre faner som har lignende info.

**Comment by AneMarlene** [comment]
Denne issuen tror jeg allerede finnes og er ordnet. Den ble laget før du kom inn på prosjektet :) Da var tanken at det ble knyttet til selve temaet. Men det er mest aktuelt for rødlista, for på de øvrige kan man (i følge Øyvind) direkte overføre gammel kode til ny, så der er det ikke behov for visning av gammel data - kanskje med unntak av limnisk og marin om disse rekker å komme i helt ny versjon. I såfall tenker jeg som du der også, at de bør knyttes til temaene. Om du f.eks. ser på ..to be continued...

**Comment by EveliinaP** [comment]
Supert, da er det nesten i orden, jeg så ikke det. Jeg foreslå at skriften bli litt større font på overskrift og kanskje litt reformulering av tekst med bruk av f.eks. "(Data fra) tidligere versjon/vurdering" eller noe slikt?

**Comment by AneMarlene** [comment]
@EveliinaP Litt større skrift er sikkert lurt, og kanskje noe reformulering, men jeg tror det er lurt at "rødlista for naturtyper 2011" er med i teksten, ellers blir det fort litt upresist tror jeg?!

**Comment by svetlnaumova** [comment]
@EveliinaP nå har overskriften blitt større, men jeg har ikke skjønt helt hvordan dere ville reformulere teksten - kunne du sjekket om det er ok nå og evt gi beskjed om det er noe mer som skal gjøres?

**Comment by EveliinaP** [comment]
Det er bra nå, vi se senere om det bli behov for småjustering på tekst.
