### ISSUE TITLE
Naturtypefanen (C, F og G-kriteriet)

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#11]
[Naturtyper160321_OH.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6148891/Naturtyper160321_OH.docx)

**Comment by AneMarlene** [comment]
Merk her at det som står på C-kriteriet (boksen Olga har kommentert) skal ligge under fanen "Invasjonspotensiale" (ikke her på Naturtypefanen), og det som står på F- og G-kriteriet (boksene Olga har kommentert) skal ligge under "Økologisk effekt" (ikke her på Naturtypefanen). Det er ikke utarbeidet egne github-issues for disse utover det som står her.

**Comment by AneMarlene** [comment]
@svetlnaumova Som du ser av kommentaren min over, henger denne fanen sammen med C, F og G-kriteriet, og hvordan disse kriteriene skal se ut inne på sine respektive faner er gitt i dette dokumentet. Det som kanskje er lurt å begynne med er å sette opp utseendet til C, F og G-kriteriet (inne på sine respektive faner, se kommentar over), samt det du hadde startet med (å rydde opp i naturtyper).  :)

**Comment by svetlnaumova** [comment]
> Merk her at det som står på C-kriteriet (boksen Olga har kommentert) skal ligge under fanen "Invasjonspotensiale" (ikke her på Naturtypefanen), og det som står på F- og G-kriteriet (boksene Olga har kommentert) skal ligge under "Økologisk effekt" (ikke her på Naturtypefanen). Det er ikke utarbeidet egne github-issues for disse utover det som står her.

Skal disse boksene under "Invasjonspotensiale" og "Økologisk effekt" være inaktive siden de bare viser noe som ble fylt ut under naturtypefanen? Eller må man kunne redigere der også?

**Comment by olgahil** [comment]
Godt spørsmål som vi ikke har tatt stilling til. Det skal strengt tatt ikke være nødvendig under selve kriteriene. Hvis det er behov for å redigere tror jeg det er mest logisk å gjøre det under naturtypefanen.

**Comment by svetlnaumova** [comment]
Ser nå at Hanne skriver i dokumentet angående A- og B-kriteriet at boksene må være grå med mindre man har valgt å redigere dem, så da regner jeg med at dette bør gjelde C-kriteriet også.

**Comment by olgahil** [comment]
Hanne sin kommentar gjelder hvis du har haket av for "Godtar beregnet skår". Da vil avhakingen skje av seg selv (både skår og usikkerhet) og du kan ikke redigere. For C-kriteriet er det annerledes. Her er det bare skåren (første "boks-kolonnen") som hakes av automatisk basert på det du har lagt inn i tabellen over. Eventuell usikkerhet (andre "boks-kolonnen") må du legge in selv. Altså den må kunne redigeres og ikke være grå i naturtypefanen. Under C og F og G trengs det strengt tatt ingen redigeringsmulighet, så her kan alle boksene være grå.

**Comment by AneMarlene** [comment]
Her har Olga rukket å svare før meg ser jeg :)

**Comment by AneMarlene** [comment]
@EveliinaP Her er naturtype-issuen.
