### ISSUE TITLE
Horisontskanning - ferdigstilling og filtrering på ferdigstilling

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#118]
Det virker som vi behøver en ferdigstillingsknapp, og at øvrige faner ikke er redigerbare (bare lesbare) når man har valgt radioknappen "Horisontskanning" på inngangssiden. 

På denne måten vil ikke arten forsvinne fra horisontskannings-lista fordi om den er ferdigstilt, men fortsatt kunne vises der og åpnes ved behov. I tillegg får vi statistikk på hvor stor andel (og antallet) av arter som er ferdigstilt for en artsgruppe inne på horisontskanninga

![image](https://user-images.githubusercontent.com/58254444/132825902-1df33beb-1a82-4950-877e-6789b0257fff.png)

Fra rlbasen:
![image](https://user-images.githubusercontent.com/58254444/132826019-c0cd1fd9-d42f-4de4-9248-8dbe80fbf312.png)

Vi ønsker videre å få sett andelen i % som har gått videre av de ferdigstilte (eventuelt også % som ikke gikk videre, men disse to skal jo til sammen bli 100%, så dette er mindre viktig.). Dette kan vises noe ala dette:

![image](https://user-images.githubusercontent.com/58254444/132827382-f95a34ae-0979-4304-87e5-7922b0d991b4.png)

**Comment by steinho** [comment]
Tror dette i hovedsak er på plass nå? @AneMarlene ?
