### ISSUE TITLE
Spredningsveier - fikserier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#119]
I tabellene kommer det med et tekstfelt (litt skjult) som ikke skal være der: 

![image](https://user-images.githubusercontent.com/58254444/132846200-27d58c59-eba4-4dc6-bf96-c6c679c750aa.png)

Der hvor det var skrevet noe i 2018 (markert i grønt over), skal hovedkategori, kategori og fritekst kopieres over i det felles fritekstfeltet på følgende måte (se  bilde nedenfor for eksempler): Hovedkategori - Kategori: fritekst

![image](https://user-images.githubusercontent.com/58254444/132846901-aee09b75-097d-4bd8-b1e3-7c7974eef350.png)

**Comment by AneMarlene** [comment]
Relatert til dette issuet er at hjelpeteksten vi tidligere hadde i fritekstfeltet før eksperten begynte å skrive nå er borte. I grunn greit, da dette har fått oss til å innse at denne hjelpeteksten heller bør settes utenfor (over) selve skrivefeltet. Det hvor den røde streken står kan teksten ". Dersom informasjonen er knyttet til en bestemt spredningsvei, må dette angis." stå. (husk punktumet etter forrige setning som allerede står der ;) 

![image](https://user-images.githubusercontent.com/58254444/133399892-b33af0ed-9b71-4f1a-b999-32ac7baba250.png)

**Comment by svetlnaumova** [comment]
Kommentar angående utfyllende informasjon: i 2018 var det ikke lagret hovedkategori på spredningsveiene, derfor kan den bli vanskelig å finne. Hvor kritisk er det å få den på plass? Holder det kanskje med underkategorien foreløpig?

**Comment by AneMarlene** [comment]
Vi må nok ha på plass hovedkategoriene før januar. Om de ikke er enkel å finne, så peker hver kategori kun til en, spesifikk hovedkategori. F.eks, så vil hovedkategorien alltid være "forurensing av vare" (det som før het "transport/forurensning") om kategorien er "som parasitter på/i dyr", eller en av de andre kategoriene under denne hovedkategorien (skjermbilde fra fab3): 

![image](https://user-images.githubusercontent.com/58254444/134321928-87765b3f-a802-4e9e-8e2c-791eac4180f0.png)

Hjelper det?
