### ISSUE TITLE
A og B-kriteriet (fanen Invasjonspotensial)

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#12]
[AB_kriteriet_utkast240221_OH.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6149143/AB_kriteriet_utkast240221_OH.docx)

**Comment by olgahil** [comment]
Både A og B-kriteriet skal plasseres under fanen invasjonspotensial slik det er i dag. C-kriteriet skal også plasseres under denne fanen (slik det er nå i basen)

**Comment by AneMarlene** [comment]
@Hannemor testing testing

**Comment by AneMarlene** [comment]
@svetlnaumova Denne får en ny versjon om ikke alt for lenge, så vent litt med den her. :)

**Comment by AneMarlene** [comment]
Her kommer et noe redigert forslag. Det mangler muligens et par presiseringer som går på logikk i noen skrivefelt, men er ellers ok.  Spør om det er noe.
[FAB_AB_kriteriet_utkast240221_OH_AMM.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6614906/FAB_AB_kriteriet_utkast240221_OH_AMM.docx)

**Comment by bugdriven** [comment]
B2 (Anslått økning i forekomstareal)
Jeg forstår ikke hvor på utbredelsesfanen t0 (og t1, t2) skal hentes fra.

**Comment by olgahil** [comment]
Slik fanen Utbredelse i Norge ser ut nå er det ingen felt hvor årstallet t0 står oppført (skjønner at du spør om dette). Startår t0 velges i selve artskartløsningen og står altså ikke i selve fanen. I Artskart i fab skal det legges til en mulighet for å velge startår, slik det er gjort i rødlistebasen (se under utvalg i artskartløsningen)). T1 med tilhørende forekomstareal hentes også fra artskartløsningen i FAB (men de kan også legge det inn manuelt om de ikke vil bruke Artskart). Tidspunktet T2 er satt til i dag (standard) og her kan vi vel egentlig forhåndsutfylle med år 2021 (t2) i tabellen. Tilhørende kjent forekomstareal står oppført  i Utbredelse i Norge (se forekomstareal i dag (km2) kjent "tallverdi"). 
Jeg har foreslått noen endringer i teksten som står under Anslått økning i forekomstareal, men jeg vil gjerne diskutere den med Ane først. Du må vel bare vente litt med denne til Ane har sett på endringsforslaget.

**Comment by svetlnaumova** [comment]
Lukker denne fordi det ser ut som eneste som ikke fungerer i denne fanen er filopplasting og teksten som inneholder verdier fra utbredelsesfanen, men det finnes egne issuer for dette.
