### ISSUE TITLE
B-kriteriet - Artskart-linker

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#120]
Her kommer en noe justert utgave av B-kriteriet. Vi håper at vi kan kvitte oss med de to radioknappene og tilhørende undervalg, og bare ha en Artskart-knapp tilhørende hver linje i stedet (plassering på knapp indikert med blå firkant). Resten av tabellen kan da flyttes litt mot høyre med noe mindre mellomrom mellom skrivefeltene.

t0-feltene i tabellen vil fortsatt være grået ut. Innholdet i disse bestemmes på fanen Utbredelse i Norge (dette er fom year/t0). 

t1 (AOOyear1) og t2 (AOOyear2), med tilhørende forekomstareal per disse årene vil da bestemmes gjennom Artskart (om eksperten velger å bruke det), eller de kan skrive inn årstall og forekomstareal manuelt. 

![image](https://user-images.githubusercontent.com/58254444/132863634-b9bbf08b-5b9c-436e-8380-42cbf3bec86f.png)

**Comment by sindrely** [comment]
Det som gjennstår på denne er en egen issue #237
