### ISSUE TITLE
D- og E-kriteriet - tabellnavn

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#123]
Vi ønsker navn på disse to tabellene inne på økologisk effekt.  Inne i rute 1 kan det stå "Legg til enkeltarter". I rute 2 kan det stå "Legg til grupper av arter"

![image](https://user-images.githubusercontent.com/58254444/133076929-7d5d1bce-d868-44d1-81b5-9a71a6e3c4da.png)

**Comment by svetlnaumova** [comment]
La til navn med vanlig tekststørrelsen og fet skrift - gi beskjed om det må endres :)
