### ISSUE TITLE
Horisontskanning - nye filtre på inngangssiden

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#125]
Vi ønsker at de tre hovedfiltrene (med underfiltre) som finnes i basen per nå kun skal være synlig for valget "risikovurdering". Altså de skal i hovedsak bort for horisontskanningen: 
![image](https://user-images.githubusercontent.com/58254444/133251772-d2eb1fd4-440a-442b-bc80-abd934ca7ed7.png)

For horisontskanningen ønsker vi i stedet en justert versjon av den siste av disse filtrene. Merk at dette issuet er delvis overlappende med issue #118. Alternativene under framdrift (tidligere "vurderingsstatus") er riktig i denne versjonen. Forslaget ligger her (slide 2 vises valgene under selve filteret): 
[Inngangsside - horisontskanningen.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7162039/Inngangsside.-.horisontskanningen.pptx)

En (eller to) liten ting til: Vi kan bytte til ordet "framdrift" også for valget risikovurdering (markert med røde ringer), samt at det grå feltet strekkes ut for alle underfiltre (oransje piler). 

![image](https://user-images.githubusercontent.com/58254444/133261172-20395839-d4a3-40f7-85c6-875f60377f57.png)

**Comment by AneMarlene** [comment]
Det begynner å bli meget bra. Så kommer jeg med små pirkedetaljer her likevel da :) [disse er ikke av typen pri 1]

1. Den filtrerings-boksen, er det mulig å få den enda et hakk mot høyre? 
2. Framdrifts-boks kan flyttes tilsvarende lengde mot høyre
3. Avstanden av lengde x, markert med oransje, skal være lik på høyre og venstre side (samt avstanden mellom boksene). 
4. Underkategoriene til "ikke risikovurdert" kan flyttes nærmere den kategorien (markert med oransje piler) 
5. Avstand mellom grå filterboks og "brukte filtre"/artslisten kan økes, så den blir lik avstanden y (markert med rødt).

...nå er jeg litt i tvil på om denne oppskriften var pedagogisk eller ikke - bare spør 😄 Kommer forresten statistikken "Totalt: " opp når vi får inn tallene? (den skulle være nederst på "framdrift".


![image](https://user-images.githubusercontent.com/58254444/133437099-76154b4a-8fb3-4292-8d6f-1106e97248f2.png)

**Comment by svetlnaumova** [comment]
Jeg lukker denne forsiktig for det meste ser ut til å være på plass - statistikken kommer senere, den glemmer vi nok ikke.
