### ISSUE TITLE
Brukerdatabase - logg ut overkill

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#126]
Kanskje vi kan holde oss til "Du er logget ut" her? :) 

![image](https://user-images.githubusercontent.com/58254444/133402797-2eccdc6b-1900-4146-b24e-b7fe68b85541.png)

**Comment by steinho** [comment]
Må ta det litt senere - brukerdatabasen er i hovedsak lagret at et opensource prosjekt - så hva vi får til å endre på tekster er litt usikkert - mulig @arvped  vet...

**Comment by steinho** [comment]
Vi lukker denne nå - kommer ikke til å gjøre noe med den i denne runden - kanskje senere
