### ISSUE TITLE
Horisontskanning - synlig fane og overføring til utbredelsesfanen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#127]
1. Horisontskanningsfanen har vært borte fra "fanebaren" ganske lenge. Den bør vises for alle artene som er inne på valget "horisontskanning". Dette kommer kanskje ikke på plass før disse artene har blitt merket på baksiden? 
2. For artene som går videre fra horisontskanningen, og som i tillegg har valgt 1 på etableringspotensial (se screenshot under), så skal dette 1-tallet overføres til feltet markert med 2 (det skal altså ikke stå "2" inne i feltet). Dette må altså bli med over til "risikovurdering". Om de senere, under risikovurderingen, velger å endre dette tallet inne på utbredelsesfanen, bør de få opp et varsel ala "Dette stemmer ikke overens med vurdering på horisontskanningen. Er du sikker på at du vil endre?"

![image](https://user-images.githubusercontent.com/58254444/133562586-29f0d7a4-7759-4dc2-bf1b-c5f7962f32e0.png)

![image](https://user-images.githubusercontent.com/58254444/133563829-c64f5a82-e6fa-4732-9d83-a3c91d82c99d.png)

**Comment by steinho** [comment]
Dette virker (synlig fane) i den versjonen jeg har nå.... kommer plutselig ut

**Comment by steinho** [comment]
> 2. For artene som går videre fra horisontskanningen, og som i tillegg har valgt 1 på etableringspotensial (se screenshot under), så skal dette 1-tallet overføres til feltet markert med 2 (det skal altså ikke stå "2" inne i feltet). Dette må altså bli med over til "risikovurdering". Om de senere, under risikovurderingen, velger å endre dette tallet inne på utbredelsesfanen, bør de få opp et varsel ala "Dette stemmer ikke overens med vurdering på horisontskanningen. Er du sikker på at du vil endre?"

@AneMarlene :
Punkt 2 her - usikker på hva det betyr, men tror det er noe annet en at fanen horizonscan skal vises på disse vurderingen. Kunne vi lukket denne og laget en egen issue på 2)

**Comment by AneMarlene** [comment]
Ja, denne kan lukket. Virker som at punkt 2 også er ordnet :)
