### ISSUE TITLE
Naturtypefane - tabeller

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#128]
Jeg liker utseendet på tabellene inne på risikovurderingen av økologiske effekter hvor all redigering av det som er lagt inn i en tabell, kan skje direkte i tabellen. Her, inne på naturtypefanen har vi en kombinasjon. Jeg foreslår at alle parametrene kan endres direkte i tabellen her også (som vist i screenshot). Alternativt, flytter vi over "vurderingsgrunnlag" til å kun kunne velges bak redigeringsknappen. Kanskje er det ryddigere på denne fanen?! 

![image](https://user-images.githubusercontent.com/58254444/133595429-3138792f-0e0d-40a2-b884-d6f4cd322f9c.png)

Relatert til dette, når man skal legge til en ny naturtype som man velger fra listen, hadde det vært fint om "vurderingsgrunnlag også ble lagt til:

![image](https://user-images.githubusercontent.com/58254444/133596083-fb605794-6f06-4ccf-990d-a2bf801cfe49.png)

**Comment by svetlnaumova** [comment]
Spørsmål angående tidshorisont-kolonner for dørstokkarter: forstod jeg det riktig at det skal alltid stå "fremtidig" uten muligheten til å endre?

**Comment by EveliinaP** [comment]
ja, bare fremtidig for dørstokkarter.
