### ISSUE TITLE
fanen Administrasjon er synlig for ikke-admin

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#130]
Jeg får denne beskjeden når jeg åpner fanen admin med min dummy-bruker: 

![image](https://user-images.githubusercontent.com/58254444/133739631-7f1e6a12-c352-4e7b-a777-091b7de83193.png)

Kanskje bedre om det er som i rødlistebasen at denne fanen er helt borte for alle som ikke er admin :)

@steinho det er bare oss i ADB som er admin, er det ikke? Lederrettigheter gir ikke tilgang til admin?

**Comment by svetlnaumova** [comment]
Jeg har fjernet administrasjonsfanen fra viewet til dem som ikke har adminrettigheter, men gi beskjed hvis det er ikke helt det som var tenkt.

**Comment by AneMarlene** [comment]
det var nøyaktig det som var tenkt :) takk!
