### ISSUE TITLE
Smått HorisonScanning

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/Fremmedartsbase2023#133]
Samler noen spm her....

Når har man startet HS på en vurdering - ved første lagring?

**Comment by AneMarlene** [comment]
> Samler noen spm her....
> 
> Når har man startet HS på en vurdering - ved første lagring?

Det høres fornuftig ut tror jeg. 

Angående lagring på HS: Om eksperten har svart på begge spørsmålene før hen lagrer... er det da slik at vi kan tolke det som "ferdigstilling" og sånn sett omgå ekstra knapp? Eller burde vi ha egen knapp?  Uansett om vi har en eller to knapper, så bør det være mulig for eksperten å finne arten igjen etter "ferdigstilling" slik at eventuelle endringer kan gjøres i tilfelle noe ny info har dukket opp.

**Comment by AneMarlene** [comment]
Jeg lukker denne da spørsmålet virker å ha fått sin løsning i FAB.
