### ISSUE TITLE
Lagring feiler hvis felt settes til "tomt"

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#136]
Hvis jeg ønsker å fjerne et tall fra en celle som ved forrige lagring hadde en verdi (altså, feltet var ikke tomt), så feiler lagringen. Da feiler all form for lagring (dvs. også ved forsøk på å sette inn et tall i et annet felt). Eneste måte å få "lagring ok" på, er å fylle inn et tall i den cella hvor jeg først fjernet tallet fra. Denne bugen gjelder flere felt, blant annet disse (jeg har ikke sjekket gjennom hele basen): 

![image](https://user-images.githubusercontent.com/58254444/135326345-403735aa-5539-4ecf-acd6-25512555ecd8.png)

![image](https://user-images.githubusercontent.com/58254444/135326558-43bbda25-dff6-4240-b1bc-ed6dff515575.png)

Antagelig er denne bugen enklere å forklare ved å demonstrere på skjerm (merker det var vanskelig å beskrive i tekst)

**Comment by AneMarlene** [comment]
@EveliinaP Kan dette forklare de gangene du ikke har fått til å lagre? (altså, har du forsøkt å tømme et tallverdi-felt)?

**Comment by EveliinaP** [comment]
Nei, tror ikke det. For meg det virker litt tilfeldig om arten kan lagres eller ikke, eller i hvilke fane jeg få lagret eller ikke.

**Comment by AneMarlene** [comment]
![image](https://user-images.githubusercontent.com/58254444/135438854-4e668ab1-4d14-491c-8a84-8b2dd270dcfc.png)

**Comment by AneMarlene** [comment]
@sindrely sjekker du denne?

**Comment by sindrely** [comment]
![Merknad 2021-10-04 121623](https://user-images.githubusercontent.com/91675679/135834918-3c4e1996-7405-43b0-be11-836c4ee236ec.png
![Merknad 2021-10-04 122119](https://user-images.githubusercontent.com/91675679/135834922-8ef60613-c403-4793-9f4e-6904ef589c1a.png)
)
Samme?
