### ISSUE TITLE
Horisontskanning - kategori fra 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#143]
Artene fra 2018 som skal via horisontskanningen hadde (med noen få unntak) kategori NR (ikke NK). Noe har vel gått galt her:

![image](https://user-images.githubusercontent.com/58254444/135502238-6f7fc6f7-7f95-4469-9884-c3257883b871.png)

Det virker også som kategorien på inngangssiden, og den vi ser øverst når vi er inne på en vurdering ikke alltid er lik. Eksempelart: Jeg ser i JSON-fila på Acheta domesticus (terrestrisk invertebrat) at den har verdi 0 på risklevel (som forøvrig er en egenskap som ikke ser ut til å finnes lengre - det lager kanskje også krøll med lagring, men det er en annen issue). Øverst på siden står det at denne har kategori NK (og det står også i JSON), mens på inngangssiden står det som er korrekt for arten; NR. (se de tre skjermbildene nederst)

I kongefila finnes ikke risklevel nivå 0. Der er den enten tomt felt (= NR), 1 (= NK), 2, 3, 4 eller 5. 

![image](https://user-images.githubusercontent.com/58254444/135504742-33d3c8a2-cbae-42f8-bc6d-6ecd82417530.png)

![image](https://user-images.githubusercontent.com/58254444/135505982-c4cf5d92-6967-4194-959d-f6c966d5623c.png)

![image](https://user-images.githubusercontent.com/58254444/135506092-935de797-a8d8-4c42-8a91-1695854ab86c.png)

Hos den terrestriske invertebraten bønnefrøbille er kategorien lik (NK) på inngangsiden og øverst siden inne på vurderingen. Den er altså feil begge plasser, ettersom denne også var NR i 2018. Her sier JSON at risklevel er satt til "-1" og at dette tilsvarer NK.  

![image](https://user-images.githubusercontent.com/58254444/135506572-5c839c74-538f-4814-a190-4f08a43bab6e.png)

Det kan virke på meg som at "risklevel == 0" har fått riktig oversettelse på inngangssiden (men ikke på toppen av vurderingen), mens "risklevel == -1" er blitt feil begge plasser.. Kanskje har det noe med at ekspertene har vært inne og fylt ut på vurderingene før NR er blitt satt? Ka du trur, @steinho? Skal jeg grave dypere i dette?

**Comment by steinho** [comment]
@bugdriven må også se på denne - i.o.m. at risklevel forsvinner her ved lagring. Denne brukes serverside nå når man filtrerer og viser kategori

**Comment by steinho** [comment]
@AneMarlene ble kanskje bedre på de nye vurderingene nå og de fra 2018?

**Comment by AneMarlene** [comment]
@steinho Jeg vet ikke helt hva du gjorde, men nå er alle artene på alger borte fra test, sett bort fra denne ene: 
![image](https://user-images.githubusercontent.com/58254444/136081258-5c643cdb-621a-448e-bdcd-026d88e67d74.png)

Det er jo en slags fiks det også, bare ikke den vi var ute etter kanskje :D

**Comment by steinho** [comment]
@AneMarlene Er denne ok nå - kan lukkes?

**Comment by AneMarlene** [comment]
Jeg har løftet det som gjenstår her i et nytt issue.
