### ISSUE TITLE
Risikovurdering - deaktiver i driftversjon

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#144]
Vi deaktiverer "heile sjiten" som har med full risikovurdering å gjøre i driftversjonen (burde det testes i testversjonen også?). Altså alt innenfor dette valget: 
![image](https://user-images.githubusercontent.com/58254444/135573488-b50199cc-4a60-4ebf-81ec-f42d1e7c67b9.png)

@svetlnaumova, tagger du en av de andre på denne om dette ikke er innenfor ditt område?

**Comment by svetlnaumova** [comment]
Usikker på om jeg har forstått riktig - må det ikke være mulig å velge "Risikovurdering", eller må alle filtre og tabellen under den deaktiveres?

**Comment by AneMarlene** [comment]
Jeg lurer på om det er lurt å bare gjøre dette i driftversjonen egentlig. Vi har nok behov for å kunne både teste selv, og vise ekspertene alle fanene under oppstartsmøtet.. 

Angående spørsmålet ditt så er jeg er litt usikker selv. Egentlig tror jeg lesetilgang på risikovurdering hadde vært best(?!), men det virket på Stein mfl. at det enkleste og beste var å hindre tilgang til risikovurderingen i det store og hele (altså at det ikke kan velges - stemmer det @steinho?). Spesielt siden noen faner ikke er helt ferdige. Det er antagelig riktig tenkt, selv om jeg ikke ser at det skulle gjøre noe at noen faner ikke er ferdige når de uansett bare skulle fått lesetilgang. Men jeg kan se at det kanskje skaper ekstraarbeid for dere på IT som vi ikke trenger akkurat nå. ;)

**Comment by svetlnaumova** [comment]
Jeg starter med å gjøre radioknappene inaktive i driftsversjonen. Horisontskanning er satt som default.
