### ISSUE TITLE
Legg til ny art - kobling mot inngangssiden

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#149]
Jeg lurer på om vi har laget en løsning som er noe uheldig i praksis nå (den må enten endres helt eller justeres). Altså, det at hvilket valg man har gjort på inngangssiden (risikovurdering vs horisontskanning) er styrende for Legg til ny art. 

Her kommer et (forhåpentligvis) forklarende eksempel - Jeg bruker artsgruppe Alger i alle trinn:
1. Jeg er på "risikovurdering" på inngangssiden, går til Legg til ny art og legger til skogfiol i Alge-listen for "reproduserer selvstendig".
2. Jeg er fortsatt på "risikovurdering" på inngangssiden, men kommer på at jeg la til skogfiol til feil gruppe - den er jo tross alt en potensiell dørstokkart. Jeg går til Legg til ny art, og prøver å flytte skogfiol, ved å legge den til på "potensiell dørstokkart". Det går ikke. Jeg får da beskjed om at arten allerede er i listen (noe den ikke gjør på horisontskanningen, så det er feil beskjed - riktig beskjed ville vært "ønsker du å flytte arten" eller noe i den duren). 
3. Jeg går til inngangssiden, velger "horisontskanning", og går så til Legg til ny art. Da kan jeg tilsynelatende legge til skogfiol både som "reproduserer selvstendig" (hvor den allerede finnes, så der burde man strengt tatt heller fått et varsel om at arten finnes i listen) og som potensiell dørstokkart. 

Det beste hadde vært om det kun er de to valgene på siden Legg til ny art som er koblet opp mot listene i bakgrunn. Altså, velger jeg "reproduserer selvstendig", så legges arten til der/flyttes dit - gitt at den ikke fantes i den lista fra før, og velger jeg "potensiell dørstokkart", så legges arten til der/flyttes dit - gitt at den ikke fantes i den lista fra før. Er det mulig? Om ikke må i allefall løsningen justeres noe, slik at beskjedene og mulighetene stemmer overens med dataen som ligger bak. :)

![image](https://user-images.githubusercontent.com/58254444/135595290-3fde7783-918b-40be-a057-15dcb2425df6.png)

**Comment by steinho** [comment]
Vi må høre med @bugdriven og @svetlnaumova her. Det var jo nærmere slik du beskriver over det jeg hadde laget til i utgangspunktet.

Slik det er nå - er i hvert fall konsekvent på å si at det er en vurdering der - uavhengig om du kom fra 2 eller 3 over....

Det mest tydelige er om det var enda en knapp til - inne på vurderingen - ala "flytt til horizontscanning" og omvendt - kanskje bare for administratorer? 
Merkelig nok finner jeg noe kode på server og i gui for dette - men klarer ikke å provosere det frem - ser ut som det skulle kommet frem som en undermeny under flytt vurdering.
@bugdriven ?

**Comment by steinho** [comment]
@AneMarlene - jeg er litt usikker - men får til flytting mellom type risikovurdering på en test-art nå. Virker som om testen på om det eksisterer art innenfor artgruppe fungerer...

**Comment by AneMarlene** [comment]
@steinho jeg tror denne kan lukkes, da funksjonaliteten rundt flytt art og legg til ny art har blitt lagt til to ulike steder nå. Flytt art-knappen fungerer utmerket, og jeg ser at legg til ny art ikke er lov om arten finnes i artsgruppa (uavhengig av om arten ligger under horisontskanning eller om den ligger under risikovurdering) - slik tror jeg det må være :)
