### ISSUE TITLE
Legg til ny art - hjelpetekst + navn på knapp

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#150]
Ettersom denne siden nå omfatter både det å legge til ny art og å flytte arter mellom horisontskanning og risikovurdering, så er det antagelig fint med en liten hjelpetekst (i det blå feltet):

"Legg til ny art, eller flytt en art fra horisontskanning til risikovurdering (evt. motsatt). Flytting gjelder for arter hvor ny informasjon tilsier at arten (evt. ikke) reproduserer selvstendig utendørs i Norge likevel." 

![image](https://user-images.githubusercontent.com/58254444/135606742-4a376fa0-bdf1-40ff-930c-326d9e4eb548.png)

Knyttet til dette: Når det er flytting av art det gjelder, kan knappen endre navn til "Flytt art" da?

**Comment by svetlnaumova** [comment]
Forstår jeg det riktig at knappen skal hete "Flytt art" bare hvis man har gjort endringer med radioknappene?

**Comment by svetlnaumova** [comment]
Jeg gjorde det slik at navnet på knappen byttes når man gjør valg ved hjelp av radioknappene, men det er ingen mulighet å endre tilbake til "Legg til ny art" - hvis det er aktuelt, hva skal logikken for det være?

**Comment by AneMarlene** [comment]
@svetlnaumova jeg tror kanskje vi misforstår hverandre nå (men er ikke 100% sikker). Navn på knappen skal endres hvis arten finnes i en av listene "potensielle dørstokkarter", eller "risikovurdering" fra før, og eksperten ønsker å legge den til i den andre listen.  

For å ta et eksempel. Om jeg er inne på horisontskannings-listen på alger, og ser på arten Antithamnion densum. Så finner jeg ut at denne arten egentlig er selvstendig reproduserende, og derfor ikke skal ligge inne på horisontskanningslisten, men inne på "risikovurdering" som "selvstendig reproduserende". Jeg går da til "legg til ny art" og søker opp Antithamnion densum for å legge den til som "selvstendig reproduserende". Ettersom denne allerede finnes i lista "horisontskanning", endrer da knappen navn til "Flytt art" for å synliggjøre for brukeren at nå flyttes arten fra den ene listen til den andre. 

Btw, i testbasen endres det ikke navn på knappen enda, uansett hva jeg gjør. Er det kanskje ikke kjørt ut i test enda?

**Comment by AneMarlene** [comment]
Og så har jeg to små endringer på teksten. Et ord skal bort, og ett ord skal flyttes lengre fram: 

![image](https://user-images.githubusercontent.com/58254444/135991305-50bbcd47-aca1-441f-aff0-f22c55ab7302.png)

**Comment by svetlnaumova** [comment]
> @svetlnaumova jeg tror kanskje vi misforstår hverandre nå (men er ikke 100% sikker). Navn på knappen skal endres hvis arten finnes i en av listene "potensielle dørstokkarter", eller "risikovurdering" fra før, og eksperten ønsker å legge den til i den andre listen.
> 
> For å ta et eksempel. Om jeg er inne på horisontskannings-listen på alger, og ser på arten Antithamnion densum. Så finner jeg ut at denne arten egentlig er selvstendig reproduserende, og derfor ikke skal ligge inne på horisontskanningslisten, men inne på "risikovurdering" som "selvstendig reproduserende". Jeg går da til "legg til ny art" og søker opp Antithamnion densum for å legge den til som "selvstendig reproduserende". Ettersom denne allerede finnes i lista "horisontskanning", endrer da knappen navn til "Flytt art" for å synliggjøre for brukeren at nå flyttes arten fra den ene listen til den andre.
> 
> Btw, i testbasen endres det ikke navn på knappen enda, uansett hva jeg gjør. Er det kanskje ikke kjørt ut i test enda?

Det var nettopp det jeg lurte på, bare formulerte det litt dårlig - takk for forklaring! 

Knappen bytter navn, men nå ser jeg at den ikke gjør det i alle tilfeller (usikker på hva er grunnen til det). Hvis man har valgt en art som har et populærnavn og trykket på en av radioknappene, pleier det å fungere (akkurat i denne screenshoten er det mye som er feil, men målet var bare å vise at det går):

![image](https://user-images.githubusercontent.com/43623201/136078391-159e39d7-6112-4508-8418-aefb23f9cd3f.png)

**Comment by AneMarlene** [comment]
Ja, ser nå at det fungerer delvis. Jeg fikk til å flytte art fra horisontskanning til selvstendig reproduserende, og da endret knappen seg på riktig måte, men når jeg forsøker å sende samme art tilbake til horisontskanningen igjen, ser det slik ut: 

![image](https://user-images.githubusercontent.com/58254444/136157516-85d52da9-6415-45c9-99a6-1f1e12223868.png)

**Comment by svetlnaumova** [comment]
@AneMarlene denne kanskje kan lukkes siden den henger sammen med #188?

**Comment by AneMarlene** [comment]
@svetlnaumova Ja det tror jeg. Dette blir nok fikset med løsningen du og Helge har jobbet med.
