### ISSUE TITLE
Driftbasen - kan (tilsynelatende) redigere på arter med lesetilgang

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#159]
Både vi i admin, og andre brukere uten adminrettigheter kan gå inn på en art hvor man bare har lesetilgang, og gjøre endringer (fylle ut horisontskanning og legge til/fjerne referanser). Det er også slik i testbasen, og der har jeg undersøkt om jeg faktisk får lagre. Får da "lagring feilet", så jeg tror ikke vi kan lagre endringer i driftbasen heller, men alle felt bør uansett kun vises som lesetilgang (sett bort fra kommentarfanen) for de med lesetilgang.

**Comment by bugdriven** [comment]
fixed
