### ISSUE TITLE
Lagring feiler under "Artens status i dag"

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#169]
Unde risikovurdering feiler lagring etter å huka av for "ja" på en eller flere av radioknapper under tekstfeltet.
![bilde](https://user-images.githubusercontent.com/91675679/136787684-584bc088-2761-4136-95ed-d52b627247eb.png)

![bilde](https://user-images.githubusercontent.com/91675679/136787765-28737171-9c5f-4161-8c72-15f58835a9c4.png)

Dette er tidligere rapportert som mulig samme feil som #117 men er ikke sikker på om disse er relaterte.

**Comment by EveliinaP** [comment]
For meg feiler nå når jeg har valgt Er arten fremmed? Ja, og bruksart Ja. Usikker om dette skulle være under #117 
![image](https://user-images.githubusercontent.com/25793207/136805834-0f52a4eb-e982-4f8e-8293-1dacfc50cd5a.png)

**Comment by bugdriven** [comment]
Det er greit å ha dette som en egen bug, for den er knyttet til akkurat disse feltene. Den er litt tidkrevende å fikse og jeg bør snakke med Stein om løsningen på denne. - Problemet er at det er en missmatch mellom datatyper på server og på klienten. Vi (IT) må se på hva som er mest hensiktsmessige løsning.

**Comment by AneMarlene** [comment]
I dag fikk jeg lagre endringer helt til jeg kom til 1800-talls grensa. Regner med denne lagringsfeilen er relatert til dette issuet: 

![image](https://user-images.githubusercontent.com/58254444/140483920-2d0c3898-ea9c-405f-9281-883783823f72.png)

**Comment by sindrely** [comment]
Denne ser ut til å være fiksa
