### ISSUE TITLE
silent error i "legg til rødlistevurdert art" under Risikovurdering - Artens økologiske effekt D- og E-kriteriet

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#170]
Får ikke til å legge til ny art under D- og E- kriteriet: Effekt på rødlistevurderte arter. 
Det ser ut som den søker:
![bilde](https://user-images.githubusercontent.com/91675679/136788618-ab6ad180-f195-411a-8710-eb0b6618713e.png)

men det kommer aldri noen forslag. Verken med norsk eller vitenskapelig navn.
Mulig denne hjelper:

![bilde](https://user-images.githubusercontent.com/91675679/136788802-02905d16-150e-4f4d-8d41-95b5ae513f50.png)

**Comment by steinho** [comment]
Url kallet gikk til feil url ..... det går riktig nå, men jeg klarer ikke å se hva som ikke slår til riktig i frontend koden på rødlistede arter.
@bugdriven og @svetlnaumova er kjappere på den koden. Kanskje har det med at ny rødliste er lansert og at det filtreres på 2015 status?

Ser parasitter og slikt dukker opp lengre nede på siden....

**Comment by steinho** [comment]
Jeg la til at den skulle filtrere på RL2021 ikke RL2015 - men fortsatt dukker ingen dropdown opp... Her må nok frontend-ekspertisen se videre på det - søket virker - men filtrering av resultatet på rødlistede arter fungerer ikke. Eller noe annet

**Comment by steinho** [comment]
@bugdriven - både jeg og @svetlnaumova har forsøkt å få disse til å virke - men skjønner ikke helt hva som skjer/ikke skjer....

**Comment by svetlnaumova** [comment]
@AneMarlene denne er nok ferdig?

**Comment by AneMarlene** [comment]
@svetlnaumova - nå tror jeg denne kan lukkes, da den på sett og vis dekkes av #408 ?
