### ISSUE TITLE
Feil beregnet verdi i Utbredelse i Norge. Risikovurdering av dørstokkarter. Fanen Bakgrunnsdata

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#173]
Jeg tror disse tre verdiene er sånne som skal beregnes på siden, men nå må de fylles ut. Det ser også ut som om laveste og høyeste anslag bare er kopier av verdien som fylles inn på Beste anslag.
![bilde](https://user-images.githubusercontent.com/91675679/136932577-75c43cb7-1c60-4015-80c8-822dbf8409a6.png)

**Comment by sindrely** [comment]
For dørstokkarter får jeg ikke fylle inn noen ting og får bare denne feilen:

![bilde](https://user-images.githubusercontent.com/91675679/137702711-89ad993b-bbc7-4a65-ae17-041464ff7942.png)

med link til denne:
https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/errors.ts

**Comment by sindrely** [comment]
Er det en oppdatering på denne?

**Comment by bugdriven** [comment]
Har sjekket inn riktig formel for disse. Kan du teste om ting fungerer som forventet?

**Comment by sindrely** [comment]
Tror ikke denne er fiksa enda.
Hvis:
Occurrences1Best  = 1
og 
IntroductionsBest = 1
blir jo 
AOO10yrBest <- 4 * round(Occurrences1Best + IntroductionsBest^((Occurrences1Best+9)/10))
AOO10yrBest <- 4 * round(1+ 1^((1+9)/10))
AOO10yrBest  <- 8

men i basen nå blir dette 12

![bilde](https://user-images.githubusercontent.com/91675679/144048488-a20e568c-8351-4ce9-b9b5-c41fefc0ee24.png)

**Comment by bugdriven** [comment]
Hvilken art tester du på?

**Comment by bugdriven** [comment]
Jeg er litt usikker, men slik jeg tolker Hanno sitt skript er at AOO10yrBest brukes for dørstokkarter(?)

**Comment by bugdriven** [comment]
@AneMarlene den over her?

**Comment by AneMarlene** [comment]
@bugdriven  AOO10yrBest brukes for dørstokkarter ja, og jeg tror vi kan lukke denne nå. Tror disse issuene er histore :)
