### ISSUE TITLE
Lagring Feilet risikovurdering/Invasonspotensiale 

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#175]
Mulig relatert til #168 som ble fiksa i den 11.10
Hvis jeg forsøker å lagre etter å ha fyllt inn vekstrate, Miljø- eller Demografisk-varians som ett desimaltall får jeg "Lagrin Feilet".
Hvis jeg fjerner desimalen og førsøker å lagre igjen går alt som det skal. 

![bilde](https://user-images.githubusercontent.com/91675679/136960521-d3bdce68-3c43-4735-9678-29b32ff855e9.png)

og uten desimalen

![bilde](https://user-images.githubusercontent.com/91675679/136960591-6cf0d728-aaef-405a-aaa0-ad52e8e0d0fc.png)

**Comment by steinho** [comment]
@sindrely - kan du sjekke denne nå.... la inn generisk fiks på alle streng til tall konverteringer... kommer vel ut på test relativt fort

**Comment by sindrely** [comment]
Ser ut til å funke nå
