### ISSUE TITLE
Problem med lagring/dafault verdi på Bakgrunnsdata for risikovvurdering

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#176]
I feltet "Beste anslag (Median)" under bakgrunnsdata for risikovurdering (**Merk** at dette bare gjelder for dørstokkarter, og ser ut til å ikke være ett problem for selvstendig reproduserende arter), endres verdien i feltet til 1, når man går ut og inn av fanen eller vurderingen. Jeg får "Lagring OK" men hver gang jeg kommer tilbake til fanen er verdien satt tilbake til 1. 

![bilde](https://user-images.githubusercontent.com/91675679/137081800-ef5cabae-dadc-45a6-84a2-3fa22301d260.png)

og etter å gå til neste fane og så tilbake igjenn ser det slik ut:

![bilde](https://user-images.githubusercontent.com/91675679/137081878-f5f7e111-c915-4403-aa17-62ef08a9e895.png)

**Comment by svetlnaumova** [comment]
Jeg har forstått kommentaren til Hanne (øverst til høyre) slik at 0 eller 1 skal overføres fra horisontskanningfane og skal ikke være redigerbart. Stemmer det ikke? 
![image](https://user-images.githubusercontent.com/43623201/137177824-369ef317-d80b-4cf4-a4d6-3b2c3bbdb209.png)

**Comment by sindrely** [comment]
OK, det kan godt hende at jeg har missforstått noe da. Jeg baserte meg på skriptene fra Hanno hvor det står:
![bilde](https://user-images.githubusercontent.com/91675679/137258284-dd1337e8-5567-41f8-9a75-479f971f46d0.png)

![bilde](https://user-images.githubusercontent.com/91675679/137258176-47d182b0-20fb-4fb8-a08b-2dcb416d0fbe.png)

@AneMarlene  kan du oppklare denne?

**Comment by AneMarlene** [comment]
begge to har i grunn rett. For alle dørstokkarter som kommer via horisontskanningen, så skal verdien settes til 0 eller 1 om en av disse ble valgt på horisontskanning. FOr de som valgte "2 eller flere" skal det ikke være noe forhåndsutfylt. En del dørstokkarter kommer også direkte til risikovurdering (de var risikovurdert, dvs. NK,LO,PH,HI eller SE, i 2018). For disse artene er det ingen forhåndsutfylling. 

Det er også slik at om eksperten som vurderer en dørstokkart som kom via horisontskanning med 0 eller 1 på etableringspotensialet, så kan det hende at ved grundigere undersøkelse så innser de at dette taller var feil. Da må det også gå an å redigere (slik Sindre prøvde, men ikke fikk til). Det burde imidlertid komme opp et varsel ved forsøk på endring i slike tilfeller. Noe ala "verdien stemmer ikke overens med etableringspotensialet anslått under horisontskanningen (1 eller 0). En endring i antall forekomster må begrunnes i oppsummeringen."

**Comment by steinho** [comment]
@AneMarlene og @sindrely 
Jeg skal prøve meg på å tolke det over:
a) Hvis vurdert i 2018 (Alle?) - ikke overfør noe til dette feltet?
b) Hvis ny og horizontscannet - at noen har valgt 0 eller 1 på Etableringspotensial - skal denne settes på Occurence1best?
Er dette korrekt?

Det med overføring av verdier og ha ett felt redigerbart samtidig - kan fort bli kluss.
Kanskje enklere om vi setter denne verdien i en nattjobb etter horisontscanningen - før fullvurdering starter. 
De kan redigere som de vil etterpå - men at det da dukker opp en advarsel hvis b) og verdien avviker fra 0 og 1 respektivt?

**Comment by bugdriven** [comment]
Tror det bør være mulig å få dette til (?), men det er ikke helt rett frem.
F.eks: Hva skjer (eller skal skje) når en vurdering flyttes mellom horisontskanning og full vurdering?

Denne henger muligens sammen med #173

**Comment by sindrely** [comment]
@steinho a- og b) er korrekt. Og jeg tror at det du foreslår:
"De kan redigere som de vil etterpå - men at det da dukker opp en advarsel hvis b) og verdien avviker fra 0 og 1 respektivt?"
Virker lurt.
Ang. Det @bugdriven skriver om flytting mellom horisontskanning og full vurdering;
Hvis arter kommer fra en 2018 vurdering og over til horisontskanning, så er det horisontskanninga som skal gjelde. Dvs verdien som evt. overføres er det som skrives på horisontskanninga (0 eller 1).

**Comment by bugdriven** [comment]
Kan vi ikke flytte fram og tilbake?

**Comment by bugdriven** [comment]
Denne virker død. lukker.
