### ISSUE TITLE
Geografisk variasjon

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#18]
Her kommer et nesten ferdig utkast på fanen geografisk variasjon. Selve utsende med tekst er satt, men det gjenstår noen detaljer når det kommer til logikk/hvilke arter fanen skal være tilgjengelig for ol. 
[FAB-fane Greografisk variasjon_310521_commHH_AMM.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6591470/FAB-fane.Greografisk.variasjon_310521_commHH_AMM.pptx)

**Comment by AneMarlene** [comment]
@Hannemor @olgahil : Denne fanen har fortsatt et par kommentarer vi må ta stilling til.

**Comment by olgahil** [comment]
Er det greiest å ta runden i TEAMs kanskje så slipper vi å hefte Svetlana med alle våre krumspring. Vi legger konklusjonen her.

**Comment by AneMarlene** [comment]
Smart, Olga. Det gjør vi :)

**Comment by svetlnaumova** [comment]
Ser at det kanskje er noe som skal endres, men lukker issuen likevel - ser ut som selve fanen fungerer bra, og hvis det er noen små ting som skal fikses, kan vi opprette egne issuer for det :)
