### ISSUE TITLE
Navneid-endring

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#181]
Det er et navn på en sopp i FAB jeg ikke får til å stemme med det som er oppført i kongefila og i Fremmedartslista 2018. 
![image](https://user-images.githubusercontent.com/58254444/137108233-a01e0654-9429-4a2e-be05-ee73711f3379.png)

Som du ser på bildet, så er arten lagt inn i FAB under artsnavnet Agrocybe cylindrica (mens det nye er Agrocybe cylindracea). Det som er merkelig, er at arten, i følge fremmedartslista 2018 og i følge kongefila, ble vurdert under riktig navn (Agrocybe cylindracea): 

https://artsdatabanken.no/fremmedarter/2018/N/2533

Denne burde legges direkte inn i basen med det riktige navnet, uten en kommentar om endring. Det bør fikses før komiteen starter arbeidet nå på tirsdag (19. oktober).

**Comment by AneMarlene** [comment]
@steinho den nye bør henge på nytt gyldig navn ja. Den gjorde ikke det i basen slik det var, og dette må vi endre :)

**Comment by steinho** [comment]
Det er denne vi snakker om?
![image](https://user-images.githubusercontent.com/3253353/145729075-ea1d79b7-9e24-40d4-a123-9aaf9987f2ef.png)
Er fortsatt forvirret - i fab 3 -2018 ligger den som http://www.artsportalen.artsdatabanken.no/#/Artsnavn/Agrocybe+cylindrica/61123.

Det har trolig i forbindelse med publisering av resultatene i 2018 vært gjort noen taksonomiske endringer, men den vi importerte til 2021 basen lå på dette navnet - og så kjørte jeg en navnevask i nye produksjonsbasen - og den foreslår denne endringen.

**Comment by steinho** [comment]
@AneMarlene - trenger mer info her ... er usikker på hva du mener - hva som er feil?

**Comment by AneMarlene** [comment]
@steinho Her fikk du ikke mye svar. Tror jeg skjønner hva du sier over her, så dette ender egentlig bare opp med å være en taksonomisk endring vi kunne gjort automatisk for ekspertene, men som per nå ligger inne som forslag på endring :) Jeg lukker denne.
