### ISSUE TITLE
Naturtypefanen: hovedøkosystem data 

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/Fremmedartsbase2023#183]
Siste elementet i naturtypefanen (hovedøkosystem) mangler koder og data.

**Comment by svetlnaumova** [comment]
Eveliina - det jeg mente i beskrivelsen var at vi mangler en måte å overføre eventuell data hvis det fantes noe lignende i tidligere versjoner av FAB.

**Comment by EveliinaP** [comment]
Jeg skal bekrefte med Olga om dette er no vi faktisk trenger her og så kommer jeg tilbake om dette.

**Comment by svetlnaumova** [comment]
Jeg lukker denne siden vi ble enige om å ikke vise hovedøkosystemer.
