### ISSUE TITLE
Ekspertene få tilgang til artenes status fane i horisontskanning

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#184]
VI opplevde hvert fall to ganger at når ekspert gå inn å skulle gjøre horisontskanning så gå de inn til fane om "status" som de ikke skulle ha tilgang til ennå. Men når vi prøvde igjen så fikk vi ikke det til da.

**Comment by AneMarlene** [comment]
Fiksen virker å være kjørt ut i drift. Jeg lukker issuet.
