### ISSUE TITLE
Får ikke editere referanser

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#186]
Referanser kan ikke oppdateres i driftsbasen. Jeg får beskjed om at lagring er OK, men når jeg går refresher sida og går tilbake til referansen, er den ikke oppdatert.

**Comment by steinho** [comment]
Har lagt ut en test på test - skal nå gå å oppdatere egne referanser

**Comment by EveliinaP** [comment]
Fungerer i test @steinho

**Comment by sindrely** [comment]
ser ut til å fungere
