### ISSUE TITLE
Flytt art - får beskjed om at arten allerede er  i listen - før man har valgt liste

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#188]
Jeg har Passer domesticus som potensiell dørstokkart. Ønsker å flytte til "selvstendig reproduserende", men får beskjed om at den allerede finnes i liste: 

![image](https://user-images.githubusercontent.com/58254444/138046363-512a1f93-a4cf-47eb-8885-9eb795cacff1.png)

**Comment by AneMarlene** [comment]
@svetlnaumova @bugdriven Skal jeg lukke denne ettersom løsningen nå gjør at flytting av art ikke berører "legg til ny art"?

**Comment by svetlnaumova** [comment]
Tror det er trygt å lukke, evt lage en ny issue på det som ikke fungerer akkurat med å flytte art. Feilmeldingen om at arten allerede finnes i listen skal i alle fall være borte før man gjør et valg.
