### ISSUE TITLE
Spredningsveier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#19]
Det aller meste er landet her, men det kan (les: vil mest sannsynlig) komme enkelte endringer i noen navn på kategorier som skal inn i rullegardinene. 
[Spredningsveier utkast_070521.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6615081/Spredningsveier.utkast_070521.docx)

**Comment by AneMarlene** [comment]
Her kommer oppdaterte underkategorier. Ettersom du ikke hadde startet på de, trenger du ikke å bry deg særlig om at noen er markert i gult (endret siden forslaget over) og noen i rødt (nye etter forslaget over), men den i gusjgulgrønn skal ikke lengre være med (men var med i forslaget over), så den kategorien skal altså ikke inn. Turkis farge handler om logikk-følger. Den fargen kan nok også se bort i fra på dette punktet. 
[Spredningsveier redigerte underkategorier.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6638264/Spredningsveier.redigerte.underkategorier.docx)

**Comment by AneMarlene** [comment]
Når det gjelder logikk mellom underkategoriene på "til innendørs--..." og "introduksjon til.." (det er vist i øverste dokument), så blir det noen endringer her også - har bare ikke rukket å se på det enda. :)

**Comment by svetlnaumova** [comment]
Lukker denne issuen siden det meste av funksjonaliteten er på plass nå.

**Comment by AneMarlene** [comment]
@svetlnaumova flere spredningsveier er forsvunnet i basen. F.eks. på forurensning av vare skal det være 11 kategorier, men det er bare 9 stk tilgjengelig i basen. Dette forklarer antagelig mismatchen i #23 også?

**Comment by svetlnaumova** [comment]
@AneMarlene nå har jeg sjekket flere ganger, og det ser ut som alle spredningsveier er på plass. Si ifra hvis du oppdager noe mer som mangler.

**Comment by AneMarlene** [comment]
Alt er på plass så vidt jeg kan se, @svetlnaumova. Jeg lukker :)
