### ISSUE TITLE
Norsk navn i eksportfil

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#200]
Pattedyrkomiteen ønsker seg norsk navn på den nedlasta excel-fila, er det mulig å legge til dette?

**Comment by AneMarlene** [comment]
@steinho Får du til å lure inn ei ekstra kolonne i eksporten? :)

**Comment by AneMarlene** [comment]
@svetlnaumova Det er denne issuen Stein snakket om. Det skal selvsagt ikke bare gjelde pattedyrkomiteen, men alle eksport, uavhengig av komite. :)
