### ISSUE TITLE
Visning av data for NR arter fra 2018

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#201]
Ekspertene ønsker mulighet å se data som ble skrevet om NR arter i tidligere vurdering allerede når de gjør horisontskanning på disse arter. Hvor mye arbeid skulle dette være @steinho ? Samme data er per i dag tilgjengelig i eksporten.

**Comment by EveliinaP** [comment]
Nå er jeg usikker om hva som bli riktig her og hvorfor det vises som NK da. Kanskje @AneMarlene vet bedre? Hva med å bruke den "skalVurderes": false fra JSON for å filtrere?

**Comment by AneMarlene** [comment]
@svetlnaumova Den "NK-kateogorien" som står inne på vurderingene til NR-artene er feil. Dette omtales i de to siste kommentarene i issue #143, men jeg tror vi burde lage eget issue på det (ettersom resten i det issuet er fikset) - jeg skal ordne det. 

Når det gjelder hvordan å finne de med NR fra 2018, så ligger de inne med "alienSpeciesCategory" = "NotApplicable", og så enten "notApplicableCategory": "canNotEstablishWithin50years", eller "notApplicableCategory": "traditionalProductionSpecie"

**Comment by svetlnaumova** [comment]
@bugdriven jeg ser at riskLevelText og riskLevelCode oppdateres i enhanceCriteria, men de metodene har ikke tilgang til "alienSpeciesCategory" eller "notApplicableCategory", så de "ser" ikke om arten har blitt vurdert tidligere og derfor setter kategorien som NK hvis riskLevel == 0. Hva å gjøre?

**Comment by EveliinaP** [comment]
Sent i prosessen å legge innsats på dette
