### ISSUE TITLE
Nytt gyldig navn - alge

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#203]
Algen Symphyocladia tanakae har fått nytt gyldig navn. Vi må derfor oppdatere dette i basen. Riktig navn skal være Symphyocladiella dendroidea:

http://www.artsportalen.artsdatabanken.no/#/Artsnavn/Symphyocladiella+dendroidea/220190

**Comment by AneMarlene** [comment]
-Dette ordner jeg så fort Helge har gjort ferdig funksjonaliteten for flytt art.

**Comment by steinho** [comment]
@AneMarlene - er denne i orden nå - flytt art og flytt denne?

**Comment by AneMarlene** [comment]
@steinho den er ikke i orden. Funksjonalitet for å flytte over på gyldig navn er ikke ferdig: 

![image](https://user-images.githubusercontent.com/58254444/144816197-c698e4f7-64c2-45a6-876c-a6b88845e98f.png)

**Comment by EveliinaP** [comment]
Jeg testet, fikk ikke flyttet. Jeg få enten melding at "Arten er allerede i liste" eller den som stå ovenfr om at funskjonen er ikke ferdig implementert.

**Comment by AneMarlene** [comment]
@steinho Det er som Eveliina sier. Den er kanskje ikke helt funksjonabel i frontend enda om den fungerer backend?! Her er eks. på en karplante hvor jeg søkte opp det nye gyldige navnet: 

![image](https://user-images.githubusercontent.com/58254444/154957735-484c8fee-cb26-45db-a629-15c52d5c8f46.png)
