### ISSUE TITLE
Feil kategori inne på artene - viser NK uavhengig av faktisk kategori i 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#207]
Det står feil kategori her inne (for alle hvor korrekt kategori fra 2018 ikke er NK). Alle arter (så vidt jeg kan se) har NK der, uavhengig av hva den korrekte kategorien er (f.eks. LO, HI, PH). Dette gjelder også de som var Ikke risikovurdert NR i 2018. 

Eksempler: 
Fra risikovurdering: Denne karplanten var PH i 2018: 

![image](https://user-images.githubusercontent.com/58254444/139815484-b402616e-6048-473d-8c02-9a9bcec2ffd6.png)

Fra horisontskanning: Denne karplanten var NR i 2018: 
![image](https://user-images.githubusercontent.com/58254444/139815572-a325b28b-0919-4ca1-b8e0-66e101dc1294.png)

Se også @svetlnaumova sin kommentar i #201

**Comment by svetlnaumova** [comment]
Det stemmer ikke helt - algen Ulva australis f.eks (og noen flere alger) har en annen kategori enn NK. Men jeg ser imidlertid at kategorien er kanskje feilberegnet. @bugdriven kunne du sett på dette?

![Uploading image.png…]()

**Comment by svetlnaumova** [comment]
@bugdriven jeg har sett litt på arter som har fått feil kategori, og det virker som om der hvor det ble brukt utgåtte metoden på A-kriteriet, har vurderinger ascore == 0, hvilket er rart. Stemmer det at verdiene som påvirker riskLevel nullstilles når man starter å jobbe med vurderingen? Det kan forklare feil ved beregningen av kategori.

**Comment by bugdriven** [comment]
Skjønner ikke dette. 
Når jeg tar opp Abies concolor, så kommer den ut som:  Arten er ikke fremmed, skal ikke risikovurderes, og den blir NR.
Hva er galt med dette?

**Comment by bugdriven** [comment]
@AneMarlene den over her?

**Comment by AneMarlene** [comment]
@bugdriven - ja, bra du minte meg på den. Den virker å være rett for arter som er risikovurdert nå, men den viser feil for NR-arter: (her ser du forøvrig også en "feil" i feilrapporten ettersom dette er en art hvor det ikke trenger å fylles ut noe på forekomstareal - men det er en annen sak :) ) 

Eksemplifisert med nyseryllik:
![image](https://user-images.githubusercontent.com/58254444/152538497-62f6864e-f1a6-47aa-9385-9fb9d6246a3e.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror at kategoriene på toppen vises riktig for NR-arter også nå. Stemmer det at feilmeldinger som gjelder faner "Risikovurdering", "Klimaeffekter" og "Geografisk variasjon" ikke skal vises for NR-arter?

**Comment by AneMarlene** [comment]
@svetlnaumova Ja, det stemmer. Og du har rett i at den nå viser rett også for NR-arter. Skal jeg legge inn det om feilmelding et nytt issue? (denne kan ellers lukkes)

**Comment by svetlnaumova** [comment]
@AneMarlene ja, det er fint med et nytt issue angående feilmeldinger. Jeg lukker denne da.
