### ISSUE TITLE
Rundormer og flatormer som skal ut fra horisontskanningen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#209]
I denne fila ligger det fem arter markert med gult, samt en ikke-markert art som skal ut fra horisontskanningen. Svar fra Haakon Hansen per mail avgjør om de skal helt ut (hjemlige) eller flyttes til risikovurdering. 

[Redigering_Artliste_HH_EK_rundormer_flatormer_arter_som_skal_ut.xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7459505/Redigering_Artliste_HH_EK_rundormer_flatormer_arter_som_skal_ut.xlsx)

Avventer funksjonalitet fra Helge før jeg får flyttet de aktuelle.

**Comment by AneMarlene** [comment]
Svar fra Haakon: 

De tre artene som er fiskeparasitter er parasitter hos leppefisk og sannsynligvis naturlig forekommende her. Ikke fremmede arter. 

Dette gjelder M. donavani, Gaevskayatrema perezi og Macvicaria. De andre må du høre med Christer og Inger om.

Disse skal mao slettes fra basen.

**Comment by AneMarlene** [comment]
@sindrely - sletter du de tre artene Haakon nevner over her fra FAB? Du kan se fullt vitenskapelig navn på de i xlsx fila. Alle tre (pluss 2 til - så ikke velg feil navn) er markert med gult i fila.

**Comment by sindrely** [comment]
M. donavani, Gaevskayatrema perezi og Macvicaria er sletta nå

**Comment by AneMarlene** [comment]
Andre endringer her: 
Rotylenchus buxophilus og Rotylenchus robustus er selvstendig reproduserende. Disse skal flyttes til risikovurdering.

**Comment by sindrely** [comment]
Rotylenchus buxophilus og Rotylenchus robustus er flytta

**Comment by AneMarlene** [comment]
Ditylenchus dipsaci og D. destructor er flytta til risikovurdering. Antar disse er fremmede. 
Valipora campylancristrota er bekreftet reproduserende fremmed. Da er alle artene det var kommentarer på i denne fila håndtert. Jeg lukker issue.
