### ISSUE TITLE
Fugler over på gyldig navn

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#210]
Alle NR-fugler i horisontskanningen skal føres over på gyldig navn. Dette er godkjent av komiteleder og skal gjøres av oss. Merk: de har begynt arbeidet, så dette må ikke "overskrive" jobben de evt. har gjort. 

Hvis mulig kunne vi også merket alle takson-kommentarene på disse artene som "behandlet". Vet ikke om det krever mye arbeid..?

**Comment by steinho** [comment]
Alle fugler: Flytte over på gyldig takson for navnet....
