### ISSUE TITLE
Utbredelse - småplukk under forekomstareal for selvstendig reproduserende arter 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#214]
Oppdaget noen ting som ikke har blitt med inn under forekomstarel (mulig de lå inne før?). Dette gjelder ikke dørstokkarter, kun selvstendig reproduserende arter. 

1. Her mangler en rullegardinmeny med følgende valg (skjermbilde): 
![image](https://user-images.githubusercontent.com/58254444/140055655-0e7c216d-ba21-4830-8a5d-75fe5f8c4fd2.png)

2. Her skal spørsmålet endres, og alternativer i form av radioknapper tilkomme under spørsmålet:

Hvilken etableringskategori har arten i Norge? Merk av den høyeste (øverste) kategorien som oppfylles av arten i Norge i dag 
o Arten har minst ti etablerte bestander i norsk natur som ligger minst 2 km fra hverandre og fra alle steder som arten har blitt introdusert til (E)
o Arten har minst én etablert bestand i norsk natur som ligger minst 2 km fra alle steder som arten har blitt introdusert til (D2)
o Arten er etablert i norsk natur og har levedyktige individer på minst ett sted som ligger 2 km fra alle steder som arten har blitt introdusert til (D1)
o Arten er etablert i norsk natur (C3)

**Merk:** Her bør ikke svaralternativ E være tilgjengelig med mindre arten faktisk har minst 10 (kjente og/eller antatte) forekomster, dvs. et «antatt forekomstareal i dag» på minst 40 km2. Motsatt kan man jo også vurdere om E over et visst forekomstareal blir valgt automatisk (altså at svaralternativene C3 til D2 blir utilgjengelige), f.eks. fra 400 km2.
 

3. Vi trenger en mulighet til å laste opp fil nederst i bolken om forekomstareal. Denne kan få lik utseende og funksjonalitet som under A- og B-kriteriet. Altså, slik før noe er valgt: 
![image](https://user-images.githubusercontent.com/58254444/140057425-8dce2286-550c-43db-8d5a-ad0d17dca853.png)

![image](https://user-images.githubusercontent.com/58254444/140056809-49bd5e6d-ea31-4ab7-92e6-196ad59bee85.png)

**Comment by AneMarlene** [comment]
Mulig du har lagt merke til det, Svetlana, men de valgene som var inne fra før, samt tekst i "spm" skal endres. Dette er altså gammel versjon: 

![image](https://user-images.githubusercontent.com/58254444/140299221-d37fdf6e-dc28-46ad-8a6b-e12d800732f9.png)

Se beskrivelse av issuet for ny versjon :)

**Comment by svetlnaumova** [comment]
Det er nettopp det som jeg driver å fikse nå - skal være ute straks :)

**Comment by svetlnaumova** [comment]
Er «antatt forekomstareal i dag» det samme som "AOOtotalBest" (beste anslag (median))?

**Comment by AneMarlene** [comment]
@svetlnaumova vi har diskutert videre (med eksterne) etter at jeg åpnet dette..(hehe..) Teksten, og logikken rundt punkt 2 her er derfor endret. Jeg åpner eget issue på det. Om det kun var logikk rundt punkt to som gjensto på dette issuet kan du derfor lukke denne. :)

**Comment by svetlnaumova** [comment]
@AneMarlene det er også funksjonalitet for å laste opp filer som ikke er helt ferdig i alle fanene ennå, men siden det finnes eget issue på det også, lukker jeg denne :)
