### ISSUE TITLE
Kart - lagring av endringer i kart fungerer ikke

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#216]
Når man fjerner og/eller legger til punkter i kartet, forså å velge "overfør arealer..." og trykke "lagre", så får man lagring OK, men neste gang man åpner kartet er valgene man hadde gjort fjernet.

**Comment by olsoybakk** [comment]
Det manglet noen parametre i modellen. Jeg la til ArtskartAdded og ArtskartRemoved som ser ut til å løse problemet.

@AneMarlene kan du ta en titt og se om lagring fungerer nå?

**Comment by AneMarlene** [comment]
Nå fungerer det etter en enkel test :) Jeg lukker denne da - om det oppstår ny lagringstrøbbel får vi åpne en ny en ;)
