### ISSUE TITLE
Utbredelse - småplukk på tabell over fylker o.l.

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#217]
Fylkes-tabellen som nå ligger i basen trenger noen justeringer (nummer refererer til nummer i skjermdump). 
1. Bytt ut ordet Fylkesvis med Områdevis
2. lag et litt større mellomrom - eller marker med linje  -  mellom siste havområde og Jan Mayen, og mellom  Svalbard og første fylke.
3. Trøndelag byttes ut med gamle, utdaterte Sør-Trøndelag og Nord-Trøndelag (som to separate listepunkt)

I tillegg trenger vi checkbokser i stedet for radioknapper.

![image](https://user-images.githubusercontent.com/58254444/140029249-72e0203f-22fb-488f-aded-ae4ba1b7eebd.png)

**Comment by olsoybakk** [comment]
@AneMarlene Jeg ser på dette nå og skulle legge inn Sør- og Nord-Trøndelag, så ser jeg at her er alle de gamle fylkene før reformen. Stemmer det at vi skal ha de gamle fylkene fra 2017?

**Comment by olsoybakk** [comment]
![image](https://user-images.githubusercontent.com/10737686/142260713-a01ae7ab-0caa-4c30-ba24-059e4a64a65f.png)
commit nr 1000 🤓

**Comment by olsoybakk** [comment]
@AneMarlene Denne er vel 🆗 nå?

**Comment by AneMarlene** [comment]
@olsoybakk Det er fortsatt radioknapper i test-basen. Er check-bokser på vei? Det er på en måte direkte knyttet til ønsket om tre forskjelige kart, så kanskje det kommer sammen med den biten? Eller virker denne issuen ok ja :)

**Comment by olsoybakk** [comment]
@AneMarlene Pkt 1, 2 og 3 skal være ok nå. Jeg fiksa nytt kart, mulig litt vel mye detaljer...
Sjekkbokser er på vei. Krever endring på klient og server.

**Comment by AneMarlene** [comment]
Kartet er fint, men vi skal jo ha 3 kart (ikke 1.) :) Synes ellers det var pent med mye detaljer i kartet.

**Comment by AneMarlene** [comment]
...men det med 3 kart er ikke i dette issuet altså, så om checkboksene er på vei kan vel denne lukkes antagelig?
