### ISSUE TITLE
Kartutvalg lastes ikke ned som dokumentasjon

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#218]
Som i rødlistebasen ønsker vi at observasjonene i Artskart som ligger til grunn for vurderingen, inklusive fjernede og tillagte ruter lastes ned som en .csv fil.

**Comment by steinho** [comment]
Trenger kart-utvalgsparametrene på vurderingen - slik at de kan brukes til dette på baksiden - som i rodlistebasen. @olsoybakk ser på dette

**Comment by steinho** [comment]
@AneMarlene - kan testet for alle unntatt regianalt fisk

**Comment by AneMarlene** [comment]
@steinho - da har jeg testa på en stk karplante, Abies amabilis. Det er noe feil her. Jeg har følgende utvalg i kartet, hvor jeg altså har fjernet ett punkt og lagt til et punkt. Jeg har da totalt 4 "gamle" og 1 nytt punkt med som grunnlag på vurderingen: 

![image](https://user-images.githubusercontent.com/58254444/151977842-c8dcbd66-d248-4b77-80f0-eb7fe09b7af2.png)

Det førte til følgende fil, med to tomme rader og 3 rader med informasjon:
[Abies amabilis (1).xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7978796/Abies.amabilis.1.xlsx)

**Comment by steinho** [comment]
@AneMarlene  kan testes nå

**Comment by AneMarlene** [comment]
@steinho Nå lastes de ned, og etter hva jeg kan se er det riktig. Eneste jeg stusser på er at jeg må gå ut av fanen "utbredelse" og inn igjen for at jeg skal få sett at en datafil er lasta ned. Er det mulig å ordne så fila vises i oversikten med en gang?

**Comment by steinho** [comment]
> @steinho Nå lastes de ned, og etter hva jeg kan se er det riktig. Eneste jeg stusser på er at jeg må gå ut av fanen "utbredelse" og inn igjen for at jeg skal få sett at en datafil er lasta ned. Er det mulig å ordne så fila vises i oversikten med en gang?

Tenker det er en pri 2 sak - som jeg må høre med @bugdriven om..... listen med filer 'ligger' på vurderingen - og da må trolig hele vurderingen lastes på nytt - hver gang man lagrer da datasettet blir lagt til på server siden..... Usikker på om det er noen quickfix på dette...
