### ISSUE TITLE
Naturtypefane: visning av gamle livsmedium data

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#222]
Import gamle data fra 2018 vurdering om livsmedium. Lage tabell under nå værende livsmedium data valg.

**Comment by AneMarlene** [comment]
@EveliinaP Er ikke livsmedium fortsatt NiN 1.0?

**Comment by AneMarlene** [comment]
Her er fra issue #11 : 

![image](https://user-images.githubusercontent.com/58254444/143424773-5bfa391f-c55a-49cc-a681-69ffacef9f65.png)

En relatert sak, livsmedium er nå plassert øverst på siden. Den skal være nederst, rett over "Hovedøkosystem". (se forslag til Olga i #11)

**Comment by EveliinaP** [comment]
Livsmedium er i NiN1 og ja, vi bør se på rekkefølge av hvordan ting vises men jeg anser at selve livsmedium data nå vises riktig.

**Comment by EveliinaP** [comment]
Eksempler på arter som hadde info om livsmedium sist: stillehavsøsters og Aedes japonicus. Kanskje disse vil gjøre det lettere å finne hvor i databasen disse dataene er plassert.

**Comment by svetlnaumova** [comment]
Det er sannsynligvis denne her? Ser at de har litt andre navn på felt enn de som vi har i FAB4, men vi burde klare å vise dem på en eller annen måte. 
![image](https://user-images.githubusercontent.com/43623201/147488021-174fedff-4532-4382-b184-516f58a05526.png)

**Comment by EveliinaP** [comment]
Kanskje dette bør være på plass før vi gå videre til å legge til ny livsmedium data i tabellen #295

**Comment by svetlnaumova** [comment]
Det er et godt poeng, men jeg klarte dessverre ikke å finne data om livsmedium i JSON-fila til disse artene. Vet du ca hva som er lagt inn der (tall, koder, noe annet)?

**Comment by EveliinaP** [comment]
Jeg mener at Olga sa at disse er ikke importert i selve JSON men er i database. Så det er vel @bugdriven som må finne og få dem importert først?

**Comment by svetlnaumova** [comment]
@EveliinaP det ser ut til å være fikset både for stillehavsøsters og Aedes japonicus.

**Comment by EveliinaP** [comment]
Enig, virker som de er overført riktig hvert fall for disse to arter.

**Comment by AneMarlene** [comment]
@steinho dette er et issue du sikkert burde være oppmerksom på i arbeidet med å få livsmedium skilt ut fra øvrige naturtyper under migreringen?
