### ISSUE TITLE
Naturtypefane: Data fra tidligere Rødlista for naturtyper

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#223]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25793207/140531040-5bf0dc87-acfd-41d0-bde0-4f15f182d8af.png)
Der data er tilgjengelig fra tidligere vurdering vise hvilke rødlistet naturtyper arter har kolonisert og påvirker i tabell under valg i nå værende vurdering. Eksempel gitt i bildet med bare bytte tekst i parenthesis til: (basert på Rødlista for naturtyper 2018 og NiN 2.0)

**Comment by svetlnaumova** [comment]
Har byttet teksten, men er usikker på om det var noe mer som var feil - tabellen med rødlistede naturtyper ser greit ut for meg (på de vurderingene der det finnes data). Får man lukke den eller er det noe jeg har oversett?
