### ISSUE TITLE
Utbredelse - tekst og logikk under forekomstareal for selvstendig reproduserende arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#224]
Teksten i denne bolken, byttes ut med den nedenfor: 
![image](https://user-images.githubusercontent.com/58254444/140879354-dc5a9995-4cbe-4b4e-9f51-f05feb305592.png)

o Arten har selv spredd seg fra ett eller flere introduksjonssted(er) og er etablert i minst ti av forekomstene (E)
o Arten har selv spredd seg fra ett eller flere introduksjonssted(er) og er etablert i minst én av forekomstene (D2)
o Arten har selv spredd seg fra ett eller flere introduksjonssted(er), men er kun etablert der den er introdusert (D1)
o Arten forekommer kun der den er introdusert (og er etablert der) (C3)

Disse punktene har følgende logikk: 
1. Ingen av punktene, eller spørsmålet forøvrig, vises for arter som har krysset av C2 under artens status. Snudd på hodet: Disse spørsmålene er kun synlig på fanen om eksperten har krysset av C3 på artens status. 
2. E bare vises hvis AOO >= 40 km²
3. D1 og D2 bare vises hvis AOO >= 8 km²
4. C3 alltid vises hvis C3 ble valgt på artens status. C3 vil også være automatisk avhaket for alle som spørsmålet vises for (dvs. alle med C3 på artens status).

**Comment by svetlnaumova** [comment]
@AneMarlene Beklager hvis det er et dumt spørsmål, men lurer på hvilken AOO det er snakk om siden det ikke ble helt avklart i forrige samtale:
![image](https://user-images.githubusercontent.com/43623201/140942856-f1125397-9aec-4cce-ac0f-3fbfbbb12813.png)

**Comment by AneMarlene** [comment]
Et veldig godt spm, Svetlana :) Det er snakk om AOOtotalBest :)

**Comment by svetlnaumova** [comment]
Den er ikke spesielt fin foreløpig, men fungerer som den skal - gi beskjed om det er noen bugs likevel :)

**Comment by AneMarlene** [comment]
Den er grei :) Jeg skal få sjekket. Mulig det blir enda en runde med små tekstjusteringer da. Det diskuteres litt enda.. :)

**Comment by AneMarlene** [comment]
Det virker å fungere slik vi tenker nå :) Etter hva jeg kan se.
