### ISSUE TITLE
Artens status - etableringskategorier som vises for dørstokkarter + logikk for alle arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#225]
Vi har innsett at de to øverste kategoriene (markert med 1) også bør vises for dørstokkarter. Dette fordi en dørstokkart kan endre status til selvstendig reproduserende. 

![image](https://user-images.githubusercontent.com/58254444/140896969-f648f896-7a34-4c84-af97-378c34fceb67.png)

Så kommer logikken. Disse omfatter både dørstokkarter og selvstendig reproduserende arter:

Om en dørstokkart velger en av nivåene markert med 1 over, endrer den status til selvstendig reproduserende. 

Om en selvstendig reproduserende velger en av nivåene markert med 2 under, endrer den status til dørstokkart.

Konklusjonen for alle arter som har valgt C2 eller C3 blir (GITT at det er svart "nei" på spm om etablering per 1800, eget issue opprettes på dette, og at den ellers oppfyller krav for risikovurdering): 

![image](https://user-images.githubusercontent.com/58254444/140913745-beeabf77-1879-4cc6-89ee-b1aa041c882a.png)

Konklusjonen for alle arter som har valgt en av A til og med C1 blir (GITT at det er svart "nei" på spm om etablering per 1800, eget issue opprettes på dette, og at den ellers oppfyller krav for risikovurdering): 

![image](https://user-images.githubusercontent.com/58254444/140914052-879ae9ee-b0d0-40d3-87b3-4a76642b3cc6.png)

Merk da at utseende på fanene som følger (der hvor de har ulik utseende for dørstokkarter og øvrige), bestemmes av svarene her (og ikke om den var dørstokkart i 2018 eller ei).

**Comment by AneMarlene** [comment]
Nå er det kanskje en bug her, Svetlana. På denne mosen får jeg ikke opp alle nivåer, med mindre jeg velger "ja" på bruksart:

![image](https://user-images.githubusercontent.com/58254444/141126144-4e578774-f61e-4717-af83-020fa5314daf.png)

men bruksart-spm bestemmer ikke at de øverste nivåene skal vises. Mener det fungerte nettopp. Rare greier :D

**Comment by svetlnaumova** [comment]
@AneMarlene jeg er ganske sikker på at det ble fikset nå, men kunne ikke sjekke fordi jeg ikke har tilgang akkurat til denne mosen. Gi beskjed hvis du fremdeles ser at det er feil :)
