### ISSUE TITLE
Artens status - konklusjon før alle svar er gitt. 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#226]
Konklusjonen vises før alle vesentlige svar som avgjør konklusjonen er gitt. Bl.a. kan det stå at arten skal risikovurderes, eller ikke skal risikovurderes før det er avgitt svar på om arten var etablert per 1800. I følgende eksempel har jeg kun svart "ja" og "regionalt fremmed" = TRUE på første spm. Ellers er alt ubesvart. Jeg tror logikken var riktig her i en tidligere versjon av artens status, så mulig koden ligger der et sted?! :)

![image](https://user-images.githubusercontent.com/58254444/140915503-31b578a2-35e4-41b6-9dcd-5b0f3593fc2a.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror ikke at selve logikken har blitt endret (men skal selvfølgelig dobbeltsjekke), men det som skjedde for ikke så lenge siden er at datatypene til alle "Ja"/"Nei" svarene har blitt endret til bool og kommer automatisk inn som "false" før man har gjort et valg, så det kan være noe sammenheng her. Jeg og @bugdriven skal se på det.

**Comment by AneMarlene** [comment]
Supert :) Mente det fungerte supert før (men lenge siden jeg testet), så tipper det er noe dere får til å trylle fram igjen ;)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg la til en test som gjør at konklusjonen ikke vises før man har gjort flere valg enn bare det første, men det er bare å åpne issuet igjen hvis det viser seg at ikke fungerer helt som det skal.
