### ISSUE TITLE
Flytt art - bli sendt til inngangssiden etter at flytting er utført

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#227]
Etter at man har trykt på "flytt art" mellom horisontskanning og risikovurdering, hadde det vært suverent å bli sendt automatisk tilbake til inngangssiden igjen. Altså, at man ikke bare ender opp med dette og lurer på om knappen egentlig fungerte eller ikke: 

![image](https://user-images.githubusercontent.com/58254444/141111862-7cc5faee-861a-49dc-bd58-a396bc38b684.png)

**Comment by bugdriven** [comment]
fixed
