### ISSUE TITLE
Flytt art - kategori 2023 på nye, potensielle dørstokkarter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#229]
Slik det er nå får nye potensielle dørstokkarter, som flyttes over i kategorien som "selvstendig reproduserende" automatisk en kategori for 2023 i inngangslisten. Den burde vel i slike tilfeller være tom? 

![image](https://user-images.githubusercontent.com/58254444/141122501-992c9971-d329-46c5-9a06-9d2ecac6866c.png)

**Comment by AneMarlene** [comment]
Om man flytter en NR-art fra 2018 fra horisontskanning og over til risikovurdering, så får vi en lignende feil. Her kommer NK opp som kategori 2023.. Det er vel også litt rart?

![image](https://user-images.githubusercontent.com/58254444/141263879-e8e97c80-eb7d-4fc5-a1f6-179cd585117b.png)

**Comment by steinho** [comment]
Skal se på muligheten til å fange opp at det ikke er gjort noe på risikovurdering - og la den stå med blank kategori

**Comment by steinho** [comment]
@AneMarlene - har du nytt eksempel ... finner ikke denne lengre...
