### ISSUE TITLE
Migrering - spredningsveier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#23]
Når data fra 2018 lastes inn, er det fint om "hovedkategori" på spredningsvei (og importvei) vises i tabell. Altså at det for eksempel står "Direkte import" under hovedkategori, i stedet for at denne kolonna er tom (ettersom denne kolonna ikke vistes i 2018): 

![image](https://user-images.githubusercontent.com/58254444/122752698-8fd31b80-d291-11eb-9285-bb7b73def19b.png)
 

Slik det er nå kommer "introduksjon" eller "spredning" inn som kategori når det var fylt ut noe på spredningsveier i 2018. Dette er feil. Hvor havner forresten spredningsveiene som var fylt på import i 2018 (importveiene)? Det er de som skal overføres til "Til innendørs- eller produksjonsareal". Når nye spredningsveier legges til, kommer også "introduksjon" inn på kategori. Her er et bilde som beskriver hva som skal hvor når det velges fra listen: 

![image](https://user-images.githubusercontent.com/58254444/133396223-dd969726-3f42-4489-8b71-adac852d043a.png)

 Noe smått i tillegg: Ordet tidspunkt i tabellen og pop-up vindu skal byttes ut med "Tidsrom" - og legg til knappen hadde vært fint å få på en linje. :) 

![image](https://user-images.githubusercontent.com/58254444/133396573-24fa750d-6e21-4eb0-a5d0-aa09c400a0d1.png)

**Comment by svetlnaumova** [comment]
Nå tror jeg at denne begynner å bli ferdig, men jeg har et par spørsmål. Forstår jeg riktig at spredningsveiene fra 2018 skal legges inn i tabellen under "Til innendørs- ..."-bolken og bare dit, mens tabellene under de to andre bolkene skal stå tomme til å begynne med? Og hva skal parametre "introduksjon" og "spredning" brukes til - bare for å skille mellom "Introduksjon til natur" og "Videre spredning"?

**Comment by AneMarlene** [comment]
Hei, nå ser jeg at jeg (nok en gang) har brukt et noe uheldig eksempel. Hehe :) det som skal til "til innendørs..." er det som var fylt ut under denne fanen i fab3: 
![image](https://user-images.githubusercontent.com/58254444/134328512-dbdb47b4-b7df-47f0-9a78-7a72965a0943.png)

Det som skal til  "Introduksjon til natur" og "Videre spredning" (som var skilt med "introduksjon" og "spredning" i 2018), var fylt inn på denne fanen i 2018:

**Comment by AneMarlene** [comment]
@svetlnaumova  Jeg ser det er noen spredningsveier som ikke har blitt med over. Dette gjelder antagelig de hvor navn har blitt noe endret. F.eks. på denne arten: 
![image](https://user-images.githubusercontent.com/58254444/135401403-14393c35-b1aa-4690-932c-406c16ce0a31.png)

Jeg skal finne en oversettelse for disse kategoriene.

**Comment by svetlnaumova** [comment]
Dette skjedde fordi noen kategorier har blitt slettet i denne versjonen av basen. Det går sikkert an å legge dem tilbake, men da må vi (jeg) tenke på hvordan å gjøre det slik at de ikke vises som et tilgjengelig valg.

**Comment by AneMarlene** [comment]
Ja, det er noen som har blitt "slettet" fordi de har fått ett nytt navn. Jeg skal få laget en liste over de navnene i 2018 det er som har endret navn, slik at du kan overføre disse til nytt navn. Om det ga mening (og løser problemet)?

**Comment by svetlnaumova** [comment]
Ikke helt. Selve endringen av navnet gjør ikke veldig mye, men når hele verdien er slettet fra kodeliste, finnes det heller ikke navn. I eksempelet ditt er det en verdi "transportationOfHabitatMaterial" som mangler i norske kodelisten (men er ikke slettet fra svenske og engelske) og derfor vises som det gjør nå. Men problemet løses så snart vi legger til kombinasjon av verdi + tekst.
![image](https://user-images.githubusercontent.com/43623201/135429840-af3c4e39-70ea-4c22-9a76-032e1d210c74.png)

**Comment by AneMarlene** [comment]
@svetlnaumova men hvorfor er hele verdien slettet fra kodebasen? Dette skal bare tilsvare et endringsnavn:
