### ISSUE TITLE
Utbredelse i Norge -0 som default i mørketall

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#231]
Inne på selvstendig reproduserende arter, så står det alltid utfylt et nulltall på mørketallet, og dette er det ikke mulig å endre. Bug?

@sindrely hvordan var funksjonaliteten tenkt i Hanno sitt skript? 

![image](https://user-images.githubusercontent.com/58254444/141470137-eeb26ad4-31c6-4881-976f-46628ae900dd.png)

**Comment by svetlnaumova** [comment]
@bugdriven jeg får denne feilmeldingen når jeg prøver å endre dette feltet. Det henger sikkert sammen med funksjonen i enhanceCriteria.js? 
![image](https://user-images.githubusercontent.com/43623201/141474500-f56629ec-658a-416c-b7af-33d06152a94d.png)

**Comment by sindrely** [comment]
Hvis jeg har skjønt Hanno riktig så skal den være AOOtotalBest / AOOknown, altså **Beste anslag (median)** / **kjent** 

![bilde](https://user-images.githubusercontent.com/91675679/141479268-d08c3d25-468e-4876-8c8a-c72935c7f892.png)

og:

![bilde](https://user-images.githubusercontent.com/91675679/141479323-26289f9a-2448-49d0-8835-c36dea7dd598.png)
