### ISSUE TITLE
Driftbasen - åpne risikovurdering for admin

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#232]
Dette valget bør åpnes for oss i ADB med adminrettigheter: 

@svetlnaumova er dette noe du har mulighet til å ordne? Eller er det andre på IT som bør tagges?

![image](https://user-images.githubusercontent.com/58254444/141775161-ed5648e4-a392-4a0c-a167-baf36db9642d.png)

**Comment by AneMarlene** [comment]
Viktig at det kun åpnes for oss, ikke for noen utenfor huset. :)

**Comment by svetlnaumova** [comment]
Tror at jeg får til å ordne det :)
