### ISSUE TITLE
Spredningsveier - redigere spredningsvei 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#234]
Når jeg skal redigere en spredningsvei, får jeg bare redigert en om gangen, så blir den "automatisk" lagret, og man må trykke rediger på nytt for å redigere en gang til. Mulig dette er en bug og at du er klar over det, men valgte å legge det ut issue likevel :) 

Det hadde vært fint om man kunne redigere på alle 3 med en gang, og så aktivt trykke på Ok når man selv følte man var ferdig:'

![image](https://user-images.githubusercontent.com/58254444/141784202-b3d26905-f214-462c-826b-48718bdd56e5.png)

**Comment by svetlnaumova** [comment]
Tror ikke det er en bug - det var slik i forrige versjonen av basen også hvis jeg ikke tar feil (men er usikker på hvorfor det har blitt implementert slik). Skal se om det er noe jeg kan gjøre her :)
