### ISSUE TITLE
Utbredelse - småfiks

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#236]
I øverste setning her, (gjelder også i tilhørende spm på Artens status), står det "kategori". Dette ordet skal endres til "klasse". Slik at det første ordet blir "etableringsklasse" (dette ordet skal også stå på Artens status i stedet for etableringskategori - se skjermdump nedenfor). 

Det trengs også større avstand mellom nederste punkt (C3) og datafil-bolken. 

![image](https://user-images.githubusercontent.com/58254444/141788603-1de5dc20-5398-470a-a492-1bf34a3d7bd7.png)

Fra artens status:

![image](https://user-images.githubusercontent.com/58254444/141788767-e1ccc2f6-d22d-43c5-a261-5fd363a0906a.png)

Her skal også ordet kategori byttes ut med klasse.

**Comment by svetlnaumova** [comment]
Det som du sier angående Artens status motsier issue #233 - hvilken tekst er riktig? :)

**Comment by svetlnaumova** [comment]
Og holder det med denne avstanden her eller bør den være enda større? 
![image](https://user-images.githubusercontent.com/43623201/141797194-2bd64107-cbd4-4742-889e-7194b96c4795.png)

**Comment by AneMarlene** [comment]
Den avstanden er fin, ser på B-kriteriet at det er lagt inn en liten horisontal strek over legg til fil, kanskje vi kan prøve med det på alle faner med denne muligheten: 

![image](https://user-images.githubusercontent.com/58254444/141836879-6654b1b2-4e1a-4588-81e6-8cea8e15755c.png)


Når det gjelder hva som er riktig i teksten av det jeg sier her og Sindre sier i #233, så er begge i grunn riktig. Det ble bare utelatt en vesentlig detalj i issue #233: Det issuet omhandler kun regionalt fremmede arter. Jeg ser også nå at vi må gjøre enda en liten endring i teksten for de regionalt fremmede artene: I stedet for "Hvilken status har artens regionalt fremmede forekomster i Norge?" skal det stå "Hvilken etableringsklasse har artens regionalt fremmede forekomster i Norge?
