### ISSUE TITLE
Horisontskanning med resultat NR

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#24]
Om en art som horisontskannes ender opp med en av følgende kombinasjoner går den **ikke** videre til full risikovurdering: 

![image](https://user-images.githubusercontent.com/58254444/133784422-764b614e-f6c9-4962-9ba2-2cd085be7c28.png)

På selve siden dukker det da opp en tekstboks hvor det står "Arten faller utenfor avgrensningen og skal ikke risikovurderes som dørstokkart." (se også issue "horisontskanningen"). Resultatet "på baksiden" i kategori er angitt i tabellen. 

@steinho Her ser du hvilken kategori med årsak, artene som IKKE går videre fra horisontskanningen skal ende opp i. Det er altså avhengig av hva eksperten har valgt på invasjonspotensialet og økologisk effekt.

**Comment by Hannemor** [comment]
Hei, jeg kjenner ikke igjen dette oppsettet helt. Jeg trodde man skilte på etableringspotensial 0, 1 og 2 og at det er kombinasjonen etableringspotensial 0 og 1 og ingen økologisk effekt som gir NR. Kombinasjonen 1 og økologisk effekt "Ja, men bare så lenge arten er til stede" er slik jeg husker det innenfor avgrensningen, men da som en form for "distanseeffekt" eller "effekt uten etablering". Litt uklart hva det skal kalles. Jeg har også forstått det slik at etableringspotensial 2 skulle gi risikovurdering uavhengig av økologisk effekt.

**Comment by AneMarlene** [comment]
Hanne, kombinasjonen du nevner er ikke gitt i forslaget mitt over heller. Var det kombinasjonen 0 og økologisk effekt "Ja, men bare så lenge arten er til stede" du tenkte på?

**Comment by Hannemor** [comment]
Å ja, dette er kombinasjoner som ikke går videre. Skjønner. Beklager ubrukelig innspill.

**Comment by steinho** [comment]
@bugdriven : Vi får vurdere om dette er ordinær category - eller om vi trenger en HorizonScan.Category ish....
Kanskje greit å ha dem adskilt - da det kommer fra annet enn full vurdering

**Comment by bugdriven** [comment]
Har jeg forstått riktig om NR har to underkategorier?
I så fall: hvordan skal disse brukes senere, i fremmedartslista?

**Comment by AneMarlene** [comment]
@bugdriven NR har flere underkategorier totalt sett, men fra horisontskanningen kan man bare komme til to av disse: ikke etablering innen 50 år (markert med nr "1." i skjermbilde 1 under), samt en helt ny underkategori som vi kaller "potensiell dørstokkart uten effekt". 

Med det samme vi snakker om underkategoriene til NR, så tar jeg med andre fra 2018 (skjermbilde nr 1), samt de man kan ende opp i under "Artens status" når man har begynt på full risikovurdering (vises med rød skrift på skjermbilde nr 2 og 3). Disse henger delvis sammen.

Følgende punkter referer til punktene i skjermbilde nr 1: 
1. Denne har vi fortsatt. En art kan kun havne i denne underkategorien gjennom horisontskanningen (ved kombinasjoner som vist over i dette issuet)
2. Denne har vi fortsatt. En art kan kun havne i denne kategorien gjennom fanen Artens status (se skjermbilde nr 2 for svar som gir dette)
3. Denne utgår - disse artene blir enten risikovurdert fordi de reproduserer selvstendig utendørs på dette tidspunktet, eller de havner i en av de andre NR-kategoriene
4. Denne blir splittet i to. En art kan kun havne i en av de to nye kategoriene gjennom fanen Artens status (se skjermbilde nr 2 for svar som gir dette). Under migrering av 2018-dataen tilsvarer gammel underkategori at spørsmål 1 på Artens status er forhåndsutfyllt med "Nei". Spm nr 7 på Artens status kan altså ikke forhåndsfylles under migrering. 
5. Denne har vi fortsatt. En art kan kun havne i denne kategorien gjennom fanen Artens status (se skjermbilde nr 2 for svar som gir dette)
6. Denne har vi splittet i to. En art kan kun havne i en av de to nye kategoriene gjennom fanen Artens status (se skjermbilde nr 3 for svar som gir dette). Under migrering av 2018-dataen tilsvarer gammel underkategori at spørsmål 1 og 2 på Artens status er svart positivt (ja og true), men valgene man har under spm 2 kan ikke forhåndsfylles under migrering. 

Skjermbilde 1:
![image](https://user-images.githubusercontent.com/58254444/135456847-91ea0da8-ec4c-4559-b875-0d05fd1426f0.png)

Skjermbilde 2:
![image](https://user-images.githubusercontent.com/58254444/135460257-d8cf2a8e-3949-4718-a99f-c65484bfab7f.png)

skjermbilde 3:
![image](https://user-images.githubusercontent.com/58254444/135460420-619d6bb2-8ca8-49fa-9078-254f9f1a4cb6.png)

**Comment by steinho** [comment]
@AneMarlene - er det ting relatert til migrering fra 2018 her? Altså noe som jeg må prøve å få over fra 2018 vurderingene som mangler nå?

**Comment by AneMarlene** [comment]
@steinho Det er nok noen saker her som er relatert til migrering. Jeg skal prøve å få de ut i et eget issue.

**Comment by AneMarlene** [comment]
Her kommeteres listen i min kommentar fra 30. sept:

Punkt 1 er ikke relevant for migrering.
Punkt 2 er ikke helt riktig migrert. Eget issue opprettet. (#290)
Punkt 3 er et godt spm - hvordan migrerer vi disse tro? Kanskje rett inn som fremmed art innenfor avgrensninga..Jeg tror vi må lage egen liste over artene dette gjelder, ettersom de fleste her går gjennom HS. 
Punkt 4 virker å være riktig migrert. 

To be continued...

**Comment by steinho** [comment]
@AneMarlene - lukker denne foreløpig
