### ISSUE TITLE
Synonymer Limniske invertebrater

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#240]
Ved klarsignal skal følgende endringer gjøres:

Haitia acuta skal flyttes til risikovurdering (ikke dørstokkart, skal risikovurderes)

Dikerogammarus tigrinus skal ut (synonym med Gammarus tigrinis, som risikovurderes i jan)

Chaetogammarus ischnus synonym m Echinogammarus ischnus - en av disse skal ut, venter på beskjed om hvilket navn)
Chaetogammarus warpachowskyi synonym m Echinogammarus warpachowskyi - en av disse skal ut, venter på beskjed om hvilket navn)

En krabbe (venter på navn) skal over på nytt gyldig navn

**Comment by sindrely** [comment]
Dikerogammarus tigrinus er sletta

**Comment by sindrely** [comment]
Haitia acuta er fiksa

**Comment by AneMarlene** [comment]
Chaetogammarus ischnus og Chaetogammarus warpachowskyi  er sletta. Alles godt.
