### ISSUE TITLE
Naturtypefane: presentasjon av livsmedium data

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#241]
- [x] Slette overskrift rett ovenfor livsmedium
- [x] Legge til overskrift som per i dag er på toppen (Velg blant følgende livsmedium...)
- [x] Slette del av kode som er ikke nødvendig i de øverste nivåer (e.g. MS LI MS -> MS)
- [x] Gi navn på øverste nivå, ikke bare kode
- [ ] Bytte pil til å peke til side før det er valgt (nå peker det opp). Bare for å gjøre det likt i hele system.

![livsmedium presentasjon](https://user-images.githubusercontent.com/25793207/142598939-d12e6a63-6854-40fc-8b75-c64c54063826.png)

**Comment by svetlnaumova** [comment]
Er det sånn du ville ha pilene? Slik ble det etter en lang arbeidsdag 😸 
![image](https://user-images.githubusercontent.com/43623201/142650288-fb74407f-5236-41b4-9baa-ba7992587849.png)

**Comment by EveliinaP** [comment]
Jeg mener slik at på andre nivå er likt som i første. Altså før man har valgt peker pilen til høyre, etter valg ned (nå er det på neste nivå ned byttes etter valg opp. Skjermdump av hvordan jeg mener det skulle se ut men dette er ikke veldig viktig
 ![image](https://user-images.githubusercontent.com/25793207/142656983-d0de2f82-b94b-47db-9b52-bbf1dd78894e.png)
![image](https://user-images.githubusercontent.com/25793207/142657135-89614b89-50b5-4558-b479-cc3f7c6ffca9.png)

**Comment by svetlnaumova** [comment]
Tror jeg har fått det til, men nå lurer jeg på om jeg burde fjerne piler der hvor det ikke er undernivåer, slik at det ikke blir misvisende (som for MS-M7, MS-M8 og MS-M9 her). Har du noen sterke meninger om det? 
![image](https://user-images.githubusercontent.com/43623201/142828039-4809c1ae-57e1-4d15-a07d-460f5eabfe74.png)

**Comment by EveliinaP** [comment]
Det ser veldig fint nå! Og god forslag, pilene bør fjernes der det ikke er nivåer under. Takk!
