### ISSUE TITLE
Ny artsgruppe: Oomycota 

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#245]
Det er en del arter/slekter, som tidligere har vært klassifisert som sopper, som nå er flyttet til riket Chromista.

Vi må derfor opprette en ny artsgruppe: **Oomycota**
Klassen Oomycetes skal inn her, så hvis det er fort gjort å flytte en hel klasse er det fint, hvis ikke skal jeg få ordna en liste over aktuelle arter.

**Comment by sindrely** [comment]
Også slekta Phytopythium  skal flyttes hit

**Comment by steinho** [comment]
ble behandlet som kromister i annen issue
