### ISSUE TITLE
Videre spredning i naturen: verdi som ikke overføres fra fab3 

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#249]
Denne rubrikken er tom:
![bilde](https://user-images.githubusercontent.com/91675679/143592404-8fd122c0-a102-45f5-8490-6cfaa2efdeaf.png)

i fab3 ser det slik ut:
![bilde](https://user-images.githubusercontent.com/91675679/143593344-0bda88d9-8296-4292-9565-d21ea3e6b28b.png)

Den kategorien som i fab3 heter "til kommersiell bruk (f.eks. produksjonsarter)" skal i fab4 være "Øvrig utsetting av nytteart" under  "tilsiktet utsetting"

**Comment by svetlnaumova** [comment]
Hvilken art er det?

**Comment by sindrely** [comment]
Karuss
