### ISSUE TITLE
Artsinformasjon-fanen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#25]
Her kommer et utkast på artsinformasjonsfanen. Det er ikke store endringene fra slik den var i 2018 og slik ser ut i basen nå, men noen presiseringer og justeringer er det :) 
[FAB - Artsinformasjon.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6726184/FAB.-.Artsinformasjon.docx)

**Comment by svetlnaumova** [comment]
Denne fanen ser ok ut for min del, men var usikker angående tabeller for brakkvann - Helge mente at det skal være samme rullegardiner som for marint. Si gjerne ifra om det ikke stemmer, men foreløpig lukker jeg issuen siden resten av fanen stemmer overens med beskrivelsen i dokumentet :)
