### ISSUE TITLE
Naturtypefane: justering av tabell for valgte naturtyper

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#250]
Små justering for tabell. Valg av "regional naturvariasjon" fra beskrivelsessystem er ikke på plass ennå men vi kan vise hvor det skal være i slutt i tabell. 
[tabell for valgte naturytper.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7616552/tabell.for.valgte.naturytper.pptx)

**Comment by svetlnaumova** [comment]
Har lagt til navn på naturtyper, mens for truede/sjeldne naturtyper overføres det koden fra overordnet nivå (ikke den lange koden på undernivå) - er det ok eller skal det helst være tomt?

**Comment by EveliinaP** [comment]
Jeg tror at om vi ikke få til å vise hele koden riktig så viser vi ikke noe.
