### ISSUE TITLE
Manglende overføring  av data fra fab3 til fab4 Regionalt fremmed art

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#252]
Arter som er regionalt fremmede i fab3 har ikke fått riktig status i fab4.

![bilde](https://user-images.githubusercontent.com/91675679/143856086-e142bf63-f3b5-4776-84b5-d9f4a12a7379.png)

![bilde](https://user-images.githubusercontent.com/91675679/143856145-a951367d-5225-4587-9110-3c716ca0eee8.png)

Denne burde ha :
![bilde](https://user-images.githubusercontent.com/91675679/143856223-e0ccc878-585a-4f95-8c2b-c3e0bdce37b9.png)

**Comment by steinho** [comment]
@AneMarlene - ser den er blitt lagt til migreringsproblematikk #286. Men er den løst? Jeg tror det: 
![image](https://user-images.githubusercontent.com/3253353/150741897-9234893e-d66c-4dd7-b723-98818216d9b0.png)

**Comment by AneMarlene** [comment]
@steinho det tror jeg også. :) Jeg la den nok bare til så vi skulle være sikre på at den var løst på rett plass i koden :)
