### ISSUE TITLE
Manglende overføring av data fra fab3 til fab4 utbredelse i norge

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#254]
For regionalt fremmede arter overføres ikke data på nåværende og potensiell utbredelse fram fab3 til fab4

Fab3
![bilde](https://user-images.githubusercontent.com/91675679/143858037-64ad6fa3-d2d0-486d-b1d2-30484e603167.png)

Fab4
![bilde](https://user-images.githubusercontent.com/91675679/143858183-891c17e9-c7d5-4c14-8cc2-0957d67352c7.png)

Dette eksemplet er fra gjedde.

**Comment by svetlnaumova** [comment]
Den ser ut til å være fikset, så jeg lukker den.
