### ISSUE TITLE
Manglende overføring av data fra fab3 til fab4. Regionvis utbredelse

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#255]
Det virker som om regionvis utbredelse ikke overføres riktig fra fab3 til fab4. 

FAB3
![bilde](https://user-images.githubusercontent.com/91675679/143859672-812aa399-fb1f-4215-8661-8f590470f274.png)

FAB4
![bilde](https://user-images.githubusercontent.com/91675679/143859763-cda6ffa7-23d6-49ef-b0a5-aefe68c63ad3.png)

Eksempel fra Gjedde.

**Comment by steinho** [comment]
@sindrely - har kjørt en patch mot test serveren - kan dere ta noen stikkprøver.

@olsoybakk - kan du sjekke commit - og om logikken ser riktig ut? Ser ut som de forrige verdiene lå lagret i kommaseparerte strenger

**Comment by sindrely** [comment]
![bilde](https://user-images.githubusercontent.com/91675679/145354542-f2c8c6c9-8fb3-40a4-be36-07feac1d5fdd.png)
![bilde](https://user-images.githubusercontent.com/91675679/145354593-642ef103-7b74-4db3-9daf-87d416526191.png)

**og**

![bilde](https://user-images.githubusercontent.com/91675679/145355172-fc9b5067-c71a-4244-99a2-ca2ead475635.png)
![bilde](https://user-images.githubusercontent.com/91675679/145355217-429c3173-a16d-48e4-8207-aeef35fa815f.png)

"Kjent i dag" ser riktig ut, men "Antatt om 50" ser ikke ut til å være helt riktig.

**Comment by steinho** [comment]
@sindrely 
Kan sjekke denne på nytt nå...

**Comment by sindrely** [comment]
Ser bra ut
