### ISSUE TITLE
Migrering fra FAB3 -  selvstendig reproduserende fremmed art

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#258]
Arter med følgende utfylling i FAB3: 
![image](https://user-images.githubusercontent.com/58254444/143864453-6eac51d0-7956-4600-a2eb-481eca285530.png)

SKal ha følgende utfylling på artens status i FAB4 (merk: her er det 3 ulike spørsmål som besvares med bakgrunn i den ene fra 2018): 
![image](https://user-images.githubusercontent.com/58254444/143865905-90115c58-e49b-47a8-b5ad-47ef6df68ba1.png)

![image](https://user-images.githubusercontent.com/58254444/143866066-a6b1c009-664b-45ba-9ddc-a0442f30cd1e.png)

![image](https://user-images.githubusercontent.com/58254444/143866304-7d008fa2-45ae-4968-ba68-7c291ebf48d3.png)

Eksempelarter: Karplanten Erigeron annuus,

**Comment by AneMarlene** [comment]
@svetlnaumova - bare for å spørre, når du lukker disse, betyr det at dette rettes i drift også? Til den verdien artene hadde i 2018?

**Comment by AneMarlene** [comment]
@svetlnaumova (enda en kommentar). Nå legger jeg merke til at denne endringen overstyr endringer man gjør når man lagrer. Jeg var inne på karplanten Abies sachalinensis, sakhalinedelgran, og endret spørsmålet "Er taxonet inkludert i vurderingen av et annet taxon?" fra "nei" til "ja".  Så lagret jeg, fikk "Lagring, OK", gikk ut av arten, oppdaterte FAB, og gikk inn igjen. Da var min endring slettet og spørsmålet sto igjen med "nei" som svar. Mulig dette gjelder flere av de lignende issuene? 

Disse utfyllingene skal kun gjelde inntil eksperten ev. gjør endringer på spørsmålet og lagrer endringene.  Og det er viktigst at denne informasjonsflyten fra 2018 blir riktig i drift.

**Comment by svetlnaumova** [comment]
> @svetlnaumova - bare for å spørre, når du lukker disse, betyr det at dette rettes i drift også? Til den verdien artene hadde i 2018?

Ingenting rettes opp automatisk i drift, vi må dytte det ut når vi er sikre på at det ikke er noe farlig i test.

**Comment by svetlnaumova** [comment]
> @svetlnaumova (enda en kommentar). Nå legger jeg merke til at denne endringen overstyr endringer man gjør når man lagrer. Jeg var inne på karplanten Abies sachalinensis, sakhalinedelgran, og endret spørsmålet "Er taxonet inkludert i vurderingen av et annet taxon?" fra "nei" til "ja". Så lagret jeg, fikk "Lagring, OK", gikk ut av arten, oppdaterte FAB, og gikk inn igjen. Da var min endring slettet og spørsmålet sto igjen med "nei" som svar. Mulig dette gjelder flere av de lignende issuene?
> 
> Disse utfyllingene skal kun gjelde inntil eksperten ev. gjør endringer på spørsmålet og lagrer endringene. Og det er viktigst at denne informasjonsflyten fra 2018 blir riktig i drift.

Beklager veldig sent svar, men nå har jeg testet og det ser ut som endringene som man har gjort ikke blir overstyrt ved refreshing. Kunne du dobbeltsjekket at det ikke er flere feil?

**Comment by AneMarlene** [comment]
Dette er muligens et nytt issue(?), men basen glemmer avhaking på dette nivået etter en refresh: 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/58254444/146328726-9372eb3e-f397-496a-bf3b-79b07db42744.png">

Tekstfeltene under lagres (selv om de ikke synes etter lagring og refreshing):
![image](https://user-images.githubusercontent.com/58254444/146328869-1a6d8db6-75cc-4bd2-8f15-d924eb1d8a18.png)

**Comment by svetlnaumova** [comment]
> Dette er muligens et nytt issue(?), men basen glemmer avhaking på dette nivået etter en refresh:
> 
> <img alt="image" width="484" src="https://user-images.githubusercontent.com/58254444/146328726-9372eb3e-f397-496a-bf3b-79b07db42744.png">
> 
> Tekstfeltene under lagres (selv om de ikke synes etter lagring og refreshing): ![image](https://user-images.githubusercontent.com/58254444/146328869-1a6d8db6-75cc-4bd2-8f15-d924eb1d8a18.png)

Da er det fikset. Er det noe mer knyttet til dette issuet som gjenstår?

**Comment by AneMarlene** [comment]
@svetlnaumova @steinho Jeg trodde jeg hadde svart på dette spm i går, men jeg trykket tydeligvis ikke på "Comment". :D Det jeg lurte på var relatert til kommentaren min den 1. desember i denne tråden. Er det sånn at migrerings-issuene kan rettes via testbasen (uten at jeg vet om jeg uttrykker meg helt riktig)? Jeg trodde i utgangspunktet at jobben måtte gjøres direkte mot drift siden artene allerede lå der?

For å svare på det siste spm ditt, Svetlana, så ser det ut til at basen nå lagrer avhakningen på de to radioknappene, men ikke helt rett på Abies alba av en eller annen grunn (se issue #321 )

**Comment by bugdriven** [comment]
Lukker denne
