### ISSUE TITLE
Migrering fra FAB3 - dørstokkart, artens status

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#262]
Alle dørstokkarter med følgende avhakning i fab3: 
![image](https://user-images.githubusercontent.com/58254444/143926519-2d213731-f3f0-4506-b418-576a7c73ac9c.png)

skal ha følgende på artens status: 
![image](https://user-images.githubusercontent.com/58254444/143926823-e05b2a12-efc0-4803-b50b-2e1ec9fd4549.png)

I drift ligger de inne med "nei" på dette spm. Dette virker å gjelde alle arter som er migrert fra fab3. I hvertfall arter som omfattes av de andre issuene som er opprettet så langt på migrering. 

Så lenge de i fab3 var oppført med dørstokkart som risikovurderes (som på skjermbilde øverst her), skal det også fylles ut slik: 
![image](https://user-images.githubusercontent.com/58254444/143927297-8df1409c-bd81-4cd2-a357-e6b0a532e820.png)

Eksempelart: fuglen aix sponsa

**Comment by svetlnaumova** [comment]
@AneMarlene er denne fikset? Har gått inn på noen vurderinger av dørstokkarter, og der ser det greit ut.

**Comment by AneMarlene** [comment]
Sender denne sjekken videre til @sindrely. Sindre, du kan lukke denne om den virker å være ok.

**Comment by sindrely** [comment]
Testa på 10 arter fra forskjellige artsgrupper, og alle var OK.
