### ISSUE TITLE
Økologisk effekt - hente naturtyper valgt under fanen naturtyper

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#265]
Under D- og E-kriteriet: Effekter på rødlistevurderte arter, på fanen økologisk effekt, er det mulig å legge til effekter på arter via å legge til en hel naturtype. Da må naturtypen først være lagt til i tabellen under fanen naturtyper, og så vil disse naturtypene dukke opp i en rullegardin her: 

![image](https://user-images.githubusercontent.com/58254444/144234151-f9a7ab27-1237-4a1c-83d1-da32ad044ec7.png)

Det er altså naturtypene som ligger i denne tabellen som skal bli tilgjengelig i rullegardinen over: 
![image](https://user-images.githubusercontent.com/58254444/144234616-5aedbac0-09fc-48dd-9d34-42cf5756f4e4.png)

**Comment by svetlnaumova** [comment]
@AneMarlene @EveliinaP det er mulig å legge til naturtyper nå, men dere ønsker kanskje også at de naturtypene som allerede er lagt til i tabellen ikke skal være tilgjengelige i rullegardinmenyen?
