### ISSUE TITLE
Migrering fra FAB3 til FAB4 Nåværende og potensiell utbredelse

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#269]
Mørketall overføres ikke fra fab3 til fab4

**FAB3**
![bilde](https://user-images.githubusercontent.com/91675679/144429677-6e460b4b-86c8-4d0c-8b96-473f4465f34c.png)

**FAB4**
![bilde](https://user-images.githubusercontent.com/91675679/144431091-852654a0-c6c3-433c-a75c-1155e56b1cb3.png)

Estimert skal stå på antatt forekomstareal, kjent på kjent, og mørketall på mørketall.

**Comment by steinho** [comment]
@bugdriven: i gui viser vi nå det konverterte feltet aooknown - som kjent - feltet pekte på aoo2. Du må nesten se over hva som er forventet - men om aoo2 erstatter known - må vi lage noe logikk for å overføre known

**Comment by sindrely** [comment]
Nå er feltene for Antatt Beste anslag (AOOtotalBest) og Mørketall AOOdarkfigureBest låst.

**Comment by bugdriven** [comment]
fixed
