### ISSUE TITLE
Oppsummeringsfanen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#27]
Da har vi omsider en utgave av oppsummeringsfanen. Noen småendringer er gjort, samt noe helt nytt for fremmedartsbasen, men disse elementene finnes det lignende versjoner av i rødlistebasen. 
[FAB - Oppsummering_commHH_AMM.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6741202/FAB.-.Oppsummering_commHH_AMM.docx)

**Comment by AneMarlene** [comment]
HEi :) Har fått tilbakemelding på ønske om å bytte plass på to av årsakene til endring: 
![image](https://user-images.githubusercontent.com/58254444/124712603-d23a6080-deff-11eb-8773-9c08aacf9031.png)

I tillegg kan det hende at den siste kategorien (endret status) vil bli splittet opp i flere, men det kommer jeg tilbake til etter sommmerferien.

**Comment by svetlnaumova** [comment]
Lukker denne issuen fordi alle feltene er nå på plass - mulig at de ikke ser ut akkurat som dere har tenkt, men det kan vi komme tilbake til. Trenger kanskje litt oppklaring på hva nøyaktig "Vis oppsummering"-knappen skal gjøre, samt legge til muligheten for å laste opp filer - oppretter egne issuer på det.
