### ISSUE TITLE
Migrering fra FAB3 til FAB4 Utbredelseshistorikk

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#270]
Utbredelseshistorikken fra fab3 

![bilde](https://user-images.githubusercontent.com/91675679/144443859-b51609d2-9b53-415d-935d-c1dbf0b7578f.png)

overføres ikke til fab4
![bilde](https://user-images.githubusercontent.com/91675679/144443924-08822c2e-6215-434d-ba18-314be88c0af2.png)

**Comment by steinho** [comment]
@sindrely - Hei - har nå funnet årsaken til dette - gjelder ett sett med felt - må patche inn data fra 2018 vurderingene. Årsaken er litt teknisk men feltene er uheldigvis blitt etablert som fields og ikke properties på datamodellen - og er dermed ikke med i konvertering til og fra Json... Skal prøve å få oversikt over om det er flere enn de som er påpekt i github issuene
