### ISSUE TITLE
Rødlista for naturtyper - felt som må bli med inn i FAB fra excelark

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#272]
@steinho Fra fila TrueteOgSjeldneNaturtyper2018 (ligger her: https://github.com/Artsdatabanken/Fremmedartsbase2023/tree/main/SwissKnife/Importfiler) trenger vi også denne kolonnen for alle naturtypene: "Totalareal, beregnet"

Den skal vises i følgende felt inne på naturtypefanen for alle naturtyper fra rødlista: 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/58254444/144602714-fa628da6-8cdd-44aa-abee-e429a2d6d830.png">

@svetlnaumova, om ingen naturtyper fra rødlista er valgt, kan kolonnen "naturtypeareal" være skjult (om det er en enkel sak å fikse).

**Comment by svetlnaumova** [comment]
@AneMarlene naturtypeareal er skjult nå (ser at den ikke kommer opp selv om jeg legger til en rødlistet naturtype, men det kan jeg fikse).

**Comment by steinho** [comment]
La inn areal for naturtypene - slik at de er tilgjengelig for å overføre til listen... https://github.com/Artsdatabanken/Fremmedartsbase2023/commit/9451287920955ac4d93d75ae9c398091a3bee2e5
