### ISSUE TITLE
Risikovurdering - Beregning av skår og kategori

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#274]
Foreløpig fungerer det ikke på noen kriterier å påvirke skåren. Dette fungerte tidligere delvis, så når dette er oppe og går er det lurt å se på issue #101  

Eksempel:
![image](https://user-images.githubusercontent.com/58254444/144617937-be70b74a-736d-4e4b-8dde-2fbba5356cf9.png)

**Comment by bugdriven** [comment]
fixed

**Comment by sindrely** [comment]
Denne på A-kriteriet går ikke ann å justere:

![bilde](https://user-images.githubusercontent.com/91675679/145191267-40f9988a-5e2d-449b-8e52-d01831ba0194.png)

**Comment by bugdriven** [comment]
Jeg har gjort en god del på dette nå. 
Kriterie A, B, D, H og I, er klare for testing.

**Comment by bugdriven** [comment]
Det konkrete eksemplet skal være fikset nå. Lukker denne siden den er for generell. 
Opprett ny issue pr kriterie, evt for feil som er felles for flere navngitte kriterier.
