### ISSUE TITLE
Artens status - muligens liten mangel

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#28]
På artens status, hvis man velger "JA" på spørsmålet om arten er fremmed, dukker det ikke opp en avkrysningsboks for om arten er regionalt fremmed. Det KAN være riktig om alle artene nå kodes som "dørstokkart", men ikke riktig om dette valget er bort for alle arter, og det ikke er slik at alt midlertidig kodes som dørstokkarter på baksiden. 

![image](https://user-images.githubusercontent.com/58254444/124443141-b7d87980-dd7d-11eb-82e5-18e5053110d0.png)

Her skal det egentlig dukke opp en boks (hvis ikke dørstokkart):

![image](https://user-images.githubusercontent.com/58254444/124443550-0f76e500-dd7e-11eb-8b4c-fe1edd610fe1.png)

**Comment by svetlnaumova** [comment]
Kan det være at du tester en dørstokkart nå? For den boksen dukker opp f.eks. her: 
![image](https://user-images.githubusercontent.com/43623201/124444261-b491bd80-dd7e-11eb-8f75-52f236141c64.png)

**Comment by AneMarlene** [comment]
Ja, ok. Da er det bare å lukke denne. Jeg er på testarter skjønner du, men den kan jo så klart være dørstokkart. ;)
