### ISSUE TITLE
Samle issues knytt til migreringsproblematikk

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/Fremmedartsbase2023#286]
Liste opp issues der det er restanser knytt til migrering

- [x] #24
- [x] #269
- [x] #262
- [x] #289 
- [x] #290
- [x] #294 
- [x] #296
- [x] #254
- [x] #261
- [x] #258 
- [x] #325 
- [x] #346 
- [x] #260 
- [x] #23 
- [x] #253 
- [x] #268 
- [x] #270 
- [x] #252 
- [x] #259 
- [x] #358
- [x] #436
- [x] #444

(prøve å liste opp enkeltissues som potensielt har med migrering å gjøre - typisk har disse oppstatt fordi det er endringer i metode/parameternavn som brukes o.l.)

**Comment by sindrely** [comment]
#254 
#261 
Disse to også?

**Comment by steinho** [comment]
> #254 #261 Disse to også?

Tok dem opp i lista ja

**Comment by steinho** [comment]
@AneMarlene og @olgahil - jeg mener alle disse er i boks nå - lukker dermed denne. Om det dukker opp ny migreringsproblematikk - lager vi en ny sak
