### ISSUE TITLE
Endre datatype for bool-verdier

### ISSUE THREAD

**Issue by bugdriven** [Artsdatabanken/Fremmedartsbase2023#287]
Det er behov for endring av datatype for følgende properties:
IsAlienSpecies
AlienSpecieUncertainIfEstablishedBefore1800
ConnectedToAnother
IsRegionallyAlien
ProductionSpecies

Kan endres til nullable<bool>

**Comment by steinho** [comment]
Da er disse bool? i modellen server side .... justerte IsRegionallyAlien til å ha en Get Setter i frontend fra yes til true osv....
