### ISSUE TITLE
Utbredelse - posentandel i sterkt endra natur. 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#289]
Tallverdier fra denne cella i FAB3:

![image](https://user-images.githubusercontent.com/58254444/144844835-c7349f1e-6e76-42de-93f6-7a47d31f03d1.png)

Skal overføres til dette feltet: 
![image](https://user-images.githubusercontent.com/58254444/144844921-949bcbac-6210-4a91-bc7d-05570f192881.png)

Overføringstabell:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/AMY/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/AMY/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/AMY/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NO-BOK style='tab-interval:35.4pt;word-wrap:break-word'>

FAB3 name="SpreadHistoryDomesticAreaInStronglyChangedNatureTypes" | FAB4   name="spreadAreaInChangedNature"
-- | --
Verdier fra og med 0 til og med   4, eller 0:4 i R-språk | < 5 %
5:24 | f.o.m. 5 til 25 %
25:75 | f.o.m. 25 % t.o.m.   75 %
76:95 | fra 75 % t.o.m. 95   %
96:100 | > 95 %

</body>

</html>

**Comment by svetlnaumova** [comment]
@AneMarlene kan du gi et eksempel på en art der denne ikke er null i FAB3?

**Comment by AneMarlene** [comment]
Eksempelarter: Amfibier reptiler: Pelophylax lessonae lessonae (andel = 95) - riktig overført i FAB4 nå :) 
Alger: Bonnemaisonia hamifera (andel = 10) - riktig overført nå
Karplanter: Epimedium alpinum (andel = 25) - IKKE riktig overført. Den har havnet i denne: 
![image](https://user-images.githubusercontent.com/58254444/145174838-aec5cef1-8b5e-491d-9150-886f9964a67a.png), men skal havne i denne: <html>
<body>


f.o.m. 25 % t.o.m. 75 %
--


<br class="Apple-interchange-newline">
</body>
</html>
