### ISSUE TITLE
Overføring av tekstfelter fra FAB3 Artens status til FAB4

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#294]
I FAB3 under Artens status og etter at radioknappen: "Art som faller utenfor definisjonen eller avgrensningen" er huket av dukker det opp radioknapper (a-f), ved avhuking på disse dukker det opp **tekstfelter**. Disse tekstfeltene må overføres til FAB4.

Eksempel, her med edelgran. Dette tekstfeltet blir ikke overført til FAB4:

![bilde](https://user-images.githubusercontent.com/91675679/145198981-12045cb4-523a-4fc9-9625-8da354278dc9.png)

**Avhuket knap i FAB3**    ->   **Overført til felt i FAB4**
(a) arten er ikke fremmed   -> overføres til tekstfeltet som dukker opp når man velger "Nei" under artens status i dag

![bilde](https://user-images.githubusercontent.com/91675679/145196869-348e394e-331b-4c1c-a7fd-f7efb2c05884.png)

**Avhuket knap i FAB3** -> **Overført til felt i FAB4**
(b) arten har vært etablert med en fast reproduserende bestand i Norge per 1800 -> tekstfeltet under "Var arten etablert per 1800?"
![bilde](https://user-images.githubusercontent.com/91675679/145197280-39949adb-3c6c-4955-82fe-bb16a82a3507.png)

**Avhuket knap i FAB3** -> **Overført til felt i FAB4**
(c) arten er en tradisjonell produksjonsart -> Her trenger vi ett nytt tekstfelt å overføre til. Dette kan ligge under "Er arten en bruksart?"
![bilde](https://user-images.githubusercontent.com/91675679/145197982-bd37f1d0-2c07-4b31-850e-633a26298e0c.png)

**Avhuket knap i FAB3** -> **Overført til felt i FAB4**
(d) arten kommer sannsynligvis ikke til etablere seg i Norge i løpet av 50 år -> Dette tekstfeltet skal ikke overføres til FAB4

**Avhuket knap i FAB3** -> **Overført til felt i FAB4**
(e) taxonet er rangert under artsnivået og deler «moderartens» status -> til ett nytt tekstfelt som dukker opp når det er huket av "ja" under Er taxonet inkludert i vurderingen av et annet taxon?
![bilde](https://user-images.githubusercontent.com/91675679/145198696-e583156f-7546-4d55-820b-c8f83efa330e.png)

**Avhuket knap i FAB3** -> **Overført til felt i FAB4**
(f) arten finnes ikke i Norge (tidligere feilangitt eller feilbestemt) -> Denne kommer vi tilbake til.

**Comment by svetlnaumova** [comment]
Spørsmål angående (c) og (e): trenger vi et tekstfelt bare hvis det er noe info å overføre fra FAB3 eller skal det stå et tomt felt selv om det ikke har vært noe fylt ut fra før av?

**Comment by sindrely** [comment]
Det var ett bra spørsmål. Du får svar på mandag, når Ane og Olga er tilgjengelig igjenn.
