### ISSUE TITLE
Naturtypefane: livsmedium valg og tabell

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#295]
Når man velge livsmedium kommer det opp tabell med flere valg (se første bilde)
- [x] "Kolonisert areal %" og "Vurderingsgrunnlag" valg skal slettes
Det skal være Art/takson valg i stedet, lignende enn i "Risikovurdering" fane der man kan søke artsnavn fra navnebase.  
- [x] Pri 1.  Her skulle det være mulig å søke med artsnavn (basert på navnebase) og da er overskrift "Art"

- [x] Informasjon om livsmedium art skal overføres med inn i tabellet der det tidligere stå "Vert(er)". Overskift byttes til "Art" eller "Takson" avhengig av hvilke metode vi rekker å implementere.
![Lysbilde2](https://user-images.githubusercontent.com/25793207/145203247-aa316c34-983d-43db-9ec9-74c5eeb0772c.PNG)

**Comment by EveliinaP** [comment]
Her mangler det fortsatt mulighet å søke for arter (eller taksoner). Dette bør være likt enn for D og E kriterier (med mulighet å søke alle arter, ikke bare rødliste). Få du gjort dette @svetlnaumova eller bør du få hjelp fra Stein? Hvis ja, så kanskje du kan assign han i saken?

**Comment by svetlnaumova** [comment]
@EveliinaP denne ser ut til å være stort sett ferdig bortsett fra muligheten for å søke på øvre taksonomiske nivå. Er det greit å lukke denne og så åpne en ny issue som gjelder forbedring av søket?

**Comment by EveliinaP** [comment]
Jeg ser at det er nå mulig å finne og legge til arter. Stort sett fungerer det også for norsk navn... men ikke når jeg prøvde å søke "ulv". Er det mulig at det er flere arter som ikke kommer opp i søket og hva som kunne vært grunn til det?

**Comment by EveliinaP** [comment]
Jeg kan legge til ny issue på takson søk

**Comment by svetlnaumova** [comment]
> Jeg ser at det er nå mulig å finne og legge til arter. Stort sett fungerer det også for norsk navn... men ikke når jeg prøvde å søke "ulv". Er det mulig at det er flere arter som ikke kommer opp i søket og hva som kunne vært grunn til det?

Jeg tror at søket ikke returnerer noe før søkestrengen er lang nok - hvis du taster inn f.eks. "gaupe", så får du opp resultat. Tror at det er gjort slik at man ikke får en alt for lang liste over treff med en gang man begynner å søke.

**Comment by EveliinaP** [comment]
Det høres ok ut! Det må nok være slik og de som vil legge til arter som har kort navn må bare finne latinsk navn da

**Comment by svetlnaumova** [comment]
> Det høres ok ut! Det må nok være slik og de som vil legge til arter som har kort navn må bare finne latinsk navn da

Ja, det er kanskje lurt å få med i veilederen, slik at de ikke blir forvirret?
