### ISSUE TITLE
Artens status - utfylling for arter som flyttes fra HS til risikovurdering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#297]
I driftbasen har jeg flyttet en del arter fra horisontskanning og over til risikovurdering (fordi de er selvstendig reproduserende). 

Jeg gikk nå inn på Artens status på en slik art (husspissmus, pattedyr), og den har da forhåndsutfylt følgende svar på første spm: 
![image](https://user-images.githubusercontent.com/58254444/145204830-bb617dbc-8e00-45af-96a8-b4d39cd3afd8.png)

Alle arter som flyttes fra Horisontskanning til risikovurdering skal ha følgende forhåndsutfylt på fanen artens status: 
1. er arten fremmed - JA
2. Er taxonet inkludert i vurderingen av et annet taxon? - NEI
3. **Bruksartspm kan ikke besvares.**
4. Hvilken etableringsklasse har arten i Norge? - Arten er selvstendig reproduserende (utendørs) (C2)
5. Var arten etablert per 1800? NEI

**Comment by steinho** [comment]
Dette må håndteres i api metoden:
assessmentController:
        [HttpGet("{id}/movehorizon/{doorknockerstate}")]
        public async Task<IActionResult> MoveHorizon(int id, string doorknockerstate)
Denne som modifiserer vurderingen når den flyttes mellom hor og full

**Comment by svetlnaumova** [comment]
Det ser ut til å fungere nå, men jeg er usikker på hvordan å håndtere bruksartspørsmålet - det skal uansett være enten true eller false siden det er en bool?

**Comment by svetlnaumova** [comment]
@AneMarlene nå som det med bruksartspørsmålet ble avklart, kan vi si at denne er fikset eller er det fortsatt noe som ikke fungerer som det skal?

**Comment by AneMarlene** [comment]
@svetlnaumova om det ikke er en grunn til at noe separat må gjøres i drift (på de som allerede er overført), så kan denne lukkes ja. Jeg tenker at vi kanskje kan leve med at de artene som allerede er flyttet i drift har feil utfylling, men om det er enkelt å fikse, så er det selvsagt fint om det gjøres :)
