### ISSUE TITLE
Feil variabelnavn under B-kriteriet. Selvstendig reproduserende arter. OG mulig feil i beregnet ekspansjonshastighet

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#298]
1.
**Variablen t0, som blir overført fra forekomstareal under Utbredelse i Norge**
![bilde](https://user-images.githubusercontent.com/91675679/145266171-fe042b20-4e19-44c9-840e-905d081cd537.png)

**til B-kriteriet**

![bilde](https://user-images.githubusercontent.com/91675679/145266113-12171375-4d8d-4cc2-85ab-d135aaf6b172.png)

**ser ut til å bli overført riktig, men den ser ut til å ha feil navn.**

![bilde](https://user-images.githubusercontent.com/91675679/145261447-aad5340d-3a48-4b35-ac6e-0579e0f97ea7.png)

**Her heter den AOOyear1, som er navnet t1 skal ha.**

![bilde](https://user-images.githubusercontent.com/91675679/145262641-0e2345ba-ce91-4104-9640-f3e17e7ff21b.png)

**Jeg tror at det er grunnen til at verdiene i tekst under tekstboksen får feil verdi.**

![bilde](https://user-images.githubusercontent.com/91675679/145266624-bdedaf99-5649-4f41-81db-6c3d184b2264.png)
**og**

![bilde](https://user-images.githubusercontent.com/91675679/145265132-2efc3c0c-7379-4a46-8ab0-e469a1c690b8.png)

2.
**Derfor tror jeg også at ekspansjonshastighet må blir feil når man bruker metoden "Anslått økning i forekomstareal" .**
**Jeg er ikke spesielt flink til å navigere i koden, men det ser jo ut som om ekspansjonshastighet må bli feil hvis feil verdi for AOOyear1 og AOOyear2 brukes.** 

![bilde](https://user-images.githubusercontent.com/91675679/145264447-12cef9bc-168f-499d-8cac-cb7e955c7caf.png)

**Comment by bugdriven** [comment]
Jeg har prøvd å fikse denne (og relaterte feil)
Regner med at du mente at (r.AOOyear2 - r.AOOyear1) blir feil pga at disse var knyttet til feil felt i GUI.
Test og se om du får forventet resultat nå. (jeg følte jeg måtte trø til med store tall her for å få utslag på kriteriet)

**Comment by sindrely** [comment]
Jeg tror vi må ta en runde med Hanno på denne utregninga. Du har rett  i at man må trø til med veldig høye verdier for å få utslag på kriteriet, jeg skal gjøre litt tester og kontakte han i dag.

**Comment by bugdriven** [comment]
Denne skal være i orden nå.
