### ISSUE TITLE
Klimaeffekter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#30]
Her kommer et utkast på fanen klimaeffekter. Muligens blir det litt småjusteringer, men forhåpentligvis ikke store. 

[FAB - klimaeffekter _github.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6770388/FAB.-.klimaeffekter._github.pptx)

**Comment by svetlnaumova** [comment]
Lukker denne også da logikken er på plass. Overføring av usikkerheten og gjeldende kriterier kan vi ta når alle faner med kriterier fungerer som de skal.
