### ISSUE TITLE
Lagringsfeil - Endringer på vurderingen uten å ha endret

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#301]
Når jeg er inne på en art uten å gjøre endringer (f.eks. en art med lesetilgang) på horisontskanning, så får jeg beskjed om at jeg har ulagrede endringer når jeg forsøker å gå ut av arten igjen. I følge JSON er dette grunnen: 

![image](https://user-images.githubusercontent.com/58254444/145957784-61b6fc7b-9962-4a4a-b1a3-e492b616ed9a.png)

Virker dermed å være relatert til migreringen/endringen i "andel i sterkt endra natur"?

**Comment by svetlnaumova** [comment]
Ja, fordi at verdien endres automatisk (hvis det var 10 i FAB3 som i ditt eksempel, endres det til 5 som tilsvarer intervallet fra 5 til 25. Usikker på om det er en bra løsning, men kanskje det burde lagres automatisk med den gang, slik at brukere ikke blir spurt om dette.

**Comment by AneMarlene** [comment]
@svetlnaumova nå får jeg bare feilen på horisontskanninga..? Kun for arter som var med i 2018 ja, ser det ut til.

**Comment by AneMarlene** [comment]
..og feilen kommer ikke når det er null i 2018: 
![image](https://user-images.githubusercontent.com/58254444/145959237-93424d1f-6e03-46bd-a95b-c7dc008a7808.png)

Da kan jeg gå ut av arten uten å få noen beskjed.

**Comment by AneMarlene** [comment]
...hehe, finner flere saker som kan spille inn her: Hvorfor er denne satt til false i 2018? Den fantes vel ikke i 2018?

![image](https://user-images.githubusercontent.com/58254444/145959678-8fe62f7b-d5c9-40a9-b456-d3a014bd7019.png)

**Comment by svetlnaumova** [comment]
Hvis den ikke fantes, så gir det egentlig mening at det er false - en boolean kan være enten true eller false, så hvis den ikke er true i utgangspunktet, så må den være false (håper det var forståelig)...

**Comment by AneMarlene** [comment]
Ja ser den. ...men samtidig skal den antagelig være "true" nå?. Det rare er at det varierer. Den forrige var en karplante, her er en sopp fra horisontskanninga: 
![image](https://user-images.githubusercontent.com/58254444/145960486-8f00eff5-122d-4237-bb34-d454f21849ea.png)

**Comment by steinho** [comment]
> ...hehe, finner flere saker som kan spille inn her: Hvorfor er denne satt til false i 2018? Den fantes vel ikke i 2018?
> 
> ![image](https://user-images.githubusercontent.com/58254444/145959678-8fe62f7b-d5c9-40a9-b456-d3a014bd7019.png)

Dette er en bool - som nå er på vurderingsobsjektet i den nye databasen. En bool må ha en verdi - true eller false. Stemmer at den ikke hadde noen verdi i 2018 - men default verdien er false.... så alle slike får en verdi uavhengig av om de eksisterte eller ikke.

Men blir den endret under åpning av vurderingen? Det er litt crazy i så fall

**Comment by AneMarlene** [comment]
> > ...hehe, finner flere saker som kan spille inn her: Hvorfor er denne satt til false i 2018? Den fantes vel ikke i 2018?
> > ![image](https://user-images.githubusercontent.com/58254444/145959678-8fe62f7b-d5c9-40a9-b456-d3a014bd7019.png)
> 
> Dette er en bool - som nå er på vurderingsobsjektet i den nye databasen. En bool må ha en verdi - true eller false. Stemmer at den ikke hadde noen verdi i 2018 - men default verdien er false.... så alle slike får en verdi uavhengig av om de eksisterte eller ikke.
> 
> Men blir den endret under åpning av vurderingen? Det er litt crazy i så fall

Skjønner ikke helt. Karplanten Acalypha brachystachya, kobberblad har denne endringen (vurderes av Olga), men andre som det er startet vurdering på har ikke en slik endring. Jeg skal få testa litt mer systematisk.

**Comment by steinho** [comment]
Ser denne er ok nå - tror noen av disse problemene er fikset - men kan dukke opp nye
