### ISSUE TITLE
Blackburn-kategorier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#302]
En siste endring på formulerling (artens status og utbredelsesfanen): 

•	Etter introduksjon har arten selv spredd seg til minst ti forekomster der den er etablert (E)
•	Etter introduksjon har arten selv spredd seg til minst én forekomst der den er etablert (D2)
•	Etter introduksjon har arten selv spredd seg, men er kun etablert der den er introdusert (D1)
•	Arten forekommer kun der den er introdusert og er etablert der (C3 )
•	Arten er selvstendig reproduserende utendørs (C2)

**Comment by svetlnaumova** [comment]
C2 er ikke med i utbredelsesfanen. Må den legges til eller har du bare samlet her alt som skal endres?

**Comment by AneMarlene** [comment]
Det var nok bare jeg som samlet alt i "hui og hast" før jeg måtte avslutte dagen. :) C2 er bare på artens status ja.

**Comment by AneMarlene** [comment]
Alt har blitt gjort rett her ja :) Da håper jeg vi er ferdige med å endre ordlyden i disse 😄
