### ISSUE TITLE
Utregning av Ekspansjonshastighet for selvstendig reproduserende arter (B-kriteriet, Anslått økning i forekomstareal)

### ISSUE THREAD

**Issue by sindrely** [Artsdatabanken/Fremmedartsbase2023#303]
Måten ekspansjonshastighet beregnes på for selvstendig reproduserende arter trenger en liten justering (Hanno har kommet fram til at den er feil med en faktor 1000). 
Altså denne (bare de tre linjene jeg har ringa inn):

![bilde](https://user-images.githubusercontent.com/91675679/146056583-e66cc4de-3ab0-4d2d-b1b1-51924ea84934.png)

Må endres til:

ExpansionSpeed  <- trunc(sqrt(AOOdarkfigureBest) * 1000 * (sqrt(AOO2) - sqrt(AOO1)) / ((AOOyear2 - AOOyear1) * sqrt(pi)))
ExpansionLowerQ <- trunc(sqrt(AOOdarkfigureLow)  * 1000 * (sqrt(AOO2) - sqrt(AOO1)) / ((AOOyear2 - AOOyear1) * sqrt(pi)))
ExpansionUpperQ <- trunc(sqrt(AOOdarkfigureHigh) * 1000 * (sqrt(AOO2) - sqrt(AOO1)) / ((AOOyear2 - AOOyear1) * sqrt(pi)))

En tillegskommentar:

Ser at det i basen er skrevet "round" i utregningen av disse:
![bilde](https://user-images.githubusercontent.com/91675679/146058507-026dc69f-352b-4785-8d88-dde4371a508a.png)

mens i scriptene våre står det "trunc". I R er "round" vanlig avrunning:
round(1.4) = 1, round(1.5) = 2,
mens "trunc", alltid trukerer verdien mot 0, altså
trunc(1.4) = 1 OG trunc(1.5) = 1

Vet ikke hvordan round fungerer i javascript (eller hva nå en dette er), og det har neppe stor betydning, men jeg tenkte jeg kunne nevne det.

**Comment by bugdriven** [comment]
Jeg har sjekket inn en fix for dette, MEN jeg ser at jeg ikke har samme versjon av Hannoscriptet!! Så her er det mere som må sjekkes!
