### ISSUE TITLE
Naturtypefane: Fiks på Naturtype tabellen

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#308]
- [x] Når man velger naturtype og få opp boksen der kan velge videre "Tidshorisont", "Kolonisert areal %" osv. Her mangler det valg av "Tydelig påvirka areal %" (sammenligne hva som bør fylles inn i tabellen). For "Tydelig påvirka areal %" det skal være mulig å velge fra: 0.0-1.9; 2.0-4.9; 5.0-9.9; 10-19.9; 20.0-49.9; 50.0-100.0.
- [x] Sjekke at data fra valg vises i riktig plass, nå virker så alt er forskjøvet mot høyre. F.eks. Tidshorisont data vises nå i i tabellen under " kolonisert areal %"
- [x] Kolonne bredde for "Kode" kan være smalere for å lage mer plass for naturtype navn i tabellen.
- [x] Kolonne navn "Vurderingsgrunnlag" kunne stått i to liner for å ta mindre plass.

**Comment by svetlnaumova** [comment]
@EveliinaP jeg la til "Tydelig påvirka areal" i boksen for både RL- og NiN-naturtyper, men ikke til livsmedium. Si ifra hvis jeg har misforstått noe.

**Comment by EveliinaP** [comment]
Dette ser bra ut men jeg oppdaget en annen ting nå: det ser ut at for truede og sjeldne naturtyper vises det "id" som kode i tabellen. Kode som skulle vises her er "typekode" men de kan ofte være veldig lange (kombinasjon av flere). Derfor jeg foreslå at for disse det vises ingenting for "Kode" kolonne i tabellen. Kan du fikse det til @svetlnaumova?

**Comment by svetlnaumova** [comment]
@EveliinaP dette burde være fikset nå så lenge kodene for truede og sjeldne naturtyper inneholder kun tall. Dette stemmer så vidt jeg har skjønt, men gi beskjed hvis det finnes noen unntak, så skal jeg ordne det.

**Comment by EveliinaP** [comment]
Jeg er nokså sikker at det er bare id som er nummer for de, så det skal være i orden. En annen ting jeg bør har fanget før er at når man velge naturtype og få opp valg for tidshorisont osv. Så bør det sikkert heller være navn på naturtypen og ikke id nummer som stå øverst. F.eks. her i stedet for 79 bør det være "Isskurt fjæresone-fastbunn"
![image](https://user-images.githubusercontent.com/25793207/148026464-e49bde27-aa11-4b40-896d-0161550495cb.png)

**Comment by EveliinaP** [comment]
Dette issue var closed selv om det egentligen var liten fix igjen. Kunne du @svetlnaumova fått sett på dette?

**Comment by svetlnaumova** [comment]
Sorry, trodde overskriften var fikset. Nå må det være i orden.

**Comment by EveliinaP** [comment]
Nå virker som dette er fikset for skjelde og truede naturtyper men ikke for øvrige typer eller livsmedium. Jeg kunne vært mer presis her, beklager!
