### ISSUE TITLE
Konsekvent tekst for Kriterie skår og usikkerhet visning

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#309]
I naturtypefane stå det nå "Angi skår og usikkerhet" ovenfor overført skår (se bilde). I naturtypefane (og om jeg har forstått også i andre plasser i FAB) skulle dette vise skår men ikke endre det og skal det være mulig å redigere usikkerhet. Slik som teksten står nå er dette tekst misvisende. Kanskje det bør skrives: "Skår og angi usikkerhet"? Men det er mulig at dette gjelder også andre plasser i basen så jeg mener det er beste om en av dere @AneMarlene eller @sindrely se disse gjennom i hele basen og tenke hva som skal stå for de. Per i dag er det også to forskjellige måter å vise dette på i naturtypefane (en med og resten uten radioknapp). Mulig dette bør være egen issue der også alle faner er viste på likt måte?
![image](https://user-images.githubusercontent.com/25793207/146519430-6c01fd06-32fe-49b5-a843-c507f044e917.png)

**Comment by svetlnaumova** [comment]
@EveliinaP nå som alle relaterte issuer er lukket, kan vi lukke denne også eller er det noe mer som gjenstår?

**Comment by EveliinaP** [comment]
Jeg lukker dette, bra jobba!
