### ISSUE TITLE
Naturtypefane: regional naturvariasjon

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#312]
Det har blitt endring til hvordan vi ønsker at ekspertene kan velge fra beskrivelsesvariabler: regional naturvariasjon (https://www.artsdatabanken.no/Pages/182001/Regional_naturvariasjon). 

I stedet for å gi det som skog dominans var gitt sist der det var koblet mot naturtyper her skal det lages eget liste med koder slik som for øvrige naturtyper og disse skal lagres i eget tabell.
![naturvariasjon](https://user-images.githubusercontent.com/25793207/147132928-bd505af2-30e5-4ef6-9778-7a42e7ebf552.png)

**Comment by AneMarlene** [comment]
@bugdriven  @svetlnaumova  Her kommer det en ny versjon, så avvent med denne issuen. :)

**Comment by EveliinaP** [comment]
Det er lagt ny issue med detaljer om hvordan dette skal gjøres i #395. Skal stenge dette issue da.
