### ISSUE TITLE
Skår og usikkerhet - B-kriteriet ved valg "Anslått økning i forekomstareal"

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#319]
relatert til issue #309 

Ved "Anslått økning i forekomstareal" vil tittelen over skårtabellen være ulik for dørstokkarter og andre arter. For dørstokkarter gjelder følgende tittel: "Skår og usikkerhet, oppsummert". Her skal det altså ikke være mulig å endre i selve skårtabellen. For øvrige arter skal det  stå "Skår, angi usikkerhet". Skåren hakes av automatisk ut ifra beregnet ekspansjonshastighet, usikkerheten kan eksperten hake av opp og ned (om den ligger utenfor skårens terskelverdier)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror det har blitt riktig både når man har valgt "Anslått økning" og "Datasett", men tabellen/radioknappene vises også før man har gjort et valg - hvilken overskrift skal stå der? Eller er det bedre å ikke vise noe i det hele tatt før man velger noe?

**Comment by AneMarlene** [comment]
@svetlnaumova, litt sent svar. Nå er utseendet riktig for 
- dørstokkarter, anslått økning
- dørstokkarter, datasett
- selv. repr, datasett
- selv. repr, anslått økning (men denne er litt vanskelig å verifisere pga. kartavhengighet)

Det er riktig at radioknappene vises hele tiden. Det er det jeg og Olga egentlig ønsker for alle kriterier. Vi ser de er borte for flere, men vi ønsker samme utseende for alle :)
