### ISSUE TITLE
Artens status - bug?

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#321]
Jeg klarte å få til dette utseendet på karplanten min. Altså, at jeg ikke får opp underspm på dette spm, men i stedet får se alle de andre spørsmålene: 

![image](https://user-images.githubusercontent.com/58254444/147936072-14b324c7-07e8-4a81-878a-bd16facabe7a.png)

**Comment by svetlnaumova** [comment]
@AneMarlene vanskelig å si hva som foregår der siden jeg ikke kan teste akkurat på denne arten, men den er (kanskje) fikset nå. Kunne du sjekket og lukket denne hvis du ikke kan gjenskape det nå, eller gi beskjed om du finner flere arter som får samme bug?

**Comment by AneMarlene** [comment]
Her har det kanskje dukket opp noe relatert. Nå vises de to svaralternativene for "ja" når man går inne på en art man ikke har gjort noe på. Hvis jeg endrer svaret fra "nei" til "ja", og så tilbake til "nei", så forsvinner de.

![image](https://user-images.githubusercontent.com/58254444/148055995-946ce787-b671-41a2-8880-380cdc6f667a.png)

**Comment by AneMarlene** [comment]
og den originale feilen er på en måte fortsatt tilstede. Spørsmålene under dette, kommer fortsatt opp, selv om det er svart "ja":

![image](https://user-images.githubusercontent.com/58254444/148056235-ec0a767d-bd82-42c1-b7d4-222fbffe5bcf.png)

**Comment by AneMarlene** [comment]
...foreløpig får jeg bare feilen på Abies alba. Snedig..

**Comment by AneMarlene** [comment]
På Abies alba lagrer den heller ikke endringen fra Nei til Ja på øverste nivå (når man går ut og refresher basen og går inn igjen), selv om den lagrer utfylling på undernivåene. Hva har skjedd her tro? Du må bare stjele arten og teste. Kanskje forsvinner det av seg selv da?!

![image](https://user-images.githubusercontent.com/58254444/148194035-4622ff00-e9c5-4cdc-99eb-6368d4a6b9ee.png)

**Comment by AneMarlene** [comment]
@svetlnaumova Nå har jeg funnet en oppskrift på å produsere feilen. Lurer på om dette er relatert til at noen av migreringsissuene (@steinho). For arter som i testbasen har fått forhåndsutfylt "Nei" på spm om taksonet er inkludert i vurderinga av et annet takson (f.eks. arter som i issue #290), så hoppet svaret tilbake til "nei" etter at lagring er gjort. Jeg åpnet karplanten nyseryllik, endret svaret fra "nei" til "ja", lagret, gikk ut - refreshet - og inn, og da så det slik ut: 

![image](https://user-images.githubusercontent.com/58254444/148196130-ac0c2d65-86a1-4ea0-94d1-2925697b9f6b.png)

**Comment by steinho** [comment]
> @svetlnaumova Nå har jeg funnet en oppskrift på å produsere feilen. Lurer på om dette er relatert til at noen av migreringsissuene (@steinho). For arter som i testbasen har fått forhåndsutfylt "Nei" på spm om taksonet er inkludert i vurderinga av et annet takson (f.eks. arter som i issue #290), så hoppet svaret tilbake til "nei" etter at lagring er gjort. Jeg åpnet karplanten nyseryllik, endret svaret fra "nei" til "ja", lagret, gikk ut - refreshet - og inn, og da så det slik ut:
> 
> ![image](https://user-images.githubusercontent.com/58254444/148196130-ac0c2d65-86a1-4ea0-94d1-2925697b9f6b.png)
> 
> Altså, underspørsmålene som bare skal vises ved svar "ja", vises sammen med alt annet, mens svaret er satt tilbake til nei.

Jeg ser det er en skult avhengighet i koden - kan se ut som den blir nei uansett hvis det i bold under stemmer. kan det være noe av forklaringen?
:
        get connectedToAnotherString() {
            // const value assessment.alienSpeciesCategory == "AlienSpecie" ? "no" : assessment.connectedToAnother ? "true" : "false" 
            return **assessment.notApplicableCategory == "establishedBefore1800" ? "no"** : assessment.connectedToAnother ? "yes" : "no"
        },
        set connectedToAnotherString(s) {
            assessment.connectedToAnother = s === "yes"
        },

**Comment by svetlnaumova** [comment]
@AneMarlene nå har jeg prøvd å følge din oppskrift på en testart rødrev og det gikk greit. Kunne du sjekket om du fremdeles får feilen? 
![image](https://user-images.githubusercontent.com/43623201/150577942-4c41b727-45d6-4de0-be26-44a0db427efa.png)

**Comment by AneMarlene** [comment]
@svetlnaumova tror ikke denne eksisterer lengre nei :)
