### ISSUE TITLE
Oppsummering - bytte ut matrise

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#324]
Vi ønsker å bytte ut denne matrisa:

![image](https://user-images.githubusercontent.com/58254444/148040373-46a5b160-da54-4336-aa84-8efc577f1d5c.png)

med utseende her: 
![image](https://user-images.githubusercontent.com/58254444/148040403-22d312af-3b8c-4c90-bc92-1246755519a3.png)

Den siste finner du her: 
https://artsdatabanken.no/Pages/239659/Risikokategorier_og_kriterier

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har gjort et forsøk på å fikse matrisen - er det greit å ha den som den er nå inntil videre? Det går også an å legge til teksten inne i selve matrisen ("Høy risiko (HI)" osv) hvis det er ønskelig, men pilene og alt annet grafisk er dessverre vanskelig og kommer til å kreve en del tid.

**Comment by AneMarlene** [comment]
@svetlnaumova dette begynner å bli kjempepent! SYnes dette ble bra. Eneste er om det er mulig å midtstille titlene (Økologisk effekt og invasjonspotensiale), samt å gjøre tall med tilhørende tekst ("1 lite" osv.) noe mindre. Er det mulig tro?

**Comment by svetlnaumova** [comment]
@AneMarlene det er ikke noe problem å få til :)

**Comment by svetlnaumova** [comment]
@AneMarlene nå har det skjedd noe og alle (?) arter har fått status NR og derfor kan man ikke se matrisen, men når det blir riktig igjen, skal den bli superfin :)
