### ISSUE TITLE
Inngangssiden - tekstendringer

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#327]
Denne issuen må gjøres før issue #326 kan ferdigstilles av Stein. 

- [x] I filteret ved valget nåværende vurdering (Merk: ikke ved valget 2018-vurderinger, så filtrene under hver av disse blir ulike), kommer det noen tekstlige endringer:

1. ordet "etablering" byttes ut med "selvstendig reproduksjon"
2. filteret endrer navn til "Inkludert i vurderinga av annet takson"
3. Alle filtre med rødt kryss over skal slettes.

![image](https://user-images.githubusercontent.com/58254444/148213069-e53b415b-2995-4440-8227-dd83e461d99c.png)

- [x] I filteret for framdrift osv. er det tre endringer:

1. ordet "ferdigstilt" endres til "påbegynt" (merk at under **horisontskanning** skal den fortsatt hete "ikke ferdigstilt")
2. kolonnetittelen endres til "Kommentarer"
3. Start setningene med stor bokstav (På mine, Alle)

![image](https://user-images.githubusercontent.com/58254444/148213720-0bf49036-dccb-4328-aa1d-a5409d75fcc3.png)

**Comment by AneMarlene** [comment]
Jeg åpner denne igjen, da det virker som at de med kryss over ikke er slettet? Dette gjelder filteret for nåværende vurdering, ikke kommentarer og framdrift. :)

I tillegg: filteret om potensiell dørstokkart skal slettes: 
![image](https://user-images.githubusercontent.com/58254444/149108038-d0d3132b-e733-43f1-845d-4289dafa2b06.png)

**Comment by svetlnaumova** [comment]
Jeg skjønner ikke helt hva som er feil her - ser ut som alt som skulle bli slettet fra "Ikke risikovurdert"-filteret har blitt slettet nå?
![image](https://user-images.githubusercontent.com/43623201/149327400-6c0adf14-6e2b-4b3b-971e-5e1bd6cbb660.png)

**Comment by AneMarlene** [comment]
Nå er det rett hos meg også. Vet ikke hva som skjedde den dagen vi hadde møte...for jeg var så sikker på at det hadde vært rett før det møtet også...skjønner ingenting, men nå lukker jeg den her :D
