### ISSUE TITLE
Artskart på B-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#328]
I Artskart-visningene på B-kriteriet, kan denne knappen slettes om det er mulig å gjøre det der, men ikke under utbredelses-fanen: 
![image](https://user-images.githubusercontent.com/58254444/148511976-0f1d802b-0a0b-45ae-9a05-4b49ea146011.png)

Det er altså om man trykker på en av disse: 
![image](https://user-images.githubusercontent.com/58254444/148512051-96a45c43-6cdd-4fa9-98a1-e214fb599ecc.png)

**Comment by steinho** [comment]
@AneMarlene  - bør kunne testes nå

**Comment by AneMarlene** [comment]
@steinho Hos meg er knappen der enda: 
![image](https://user-images.githubusercontent.com/58254444/152751867-91578490-17cb-4d75-96af-78e41939d712.png)

**Comment by steinho** [comment]
@AneMarlene - kan testes
