### ISSUE TITLE
Artskart på B-kriteriet - overføring av årstall og kjent forekomstareal tilbake til vurderingen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#329]
Årstall overføres til feil kolonner når man legger til årstall i Artskart-applikasjonen. 

- Nå går det an å redigere f.o.m. år i kartappl., det skal ikke gå. Denne redigerers under utbredelses-fanen, og samme år brukes her. 
- t.o.m. år og kjent forekomstareal ved trykk på Artskart-knappen markert i rødt, skal inn på første rad. 
- t.o.m. år og kjent forekomstareal ved trykk på Artskart-knappen markert i blått, skal inn på andre rad. Her skal t.o.m. år og kjent forekomstareal som default være overført fra utbredelsesfanen, men de to skal altså kunne overskrives hvis eksperten bruker Artskart-knappen her. :)

![image](https://user-images.githubusercontent.com/58254444/148513964-a7ea28d1-9e53-4cc5-a9b0-bd493a91c547.png)

**Comment by AneMarlene** [comment]
@steinho ikke bry deg om den flyttingen av 2005 i skjermbildet over. Akkurat den feilen er borte.

**Comment by steinho** [comment]
@AneMarlene - skal kunne testes nå

**Comment by AneMarlene** [comment]
@steinho denne virker å fungere! HuRRA! Jeg fant en feil som kødder til det fine resultatet litt (se issue #425 ), men denne her lukker jeg.
