### ISSUE TITLE
Last ned fil - risikovurdering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#330]
På risikovurdering lastes filen for horisontskanning ned om man trykker på denne: 
![image](https://user-images.githubusercontent.com/58254444/148542994-9bf6c835-bf75-4077-9f23-f3b54ee5ae16.png)

Her skal vi selvsagt ha en fil med kolonner som bruker under selve risikovurderingen :) Hvilken fil som lastes ned må altså være sensitiv til om man er inne på horisontskanning eller på risikovurdering.

**Comment by steinho** [comment]
@AneMarlene - jeg la til en første endring på denne - eksporten er nå sensitiv til om det er fullvurdering eller ikke.

Men vi må gjøre en jobb på å definere hvilke felt som skal ut - se https://github.com/Artsdatabanken/Fremmedartsbase2023/commit/57930a2ff5a55349ca064f2580287077a949149d

**Comment by steinho** [comment]
@la til en del mer - kun lister som mangler nå - alt er relativt usortert - og antall kolonner i denne fila ......

**Comment by AneMarlene** [comment]
@steinho skal vi lukke denne og åpne en ny med oversikt over endringer i kolonner og kolonnenavn etc når vi har det mer klart?
