### ISSUE TITLE
Forekomstareal - dørstokkarter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#335]
De to feltene markert i blått er ikke redigerbare (dette er for dørstokkarter). Det er kanskje enklere å forstå om de får grå farge, slik som andre ikke-redigerbare felt har enkelte andre steder i basen. :) 

![image](https://user-images.githubusercontent.com/58254444/148771447-6ae847fc-73cf-465e-bc5f-2f75e0439d47.png)

**Comment by svetlnaumova** [comment]
Dette skal (sannsynligvis) være ordnet straks. Skjønner jeg riktig at de er deaktiverte for alle dørstokkarter, og er redigerbare for selvstendig reproduserende?

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har glemt å tagge deg i forrige kommentaren, så du har sannsynligvis ikke sett den. Kunne du sjekket om denne er i orden nå?

**Comment by AneMarlene** [comment]
@svetlnaumova Ja, så ikke denne :) Disse feltene finnes kun for dørstokkarter (fanen ser annerledes ut, og feltene heter noe annet for selvstendig reproduserende arter). Den virker å være ok nå, så jeg lukker :)
