### ISSUE TITLE
Artens status - nytt spørsmål for enkelte arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#336]
Vi synes ikke Artens status er komplisert nok, og vil derfor slenge inn enda et spørsmål med avhengigheter. :D 

For arter som kom til risikovurderingen via Horisontskanningen _og_ som skåret 1 på etableringspotensialet og som har oppgitt en av de tre markerte etableringsklassene i screenshoten under, trenger vi et ekstra spørsmål for å gi arten riktig "tag": 

"Arten skåret 1 på etableringspotensialet under horisontskanningen. Dette kan bety at arten var antatt å reprodusere på stedet uten at den sprer seg ut av forekomstruten i løpet av 10 år (i et 50-årsperspektiv), eller at arten var antatt å overleve på stedet, men ikke reprodusere. Er det antatt at arten reproduserer i et 50-årsperspektiv?"

Etableringsklassene som er aktuelle (det kan hende at A også blir aktuell...men sier i fra i tilfelle): 
![image](https://user-images.githubusercontent.com/58254444/148932069-30af2c48-a9df-44eb-b840-08bd5c4f5560.png)

Spørsmålet stilles her: 
![image](https://user-images.githubusercontent.com/58254444/148932220-911bc3be-0272-424a-bf7d-c80c1f21b393.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg fant ikke noen arter som har denne kombinasjonen og fikk ikke testet, men regner med at det må se ok-ish ut (men ikke fungerer helt som det skal foreløpig). Regner med at svaralternativene er "Ja" og "Nei"? Eller er det mulighet for flere?

**Comment by AneMarlene** [comment]
@svetlnaumova Jeg glemte helt svaralternativer, men ja, du har rett i at det er ja og nei. :D Lurer på om eksempler på slike arter først blir synlige når de artene som gikk videre fra HS blir tilgjengelige under risikovurdering. Dette burde vi antagelig lage funksjonalitet for nå, slik at vi får testet. Jeg skal prøve å huske å opprette et issue på det i morgen :)

**Comment by AneMarlene** [comment]
@svetlnaumova innser nå at på skjermbildet mitt øverst i issuet, så var ikke etableringsklasse B2 med, men den skal også inngå. Altså  spørsmålet skal også dukke opp for de med valget B2 på etableringsklasse gitt at øvrige betingelser er oppfylt. :)

**Comment by svetlnaumova** [comment]
@AneMarlene nå som vi har arter tilgjengelige for testing, kunne dere sett og lukket denne hvis alt fungerer som det skal?

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har testet litt på gullsjakal i testarter og denne ser greit ut, så jeg lukker den. Bare å åpne igjen hvis noe ikke fungerer som det skal.
