### ISSUE TITLE
Artens status - fjerne logikk bak hvilke felt som skal vises under "Første observasjon av arten"

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#341]
Vi har konkludert med at (nesten) all logikken her kan fjernes, unntatt logikken som ligger bak etableringsklasse "A", samt logikk for når skrivefelt skal vises. Mao, alle årstall-feltene vises for alle arter med etableringsklasse B1-C3:

![image](https://user-images.githubusercontent.com/58254444/149119260-29de06c4-90fe-4c24-a5f1-8356e1967aad.png)

**Comment by svetlnaumova** [comment]
Nå har jeg fjernet logikken og det ser ut til å være riktig, men fint om du kan ta siste sjekk og se om jeg ikke har fjernet for mye :)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg ble usikker på om du har sett min kommentar - får du til å sjekke?

**Comment by AneMarlene** [comment]
@svetlnaumova hadde nok ikke kommet dit, takk for påminnelse ;) Denne kan lukkes!
