### ISSUE TITLE
Inngangssiden - Ny artsgruppe for risikovurdering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#342]
Artsgruppen "Sopper" skal splittes i to, siden en del av artene der inne ikke er sopper, men er kromister. De skal inn i ei ny artsgruppe som skal hete "Kromister". 

De som skal flyttes er alle "Soppene" med følgende øverst i sin taksonomiske sti:

Chromista/

Mulig det stort sett er arter fra horisontskanningen som havner i den artsgruppa. Jeg har ikke helt oversikt over om det fantes noen kromister i FAB 2018..

**Comment by steinho** [comment]
> Artsgruppen "Sopper" skal splittes i to, siden en del av artene der inne ikke er sopper, men er kromister. De skal inn i ei ny artsgruppe som skal hete "Kromister".
> 
> De som skal flyttes er alle "Soppene" med følgende øverst i sin taksonomiske sti:
> 
> Chromista/
> 
> Mulig det stort sett er arter fra horisontskanningen som havner i den artsgruppa. Jeg har ikke helt oversikt over om det fantes noen kromister i FAB 2018..

Chromista/ -> Kromister?

(Var rom for å misforstå over...)
