### ISSUE TITLE
Migrering fra FAB3 - Artens status, årstall for første observasjon

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#346]
Olga har laget regler for overføring fra FAB3 til FAB4. De er i følgende dokument: 

[Overføring av data, første observasjon.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7860988/Overforing.av.data.forste.observasjon.docx)

**Comment by AneMarlene** [comment]
@steinho Her har det skjedd noko gale. Slik er f.eks. Abies alba (karplante) i FAB3:
![image](https://user-images.githubusercontent.com/58254444/149472193-d8d416cd-d8d7-4015-8044-f37fa9d7f29a.png)

Dette har blitt slik i FAB4: 
![image](https://user-images.githubusercontent.com/58254444/149472231-4089a56a-d5a1-4c68-a80a-db0154553906.png)

**Comment by AneMarlene** [comment]
@steinho 1-tallene er borte, så nå virker ting mer korrekt. Lurer litt på denne inne på karplanten abies alba: 

<img width="566" alt="image" src="https://user-images.githubusercontent.com/58254444/150404353-1c660f88-f1e7-4465-9e28-cffd282c9b99.png">

Den skulle blitt hentet fra dette feltet i fab3 (siden 1745 < 1770):
<img width="540" alt="image" src="https://user-images.githubusercontent.com/58254444/150404652-5d748ebd-8386-484d-baae-472b8771ed66.png">

men det har altså blitt til en feilbeskjed. Hva har skjedd der tro?

**Comment by steinho** [comment]
Ser slik ut for meg uten skrive tilgang - teksten du viser til er jeg litt usikker på men koden ser ut til å vise den hvis man skriver inn ett negativt årstall eller ett større enn 2023 :
![image](https://user-images.githubusercontent.com/3253353/150479373-e01662b7-6d61-45c8-aeae-0d8e7e40e968.png)

**Comment by AneMarlene** [comment]
Dette var rart, da jeg gikk inn i basen igjen i dag var den tilbake til 1745 ja. Jeg lukker denne da :)
