### ISSUE TITLE
Horisontskannede arter som gikk videre må bli tilgjengelig for risikovurdering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#350]
I driftbasen er som kjent ekspertene ferdig med horisontskanningen. Sett bort fra sopper og karplanter, kan artene som gikk videre nå bli tilgjengelig under risikovurdering (i testbasen kan selvsagt alle artsgrupper bli tilgjengelig). Det er artene i denne gruppa som sendes videre: 

![image](https://user-images.githubusercontent.com/58254444/149522270-a139dbe8-9ee9-4f32-9785-2e8283ef30a8.png)

For disse artene ønsker vi også at utfyllingen som er gjort under horisontskanningen blir lesbar under risikovurderingen. F.eks. at fanen vises som her (bare at de øvrige fanene er tilgjengelige): 

![image](https://user-images.githubusercontent.com/58254444/149522461-41cfe665-64d3-4ee9-b163-eee2c81d3479.png)

**Comment by AneMarlene** [comment]
Denne bør vi få prioritert ganske raskt. Noe testing avhenger bl.a. av at dette er på plass.

**Comment by bugdriven** [comment]
Jeg har sett på dette og forstår ikke helt hvordan reglene og mekanikken for dette er.

**Comment by steinho** [comment]
@svetlnaumova 
        public string HorizontScanResult { get; set; }
0 ikke hs, 1 gikk ikke videre, 2 videre fra horizontscanning

I resultatlisten fra filtrering av vurdering.....

**Comment by steinho** [comment]
@olgahil og @AneMarlene  - Gjorde ett forsøk på å få frem dette på grei måte i tabellen

På test skal HS vurderingene nå være tilgjengelig på full vurdering - Merk konsekvensen av at de ikke lengre står under horizontscanning - og statistikken der...

**Comment by AneMarlene** [comment]
@steinho Dette ser bra ut! Før det tas inn i drift for Sopper, Bakterier og Kromister må vi finne ut hvilke av artene som ikke skal over. 
@svetlnaumova Er det mulig å lage et filter, slik at vi kan få opp kun de med HSc = HS i listen?

**Comment by AneMarlene** [comment]
@steinho Får vi inn horisontskanningsfanen for de med HSc = HS? Og det er også litt rar forhåndsutfylling på artens status. Alle disse artene er nok fremmede. 

![image](https://user-images.githubusercontent.com/58254444/152159416-56d3fbe5-76a6-426a-8012-f4701bf3e70b.png)

**Comment by svetlnaumova** [comment]
@AneMarlene nå ser det ut til å være i orden både med forhåndsutfylling, HS-fanen og filtreringen på inngangssiden - bare å lukke hvis det ikke er noe mer her.
