### ISSUE TITLE
skår og usikkerhet - feil utseende på tabell

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#351]
Disse mangler tall og radioknapper:
- Alle estimeringsmetoder på A-kriteriet 
- D-kriteriet
- E-kriteriet
- H-kriteriet
- I-kriteriet

Eks:
![image](https://user-images.githubusercontent.com/58254444/149523940-5b36e4d0-b597-447a-8934-ab59e446fcbb.png)

**Comment by svetlnaumova** [comment]
@AneMarlene nå skal radioknappene vises på alle kriterier, men samtidig ble jeg usikker på om check-symbolen vises som den skal (og om den burde være der i det hele tatt). Har du noen meninger om det?
