### ISSUE TITLE
Spredningsveier - layout på pop-up bokser

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#364]
Vi har to/tre ønsker her, mer er litt spente på hvor enkle de er å implementere ettersom disse vinduene skaper litt trøbbel for dere... hehe :) 

1. Er det mulig å lage pop-up vinduene litt "kortere"? Det er veldig langt mellom siste rullegardin og bort til "x'en" slik det er nå.
2. kan vi få rette hjørner (ikke avrundede)
3. Bonusspørsmål: Er det mulig å få med navnet på hovedkategorien før kategorien? (markert i blått). På eksemplet her er hovedkategorien "Direkte import", slik at vi skulle ønske det sto "Direkte import til forskning"
<img width="934" alt="image" src="https://user-images.githubusercontent.com/58254444/149774380-f10e8e2c-85b0-4e67-918e-93d4bbff75c8.png">

**Comment by svetlnaumova** [comment]
@AneMarlene be careful what you wish for... Har fikset det, men noen av overskrifter har blitt litt rare (se screenshoten). Er det kanskje bedre å legge til en kolon mellom hovedkategorien og underkategorien? 
![image](https://user-images.githubusercontent.com/43623201/149808646-9b058ff6-646e-4f3f-8f79-4e6fe7918b67.png)
