### ISSUE TITLE
Naturtyper - Naturtypeareal truede arter 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#366]
Jeg lurer på om vi kan skjule en raritet fra Rødlista for naturtyper. Der er det slik at hvis eksperten _ikke_ har fylt ut noe på naturtypeareal, så står det at denne har areal "0". Det stemmer åpenbart ikke ettersom naturtypene finnes i Norge. Derfor lurer jeg på om vi kan skjule naturtypearealet hvis det står "0"? Altså at feltet da er blankt/tomt? 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/58254444/149905607-aa90696b-aba9-4d80-bc31-149964752aea.png">

**Comment by svetlnaumova** [comment]
@AneMarlene jeg klarte ikke å finne arter som har slike naturtyper, men kunne du sjekket om det har blitt riktig nå?

**Comment by AneMarlene** [comment]
Nå ser det riktig ut: 
![image](https://user-images.githubusercontent.com/58254444/150107815-566f616f-52b4-4fc8-beda-16357d60b39a.png)

Jeg tror forresten ingen hadde slike verdier fra før av, ettersom dette er nytt. Så jeg prøvde bare å legge til den samme som jeg la til i skjermdumpen over der:)
