### ISSUE TITLE
Horisontskanning må være tilgjengelig kun for noen arter

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/Fremmedartsbase2023#37]
Må legge til en property som viser om arten skal horisontskannes eller ikke. Hvis den ikke skal horisontskannes, blir denne fanen ikke tilgjengelig.

**Comment by AneMarlene** [comment]
Her kommer regler for hvilke arter som skal gjennom horisontskanningen. @bugdriven vi må få dette på plass så fort som mulig. Får du til å orde denne biten for alle som står under punkt 2 i denne fila? 

[Hvilke arter skal gjennom horisontskanningen.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7120070/Hvilke.arter.skal.gjennom.horisontskanningen.docx)

**Comment by AneMarlene** [comment]
Denne tilgjengeligheten må være koblet opp mot dette feltet: 
![image](https://user-images.githubusercontent.com/58254444/132635555-b82eaa9c-d6fb-4b45-a182-178934bf8632.png)

**Comment by steinho** [comment]
Dette er nå ivaretatt. De fra 2018 er riktig merket. Nye må importeres...
