### ISSUE TITLE
Spredningsveier - splitting av kategori i to

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#371]
Følgende kategori (ringet rundt i skjermbildet) under rømning/forvilling skal erstattes av disse to: 

- av levende fôr eller agn (ikke til kjæledyr)
- av levende mat (til mennesker)

![image](https://user-images.githubusercontent.com/58254444/149929212-7aa7dcae-c267-4837-aaf7-d305e0918c54.png)

**Comment by AneMarlene** [comment]
Det var et ekstremt godt spørsmål, Svetlana! Jeg har nå gått gjennom de 13 artene som hadde brukt denne kategorien i 2018. Det er slik at hvis artsgruppen er: 
Fisker eller Karplanter --> av levende fôr eller agn (ikke til kjæledyr)
Terrestriske invertebrater eller marine invertebrater --> av levende mat (til mennesker)

Er det mulig å foreta det skillet for dere under migreringen fra 2018, eller er det mye arbeid? 

Her er listen over de aktuelle artene om det er av interesse: 
1 Barbatula barbatula   Fisker  - NR-art  - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
2 Carassius gibelio     Fisker    - NR-art - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
3 Cobitis taenia        Fisker    - NR-art  - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
4 Culaea inconstans     Fisker    - NR-art  - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
5 Gobio gobio           Fisker    - LO-art --> av levende fôr eller agn (ikke til kjæledyr)
6 Helix pomatia         Bløtdyr   - HI-art --> av levende mat (til mennesker)
7 Homarus americanus    Krepsdyr  - SE-art --> av levende mat (til mennesker)
8 Leucaspius delineatus Fisker    - LO-art --> av levende fôr eller agn (ikke til kjæledyr)
9 Luzula luzuloides     Karplanter- PH-art --> av levende fôr eller agn (ikke til kjæledyr)
10 Misgurnus fossilis    Fisker   - NR-art  - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
11 Rhodeus sericeus      Fisker   - NR-art - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)
12 Umbra pygmaea         Fisker   - NR-art - ikke videre fra HS (denne trenger dermed ingen endring i spredningsvei)
13 Vimba vimba           Fisker  - NR-art   - videre fra HS --> av levende fôr eller agn (ikke til kjæledyr)

**Comment by svetlnaumova** [comment]
@steinho har du noen meninger om hvordan det burde gjøres? Jeg har foreløpig ingen bedre ideer enn å ha to forskjellige kodelister for hver artsgruppe, men det er sikkert ikke optimalt.

**Comment by steinho** [comment]
Oi: oppfatter at det er en fab3 - spredningsveg - som skal splittes i to ny 

Det er best å gjøre dette mellom fab3 og fab4 - altså i migreringen og kan da bruke:
- Fisker eller Karplanter --> av levende fôr eller agn (ikke til kjæledyr)
- Terrestriske invertebrater eller marine invertebrater --> av levende mat (til mennesker)
Til å plassere de.

Oppretter to nye og kommenterer bort den gamle i kodelista... de eksisterende data plasserer i en av de to nye.

Men er det slik at det kun er for historisk bruk - begge de to nye skal fortsatt være "disabled" og ikke mulig å velge nå?

**Comment by steinho** [comment]
Oi2 - her er det noe muffens  - artene du peker på @AneMarlene er knytt til koden i fab3 'liveFoodLiveBait' - som ikke eksisterer i fab4 - det nærmeste der er: "petAquariumTerrariumFood", "Text": "fra levende mat, fôr eller agn (unntatt til kjæledyr)".

Ser nå at mange er blitt endret mellom fab3 og fab4 - uten at det eksisterer noen migreringsplan for å flytte informasjon.
Er dette ok?

**Comment by steinho** [comment]
Har forsøkt fikse i koden over ..... la til to nye koder - lot den gamle som jeg peker på i kommentaren stå - denne skal kanskje bort? Lagt ut på test og kjørt migrering.

Mulig @AneMarlene  mente 'av levende mat til kjæledyr/hobbydyr' - skulle splittes? ikke den du ringet rundt? (var denne som var brukt på de artene jeg tok stikkprøve på...)

**Comment by steinho** [comment]
> Hva skal settes i vurderingen hvis denne kategorien har vært valgt i FAB3 - skal den fremdeles vises som den er, men fjernes fra menyen og erstattes med de to nye kategoriene?

Jeg tror ikke @AneMarlene mener at vi skal operere med to forskjellige lister avhengig av artsgruppe - der må nok ekspertene plukke den koden som er relevant for sin gruppe. Forstår bestillingen slik at en gammel kode - skal splittes i to og eksisterende vurderinger fordeles i mellom disse to.

**Comment by AneMarlene** [comment]
> Oi: oppfatter at det er en fab3 - spredningsveg - som skal splittes i to ny
> 
> Det er best å gjøre dette mellom fab3 og fab4 - altså i migreringen og kan da bruke:
> 
> * Fisker eller Karplanter --> av levende fôr eller agn (ikke til kjæledyr)
> * Terrestriske invertebrater eller marine invertebrater --> av levende mat (til mennesker)
>   Til å plassere de.
> 
> Oppretter to nye og kommenterer bort den gamle i kodelista... de eksisterende data plasserer i en av de to nye.
> 
> Men er det slik at det kun er for historisk bruk - begge de to nye skal fortsatt være "disabled" og ikke mulig å velge nå?

@steinho De er disabled i det skjermbildet fordi arten jeg så på ikke var en bruksart (det har mao ikke noe med historikk å gjøre). Logikken rundt det er det @svetlnaumova som har ordnet. Dette er knyttet til et svar på om arten er en bruksart på fanen Artens status. Kategoriene er altså mulig å velge hvis svaret på om arten er bruksart er "ja", og ellers er de "disabled".

**Comment by AneMarlene** [comment]
> Har forsøkt fikse i koden over ..... la til to nye koder - lot den gamle som jeg peker på i kommentaren stå - denne skal kanskje bort? Lagt ut på test og kjørt migrering.
> 
> Mulig @AneMarlene mente 'av levende mat til kjæledyr/hobbydyr' - skulle splittes? ikke den du ringet rundt? (var denne som var brukt på de artene jeg tok stikkprøve på...)

@steinho , nei jeg mente ikke "av levende mat til kjæledyr/hobbydyr". Jeg mente den jeg hadde ringet rundt. Så om artene var koblet til den (og ikke den jeg hadde ringet rundt) i fab4, så var koblingen feil.

**Comment by AneMarlene** [comment]
@steinho Jeg ser at gammel kategori ikke er slettet enda, men det er kanskje fordi du lurte på hvilken? 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/58254444/150764503-0d6f92b4-b8fe-4eb3-bd4e-401d330073e4.png">

**Comment by svetlnaumova** [comment]
@AneMarlene det er vanskelig å se i testbasen om de artene det gjelder har fått riktig tekst under spredningsveier, men ut i fra det jeg ser i koden burde det være riktig. Har du mulighet til å sjekke?

**Comment by AneMarlene** [comment]
@svetlnaumova denne er rett. Jeg har glemt å lukke. :)
