### ISSUE TITLE
Naturtyper - Rødlista for naturtyper påvirker G-kriteriet i stedet for F-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#375]
Rødlistede naturtyper og øvrige naturtyper gir begge utslag på G-kriteriet. Førstnevnte skal gi utslag på F-kriteriet. 

![image](https://user-images.githubusercontent.com/58254444/149932904-195ac394-14ca-4e04-bab3-251d0ed4ed82.png)

@svetlnaumova har sett at det går å skille disse via NiN-kode, hvor de fra rødlista har kun tall, f.eks. niNCode == "66", mens de rene NiN-naturtypene alltid har bokstaver, f.eks.  niNCode == "NA I1". Kanskje disse kan brukes for å skille på kriteriene, @bugdriven ?

**Comment by bugdriven** [comment]
Fixed
