### ISSUE TITLE
Legge til muligheten for å laste opp filer

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/Fremmedartsbase2023#38]
Trenger funksjonaliteten for å laste opp filer og koble dem til vurderingen i api (både på oppsummeringsfanen og under invasjonspotensiale).

**Comment by steinho** [comment]
La ut en første test på dette under oppsummering...

**Comment by svetlnaumova** [comment]
Ser ikke ut til å fungere i test dessverre. Linken er https://fab4api.test.artsdatabanken.no/api/Document/2299 
![image](https://user-images.githubusercontent.com/43623201/141301366-08ea09e9-d36d-4b4f-b7bb-8523beedc690.png)

**Comment by AneMarlene** [comment]
Jeg får det til å fungere, men jeg må lage navn først. Om jeg prøver å velge fil før jeg har gitt navn, skjer det ingenting.. Jeg lastet opp de to nederste her:

![image](https://user-images.githubusercontent.com/58254444/141303900-fd38496c-f548-4ba2-af4d-9e551c9e730c.png)

**Comment by svetlnaumova** [comment]
Ja, selvfølgelig. Burde enten ha kommet på en bedre feilmelding, eller deaktivere knappen før man har tastet inn et filnavn :)

**Comment by AneMarlene** [comment]
Kanskje burde vi presisere at de må gi navn først, eller åpne for at rekkefølgen kan være motsatt?

**Comment by svetlnaumova** [comment]
Lukker denne siden selve funksjonaliteten ser ut til å være på plass.
