### ISSUE TITLE
Artskartapplikasjon - manglende overføring tilbake til vurderingen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#382]
Når jeg velger "overfør arealer og fylker tilbake til vurderingen" er det ingenting som blir med tilbake, sett bort fra kjent regionvis utbredelse i dag (men kartet for antatt og antatt om 50 år er tomme). 

Mao, dette blir ikke med: 

- [x] årstall (fra og til)
- [x] Kjent forekomstareal
- [ ] regionvis utbredelse for antatt og antatt om 50 år (som da skal være lik den for kjent i dag) 
- [x] en datafil med datagrunnlaget (inkl. punkter som er lagt til og fjernet) - dette punktet er en @steinho jobb tenker jeg :)

**Comment by AneMarlene** [comment]
Jeg har huket av Kjent forekomstareal, da Terje har fikset det i dag.

**Comment by steinho** [comment]
Trenger gjennomgang av sammenhengene her

**Comment by AneMarlene** [comment]
@steinho her gjenstår kun en oppgave. Og den gjelder manglende flyt fra venstre mot høyre i kartene. Når man nå lagrer utvalg fra kartet, så blir det overført slik: 

![image](https://user-images.githubusercontent.com/58254444/151964013-a7edf978-9c27-4343-a05f-be1b70a4181b.png)


korrekt overføring er slik: 
![image](https://user-images.githubusercontent.com/58254444/151964077-44ba77ef-55bf-4cb6-a726-1db3a98c3927.png)

**Comment by AneMarlene** [comment]
Jeg fjernet pri1, da det viktigste i dette issuet er gjort.

**Comment by steinho** [comment]
Kartene skal virke igjen nå - på begge fanene - og årstall lagres ok og overføres ok

**Comment by AneMarlene** [comment]
@steinho Ja, virker som alt her er ok unntatt den flyten fra venstre mot høyre når man overfører regioner fra kartutvalget. Jeg lukker uansett denne, for det siste tror jeg trenger noen justeringer i bestillingen og kommer i et nytt issue.
