### ISSUE TITLE
B-kriteriet - skjule skårtabell før metode er valgt

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#383]
Vi lurer på om det er mulig å skjule skårtabellen før metode er valgt? Om det er en enkel sak, så ønsker vi det (men ikke om det er en mer komplisert sak..)

<img width="389" alt="image" src="https://user-images.githubusercontent.com/58254444/150406504-a0010da5-a0a1-40e7-80e3-fc8dc98663df.png">

**Comment by svetlnaumova** [comment]
@AneMarlene Den burde være riktig nå, men si ifra hvis dere finner noen vurderinger der det fortsatt vises.

**Comment by AneMarlene** [comment]
@svetlnaumova virker som den ikke hadde forsvunnet fra alle vurderinger: (dette er karplanten Armoracia rusticana)
![image](https://user-images.githubusercontent.com/58254444/150974398-a652529a-cb87-4a9e-996a-b6f3aeff5bd8.png)

**Comment by svetlnaumova** [comment]
@AneMarlene grunnen til at dette skjer er at det var noe som har vært valgt under chosenSpreadYearlyIncrease i FAB3 som ikke er tilgjengelig nå (som feilmeldingen i A-kriteriet), derfor ser det ut som ingenting er valgt mens det er faktisk noe som ligger bak. Jeg tror at den er endelig fikset nå, men hvis det er noen flere metoder som jeg ikke vet om, kan den teoretisk dukke opp igjen.
