### ISSUE TITLE
Lagringsbug - fanen naturtyper

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#388]
Om jeg åpner fanen naturtyper på en art jeg *ikke* vurderer, og så skal gå ut av arten igjen, så får jeg beskjed om at jeg har ulagrede endringer på arten (selvfølgelig uten å ha endret noe). JSON gir meg svaret: 

![image](https://user-images.githubusercontent.com/58254444/150741768-1628e0e1-08f2-4a40-b116-674516affd3a.png)

**Comment by svetlnaumova** [comment]
Objektet hadde ikke property "name" i siste versjonen av basen, men jeg trengte den for å kunne vise navn på naturtyper og ikke bare koder. Fant ikke en bedre måte å gjøre det på enn å lage en funksjon (findNTName) som går gjennom kodelister og finner navnet som hører til hver kode, derfor skjer det endringer i JSON. @bugdriven tror du det går an å gjøre noe tilsvarende i datamodellen / ved migreringen?

**Comment by steinho** [comment]
Jeg tror det kan være lurt å få disse inn i migreringsjobben ja. - Praktisk å ha benevninger på data - ikke bare koden.

@svetlnaumova : trengs findNTName etterpå - hvis name kommer inn på de gamle dataene? Kanskje trengs den uansett når de velger nye?

**Comment by svetlnaumova** [comment]
@steinho usikker på om jeg forstår spørsmålet riktig, men hvis objektet allerede har "name" som ikke er tom streng, så trenger den ikke endres fordi det er bare ett navn som tilsvarer hver kode. Det er kanskje optimalt å gå gjennom alle naturtyper / livsmiljø og sette inn "name" slik at det ikke skal trenges å gjøre noe med den på frontend?

**Comment by steinho** [comment]
> @steinho usikker på om jeg forstår spørsmålet riktig, men hvis objektet allerede har "name" som ikke er tom streng, så trenger den ikke endres fordi det er bare ett navn som tilsvarer hver kode. Det er kanskje optimalt å gå gjennom alle naturtyper / livsmiljø og sette inn "name" slik at det ikke skal trenges å gjøre noe med den på frontend?

Tanken var å sette inn name på forhånd ja - der jeg finner kopling i NIN2_3, nin2_2 filene o.l. 

Har kjørt ett forsøk på fiks mot test nå - kan dere teste litt @AneMarlene - om du finner vurderinger som fortsatt "må lagres" eller andre nye problemer.

(registrerer allerede at det er kommet inn noen felt knytt til ArtskartModel - som lager lagre problemer - så sjekk json fanen om det har med dette å gjøre eller naturtypene)
