### ISSUE TITLE
Legge til logikk i spredningsveifanen

### ISSUE THREAD

**Issue by svetlnaumova** [Artsdatabanken/Fremmedartsbase2023#39]
- [x] Legge til logikk som kobler valg i "Til innendørs- og produksjonsareal" og "Introduksjon til naturen"

- [x] Gjøre noen av valgene under "Direkte import" og "Rømning/forvilling" disabled for arter som ikke er bruksarter

**Comment by svetlnaumova** [comment]
Tror denne er nå ferdig, men listen over kategorier i dokumentet stemmer ikke helt overens med det vi har nå i basen - må dobbeltsjekkes. 
![image](https://user-images.githubusercontent.com/43623201/135170127-2c09f314-e372-440f-bc36-9b7c2ee9d51e.png)

**Comment by svetlnaumova** [comment]
@AneMarlene ikke meningen å mase, men høsten har sluttet for litt over en måned siden :)

**Comment by AneMarlene** [comment]
aiaiai, se der ja, Svetlana :D Du maser ikke! Jeg har ikke sett nøye på dette (som du kanskje skjønner), men av det jeg så, virket det rett. Jeg åpner heller noen små-issues ved behov senere :)
