### ISSUE TITLE
Naturtyper - migrering 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#392]
Denne er relatert til issue #388 . 

I NiN 2.3. har vi fått en meningsendring for naturtyper som befant seg under kode F eller L i NiN 2.2. Her er det ikke 1:1 forhold med nye koder.  Dette fører til følgende: 

- Naturtyper med kode F og L fra NiN 2.2 (fab3) må over i ny struktur: Migreres til feltet "Data fra tidligere vurdering" uten redigeringsmulighet. Her må vi hente navn fra NiN 2.2 
- Øvrige naturtyper fra NiN 2.2 har 1:1 forhold med NiN 2.3, og navn for disse hentes fra NiN 2.3. Alle disse migreres fra fab3 til den redigerbare tabellen med navn fra NiN 2.3. 

I tillegg, Livsmedium er i fab4 ikke i samme tabell som øvrige naturtyper. Disse må derfor flyttes ut under migreringen og skal hentes over til objektet  "habitats" i fab4. Ingen navneendringer på livsmedium siden fab3.

**Comment by steinho** [comment]
De ikke kompatible naturtypene har fått sitt gamle navn og er flyttet ut i egen liste :
 ImpactedNatureTypesFrom2018.

**Comment by steinho** [comment]
@svetlnaumova - muligens behov for å få denne visningen litt penere samt at nå er navn inne på de gamle elementene - slik at logikken for å oppdatere navn på disse bør sjekkes - trolig ikke nødvendig - med mindre de trengs ved innlegging av nye valgte naturtyper..

**Comment by svetlnaumova** [comment]
@AneMarlene @steinho det ser ut for meg som det eneste den metoden gjør nå er at den endrer stor forbokstav i navnet på naturtypen til en liten bokstav. Hvis vi ikke trenger denne endringen, så kan vi godt fjerne/kommentere bort metoden, tror jeg.

**Comment by AneMarlene** [comment]
@svetlnaumova Jeg vet ikke helt om jeg skjønner hvilken metode det er snakk om, men jeg fant en art som nå har utgåtte data både fra Rødlista og fra NiN 2.2. Kan vi få ordna slik at de kommer under en og samme overskrift (slette den nederste), samt (punkt 1. i figur) endre mellomteksten på tabellen for 2.2 til "Overførte naturtyper fra NiN 2.2". i tillegg kunne vi sletta "kolonna" med rediger og slett, så kanskje NiN 2.2-naturtypene kan få litt smalere rader? 

Eksempelarten er en som skal slettes fra fab, men ligger per nå på "Ikke-marine invertebrater", arten finnmarkshops.
![image](https://user-images.githubusercontent.com/58254444/152528068-1fdf20eb-b46e-4edd-924d-b198a337bece.png)

**Comment by svetlnaumova** [comment]
@AneMarlene nå tror jeg at tabellene endret og stylet. Er det noe mer som gjenstår med dette issuet?

**Comment by AneMarlene** [comment]
@svetlnaumova ser bra ut dette. En liten detalj om du får tid (ikke førstepri dette).. kan delordet "del-" flyttes opp til linja over, så får vi redusert med en rad? 

![image](https://user-images.githubusercontent.com/58254444/156997807-f5d45732-b0eb-458f-a015-f7e1b44fc475.png)

**Comment by svetlnaumova** [comment]
@AneMarlene da er det ordnet.

**Comment by AneMarlene** [comment]
@svetlnaumova så pent det ble 👯
