### ISSUE TITLE
Artens status - endring i konklusjon for et svaralternativ

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#393]
Vi har innsett at vi har feil konklusjon på et undervalg på et spm. Slik det er nå gir svar "ja" på spm om arten er inkludert i vurderinga til et annet takson alltid konklusjonen "Arten skal ikke risikovurderes". Konklusjonen/hva som skjer videre er imidlertid avhengig av undervalgene. 

Mao, om eksperten velger dette, skal den fortsette i samme løype som de som svarer "nei"  på spm om arten er inkludert i vurderinga til et annet takson (dvs. de får opp spm om arten er en bruksart osv osv): 
![image](https://user-images.githubusercontent.com/58254444/150958766-c63ac640-6120-4c81-851d-6a7d61d80e17.png)
Dette gjelder typisk arter som sitkagran og lutzgran som begge risikovurderes, men som vurderes sammen.

Om eksperten velger følgende, skal konklusjonen være som nå:
![image](https://user-images.githubusercontent.com/58254444/150960126-84a0b07f-46da-4919-9f09-100668ea6391.png)

**Comment by svetlnaumova** [comment]
@AneMarlene tror ikke det kommer frem i opprinnelige bestillingen - hvis jeg skjønte riktig og det ikke har vært vesentlige endringer, så skal man ikke få flere spørsmål hvis man har svart "Ja" på spørsmålet om arten er inkludert i andre vurderinger:
![image](https://user-images.githubusercontent.com/43623201/151005927-e5a1e091-18e2-45b1-adc5-b96a9d003962.png)

**Comment by AneMarlene** [comment]
dette hovedspørsmålet har utgått fra Artens status og issuet er derfor ikke lengre relevant. Jeg lukker.
