### ISSUE TITLE
A-kriteriet: ny tekst når Rødlistekriteriene ble brukt i 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#394]
Slik det er nå kommer det en liten feilmelding i kode-tekst i fab når rødlistekriteriene var brukt som metode i 2018. I stedet for denne feilmeldingen, er det mulig å skrive følgende tekst?

"Den utgåtte metoden c) Rødlistekriterier var brukt på A-kriteriet for denne arten i 2018. Det resulterte i skår _[her settes inn Ascore som tilsvarer RedListCategoryLevel brukt på arten i 2018]_ på A-kriteriet"

![image](https://user-images.githubusercontent.com/58254444/150962397-8763fe6e-111d-4492-b6f8-d0d2ead41bea.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg er usikker på om jeg har tolket "Ascore som tilsvarer RedListCategoryLevel brukt på arten i 2018" riktig - satt inn riskAssessment.ascore, men på alle arter som bruker RedListCategoryLevel som jeg har sett på er den lik 0, så det syntes jeg var litt rart. Er det greit å lukke #275?

**Comment by AneMarlene** [comment]
Jeg lukka #275. :) Det var veldig rart at den var lik 0. Den burde være lik 3 på omtrent alle som brukte rødlistekriteriene. Og det glemte jeg, det tallet som settes inn må være Ascore + 1 (siden det skal gå fra 1-4 og ikke 0-3 som i koden).

**Comment by svetlnaumova** [comment]
@AneMarlene Jeg så f.eks. på kanadagås og snøgås, de begge hadde både RedListCategory og 0 på ascore, så selv om jeg legger til 1, hjelper det ikke alt for mye. Mulig det skjedde noe rart i testbasen, eller om den ble beregnet på nytt?

**Comment by AneMarlene** [comment]
@svetlnaumova Jeg mistenker at vi trenger hjelp fra @bugdriven her. @bugdriven vet hvordan vi får fram skåren fra 2018 på A-kriteriet her? 

![image](https://user-images.githubusercontent.com/58254444/151522299-f11fcb78-42f6-437c-930d-5317811a889d.png)

**Comment by bugdriven** [comment]
Hvis jeg har rett (?) så har vi lagret rødlistekategori som kode. "LC" for kanadagås og "CR" for snøgås f.eks.
Vi kan nok finne criterie level derfra.

**Comment by AneMarlene** [comment]
Jeg lurer på om vi må gå veien om LC, NT osv. ja. Får du til det, @svetlnaumova ? Kanskje med litt hjelp fra @bugdriven ?

**Comment by AneMarlene** [comment]
@svetlnaumova @bugdriven jeg ser det har skjedd noe her ettersom alle ikke lengre er 0. Det er fortsatt noe feil dog. F.eks. på karplanten alpebispelue. Den hadde skår 2 på A-kriteriet i 2018 (rødlistekategori EN), men den står i basen med skår 1: 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/58254444/153765983-d79cba6e-ab2a-4927-a82e-4c3ac0edb928.png">

**Comment by svetlnaumova** [comment]
@AneMarlene den ser ut til å være riktig nå (i alle fall på alpebispelue).

**Comment by AneMarlene** [comment]
ja, fikk Helge til å rette den i dag :)
