### ISSUE TITLE
Naturtyper - bioklimatiske soner og seksjoner

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#395]
Her kommer utkast på hvordan tabellene for bioklimatiske soner og -seksjoner skal se ut. I vedlegget er det 3 tabeller, men hver art skal kun ha maks 2 av disse synlig: 

- Tabellen marine arter gjelder for komiteene "Marine invertebrater", "Marine invertebrater (Svalbard)", "Alger", "Fisker" og "Fisker (Svalbard)"
- Tabellen FastlandsNorge gjelder for alle komiteer _unntatt_ de med Svalbard i navnet og "Marine invertebrater".
- Tabellen Svalbard gjelder kun for "Karplanter (Svalbard)" og  "Pattedyr (Svalbard)"

[Regionvis utbredelse.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7933610/Regionvis.utbredelse.docx)

**Comment by AneMarlene** [comment]
@svetlnaumova liten detalj om tabellene: Det er et surrumsarium om jeg har startet en kolonne- eller radtittel med stor eller liten bokstav. Alle skal ha stor forbokstav :)

**Comment by EveliinaP** [comment]
Jeg sjekket og for meg dette virker som at tabellene er i orden. Jeg fikk testet bare for karplanter om lagring men det se ut til å virke. 
Små ting til: om det er mulig å endre tabell kolonne bredde slik at alle overskriftene har plass i to linjer så er det litt mer lesbar, men er ikke noe man skal bruke mye tid på.  F.eks. her Svaktk kontinental seksjon er i tre rad: 
![image](https://user-images.githubusercontent.com/25793207/152181619-4b01246d-feb8-4894-a786-4f1853773faf.png)

For du @AneMarlene teste lagring for marine og Svalbard? Om det er i orden kanskje vi kan lukke dette?

**Comment by AneMarlene** [comment]
Jeg tror det er noe galt i fab nå, for jeg får bare opp en art og på den ser tabellen slik ut: 

![image](https://user-images.githubusercontent.com/58254444/152312681-5102ab54-7525-4b84-b598-0cac54ed6c90.png)

Jeg skal prøve å komme med en mer konstruktiv kommentar om litt :)

**Comment by svetlnaumova** [comment]
@AneMarlene nå er det litt flere arter i test og tabellen ser mer normalt ut :)

**Comment by EveliinaP** [comment]
Oops, tabell for amfibier er ikke på plass ennå
![image](https://user-images.githubusercontent.com/25793207/152319702-2e226104-dc2e-4704-a024-cb3b891b0615.png)

**Comment by svetlnaumova** [comment]
Har du prøvd Ctrl+F5? Har sett på noen amfibier nå, og det ser greit ut for meg.

**Comment by svetlnaumova** [comment]
Nevermind, fant ut at de som har vært gjennom HS har ikke fått verdiene som burde vært i tabellen. Skal se på det.

**Comment by AneMarlene** [comment]
Jeg har ikke flere kommentarer på issuet her enn de Eveliina har nevnt. Jeg tenker kanskje at alle tabellene skulle hatt en felles tittel, f.eks. "Regional naturvariasjon", og at tabellene skulle blitt flytta lengre ned på fanen (rett over livsmedium), men jeg kan lage et nytt issue på det om du vil, @svetlnaumova ?

**Comment by svetlnaumova** [comment]
@AneMarlene Nei, trenger ikke eget issue på sånt småtteri, skal ordne straks :)

**Comment by svetlnaumova** [comment]
@EveliinaP @AneMarlene ser tabellene greit ut for dere nå? Feilen som har vært hos HS-arter ser ut til å være rettet opp.

**Comment by EveliinaP** [comment]
Se bra ut, takk!
