### ISSUE TITLE
Utbredelse - låste felt som ikke skal være låste

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#399]
Disse feltene (AOO50yrLow og AOO50yrHigh) er nå låst i fab, det er feil. Disse skal være redigerbare. 
![image](https://user-images.githubusercontent.com/58254444/151519961-cf5d633d-092e-4a6d-8884-1f5a03656cb1.png)

**Comment by svetlnaumova** [comment]
Ser ut til å være fikset.
