### ISSUE TITLE
Fanerekkefølge i fremmedartsbasen

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#4]

**Comment by olgahil** [comment]
[Basestruktur250121.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/5910476/Basestruktur250121.pptx)

**Comment by AneMarlene** [comment]
[Basestruktur250121GitHub.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6537951/Basestruktur250121GitHub.pptx)

Ny versjon. Ikke bry deg om ark 2 og 3 foreløpig.

**Comment by AneMarlene** [comment]
Jeg ser vi har skrevet litt feil i en hovedfane: "Klimaeffekt" --> "Klimaeffekter"

**Comment by AneMarlene** [comment]
jeg ser vi satte feil rekkefølge her. Den "til innendørs..." vil forøvrig heller ikke være tilstede for alle arter, men mer detaljer rundt hvordan den fanen skal se ut vil komme ila neste uke :) 
![image](https://user-images.githubusercontent.com/58254444/120771506-9175b300-c51f-11eb-870b-fe193d536a8f.png)

**Comment by svetlnaumova** [comment]
Kan vi si at vi er mer eller mindre ferdige med denne issuen per i dag siden alle fanene fra ark 1 er på plass? Det blir mest sannsynlig ikke noe problem å gi dem nytt navn og/eller slå noen av fanene sammen på et senere tidspunkt om det blir behov for det (ser at ark 2 og 3 går mest ut på det).

**Comment by olgahil** [comment]
Ja, det ser greit ut. Før vi sier oss ferdige (så langt) ser jeg at fanetittelen Informasjon til risikovurdering, gjerne kan endres til Bakgrunnsdata for risikovurdering. Ellers tar vi vel finpussen i neste runde

**Comment by svetlnaumova** [comment]
Tror at jeg lukker denne issuen for det ser ut for min del at mesteparten av den er gjort. Jeg åpner separate issuer på filtrering og horisontskanning i stedet, og det er bare å si ifra om det er noe mer som mangler :)
