### ISSUE TITLE
Karplante-obser som skal bort fra datagrunnlaget i kartløsningen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#40]
Disse to filene inneholder alle observasjonene fra Artskart som ikke skal være med i standardutvalget på karplanter. Når en ekspert er inne i base-kartet på en viss art må den likevel kunne fjerne denne filtreringen (dvs. velge å bruke (noen av) disse observasjonene likevel). 

Observasjonene er delt i to filer fordi, selv om observasjonene i "Forkastede_MaybeEx_Karplanter_fra_Artskart_FAB2018_til_Stein" ikke ble brukt i 2018, så var de litt mer usikker på om disse skulle fjernes eller ikke. Jeg har derfor bedt årets komité om å si fra til oss om noen av disse ikke skal fjernes likevel. Så langt har jeg ikke hørt noe, så jeg regner med de skal bort alle sammen. 

Kolonnen CatNr inneholder katalognummeret, og er grei å bruke til søk i Artskart (kanskje også på baksiden?):
![image](https://user-images.githubusercontent.com/58254444/127860764-92d04e6d-940a-443d-8d39-9cf8a0db8120.png)

Den kolonnen sammen med artsnavn (kolonne "RE_Navn") og dato bruker å være nok for å finne riktig observasjon i Artskart, eventuelt sammen med sted/kommune, samler eller lignende. Bare spør om du lurer på noe, eller om du trenger andre søkekriterier for å finne fram til riktig observasjoner på baksiden.  

[Forkastede_MaybeEx_Karplanter_fra_Artskart_FAB2018_til_Stein.xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6916722/Forkastede_MaybeEx_Karplanter_fra_Artskart_FAB2018_til_Stein.xlsx)

[Forkastede_Karplanter_fra_Artskart_FAB2018_til_Stein.xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6916728/Forkastede_Karplanter_fra_Artskart_FAB2018_til_Stein.xlsx)

**Comment by steinho** [comment]
> Disse to filene inneholder alle observasjonene fra Artskart som ikke skal være med i standardutvalget på karplanter. Når en ekspert er inne i base-kartet på en viss art må den likevel kunne fjerne denne filtreringen (dvs. velge å bruke (noen av) disse observasjonene likevel).
> 

Det at man enten skal ekskludere eller ikke - ønsker jeg helst å unngå. Tenker det må bli enten eller - at man stoler på reidar - eller at vi ikke tar inn den listen.

Det skaper ennå en akse i systemet som potensielt bare får nye utfordringer - man har allerede muligheten til å ta bort eller legge til enkeltfunn (en akse vi må holde orden på til enhver tid), utvalgsmuligheter som man skal kunne endre på - og eksport av datasett - som må holde orden på om funnet kom fra artskart, eller kom og blitt fjernet , eller lagt til osv...)

**Comment by AneMarlene** [comment]
@steinho Da har jeg sjekket hva Reidar sa ang. disse, og jeg har ikke fått innvendinger fra karplantegjengen. Konklusjonen er at alle observasjonene i begge disse filene skal tas bort fra datagrunnlaget. :)

**Comment by steinho** [comment]
En foreløpig konklusjon er at en del av disse postene får jeg ikke match på lengre - ingen av de fra gbif... trolig fordi gbif er bygd på nytt siden sist og har renummerert poster...
De andre institusjonene har kanskje slettet sine - aner ikke...

![image](https://user-images.githubusercontent.com/3253353/152648284-06d6b896-6568-40d8-9354-cd2897a95739.png)


Til sammen får jeg ikke treff på 2050 av 15635 poster

SELECT distinct o.id into FAB4RejectedRecords
	--, [Institusj]
 --     ,[CatNr]
 --     ,[Datasett_Kode]
  FROM [ForkastedeNy] f  join Observation o on o.InstitutionCode = f.Institusj and o.CatalogNumber = f.CatNr and f.Datasett_Kode = o.NodeId

**Comment by AneMarlene** [comment]
@steinho Vet du hvilke poster du ikke får treff på av de andre institusjonene enn GBIF? Så kan jeg ta noen stikkprøver å se hva jeg finner ut.

**Comment by steinho** [comment]
[mangler treff.csv](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/8014630/mangler.treff.csv)

Disse (kun nøklene) - matcher ikke

**Comment by steinho** [comment]
Lukker denne nå - Vi lager en ny om ytterlige poster skalbort - har en enkelt tabell de skal inn i

**Comment by EveliinaP** [comment]
Jeg har sjekket filtrert data mot FAB4 data for en art (Abies concolor) som jeg fikk fra Ane. For denne art var det hvert fall ikke med obs som skulle vært filtrert.
