### ISSUE TITLE
Utbredelseshistorikk fra 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#400]
@steinho @svetlnaumova Her er det noe jeg ikke skjønner. Utbredelseshistorikk 2018 skal være et rent historisk objekt, og dermed ikke redigerbart. Hvordan kan det da ha blitt slik i testbasen for abies alba: 

![image](https://user-images.githubusercontent.com/58254444/151527063-ae05b144-8dfc-4f5d-a11f-a72e70147249.png)

Slik ser det ut i driftbasen (dette ser ut som det er korrekt visning fra 2018): 
![image](https://user-images.githubusercontent.com/58254444/151527128-1ecbf92a-93c3-4753-9a17-60e9a4a10cb1.png)

**Comment by steinho** [comment]
Mystisk - har ingen forklaring ... jeg legger ut en kopi fra drift - for å skje om det oppstår igjen.... vi kan ha tuklet det til midtveis i noe .... 

Ny kopi fra drift er ute nå - med siste patchinger

**Comment by AneMarlene** [comment]
@steinho Da lukker jeg denne nå, så får vi heller se på det en gang til om det oppstår på nytt
