### ISSUE TITLE
Artens status - Gjenoppstått raritet på årstall..

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#407]
Nå er dette med årstallet tilbake igjen på karplanten Abies alba. Jeg tør påstå at jeg ikke har rørt noe som skulle påvirka det årstallet. Er det mulig å finne ut hva som skjer her tro? JSON sa det ikke var noen endringer etter forrige lagring..

![image](https://user-images.githubusercontent.com/58254444/151803000-ba11f7a1-9ff4-4b91-af91-7985fe4db053.png)

**Comment by steinho** [comment]
Data fra fab3:
![image](https://user-images.githubusercontent.com/3253353/151963531-04ac16c4-94b0-4642-856b-3714a423a9ba.png)

**Comment by AneMarlene** [comment]
@steinho Skal tro hvorfor det da vises slik i fab3, og tidvis også slik i fab4 (selv om den av og til endrer seg...): 

![image](https://user-images.githubusercontent.com/58254444/152126364-b6880407-9fd4-4582-96ec-d358ef01596d.png)

**Comment by AneMarlene** [comment]
@steinho Nå har samme sak dukket opp på enda en karplante, Abies amabilis: 
![image](https://user-images.githubusercontent.com/58254444/152310719-1f7baaa7-3647-45fe-9157-ba49c02759f4.png)

**Comment by steinho** [comment]
AI - tror dette er en bug - terje la inn noe for #219
overførte utbredelsesområde til dette feltet......
ass.riskAssessment.yearFirstProductionOutdoors = areadata.AreaExtentOfOccurrence;

Kommenterte bort denne linja nå....
