### ISSUE TITLE
Artens status - kobling mot artsnavnebasen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#41]
For taksoner som er omfatta av vurderingen til et annet takson, skal ekspertene oppgi navnet på dette taksonet. Disse skrivefeltene skal være koblet opp mot artsnavnebasen: 

![image](https://user-images.githubusercontent.com/58254444/127970698-1c6f59b0-f09f-4ac6-86c0-9b32bca5f46a.png)

![image](https://user-images.githubusercontent.com/58254444/127970760-cb006cf5-c028-4010-a8b2-42fe28486068.png)

**Comment by steinho** [comment]
Hvilken fane hører dette til (moi not found)

**Comment by AneMarlene** [comment]
@steinho Moi, je found. C'est cette fane (og du må ha gjort følgende valg): 

![image](https://user-images.githubusercontent.com/58254444/135328136-bb866df0-ccc7-456c-930a-49baa2196906.png)

**Comment by AneMarlene** [comment]
@svetlnaumova , denne jobbet kanskje du med, men så trengte du hjelp?

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror at jeg fant ut av det. Den fungerer nå, selv om den ikke er helt fin, men stylingen kan vi ta senere. Det er også slik at det er bare en "beholder" for knyttede takson (dvs hvis du velger "vurderes sammen med et annet takson" og finner hornugle, og så bytter til "deler vurderinga til et annet takson", skal hornugle være i det nye feltet som åpner nederst). Tror du det kan skape trøbbel?

**Comment by AneMarlene** [comment]
Tror det går fint, men arten lagres ikke... hmm, åpner nytt issue på det :)
