### ISSUE TITLE
Naturtypefane: filtrering av sterkt endret hovedtyper

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#411]
Når man beregne "Påvirket areal i en «øvrig» naturtype (overføres til G-kriteriet)" må vi kunne filtrere vekk sterkt endret hovedtypene. Kodene for typer som skal ikke med i kriteria er gitt csv fil. Jeg fikk ikke kopiert tabellen med også navner fra pdf men mulig at @AneMarlene (?) har den for å kunne sjekke at de riktige typene bli tatt vekk
[sterkt_endret_hovedtyper.csv](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7979163/sterkt_endret_hovedtyper.csv)
Dette er del av #77 som jeg forstå har allerede blitt gjort?

**Comment by AneMarlene** [comment]
Det gjelder også C-kriteriet. Naturtypene som ikke skal gi utslag på C- og G-kriteriet skal være som følger: F9–F13, H4, L14–L17, O6+O7, T35–T45 og V11–V13.
