### ISSUE TITLE
Hva med Horisontscanning / full i drift nå?

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/Fremmedartsbase2023#412]
For andre enn admin ser det slik ut:
![image](https://user-images.githubusercontent.com/3253353/152111083-e17389c8-c930-48a3-bb1e-55c83bea702b.png)

Hva skal være tilgjengelig?

**Comment by AneMarlene** [comment]
@steinho Er vi fornøyd med hvordan det ser ut tror du? Andre enn admin har vel ikke tilgang til horisontskanninga, men det er nok greit nå tror jeg?!

**Comment by AneMarlene** [comment]
Jeg tenker vi sier oss fornøyd :)
