### ISSUE TITLE
Oppsummeringen - laste opp vedlegg

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#415]
Vi ønsker noen små endringer i tekst og plassering her (se skjermdump). 

Tekstendringer:
1. Du har lastet opp følgende filer til vurderingen:
2. Ønsker du å laste opp flere filer?

![image](https://user-images.githubusercontent.com/58254444/152125751-5d22e296-29e0-4e78-9354-3441b6deb64f.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har fikset, men dere ønsker kanskje å beholde originaltekst i nr 2 for vurderinger som ikke har opplastede filer ennå?

**Comment by AneMarlene** [comment]
@svetlnaumova god idé! I tillegg kan det kanskje i stedet for nr 1 stå "Du har ikke lastet opp noen filer til vurderingen". Men det er kanskje ikke så viktig egentlig... de skjønner at de ikke har lastet opp noen når lista er tom også :D
