### ISSUE TITLE
Horisontskanning - faner for risikovurdering er plutselig tilgjengelig i driftbasen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#416]
Hvis jeg er inne på en art under horisontskanning i driftbasen ser det plutselig slik ut: 

![image](https://user-images.githubusercontent.com/58254444/152152659-561299b1-f715-4341-866d-1b4de99c7979.png)

Om jeg trykker på en av fanene - får jeg også beskjed om at jeg har ulagrede endringer på vurderingen når jeg prøver å gå ut igjen. Dette uten å ha gjort noe. Slik ser JSON ut hvis jeg åpner fanen geografisk variasjon:

![image](https://user-images.githubusercontent.com/58254444/152152971-8852d728-8456-4215-bff2-2a7b48eb5410.png)

Åpner jeg invasjonspotensiale eller økologisk effekt dukker flere ala denne på C-kriteriet opp:
![image](https://user-images.githubusercontent.com/58254444/152153255-aa21ac8a-f187-431e-9027-7fd4d0d6ed51.png)

 Kan vi få låst disse fanene igjen?

**Comment by steinho** [comment]
Tror dette kan testes

**Comment by bugdriven** [comment]
Disse "auto" oppdateringene er litt vanskeligere å fike enn jeg trodde, for verdien her endres faktisk av å velge fane.

**Comment by AneMarlene** [comment]
@steinho @bugdriven - Jeg ser nå at de aktive fanene og lagringsbugen er knyttet til vurdering i 2018. Om jeg går inn på en vurdering under HS som er helt ny, er fanene låst og nada problemas. Om jeg går på en NR-art er fanene åpne og jeg får lagringsfeil om jeg åpner en av fanene (unntatt klimafanen) før jeg går ut av vurderingen.

**Comment by AneMarlene** [comment]
@bugdriven @steinho Lurer på om vi bare lukker denne inntil videre, så kan vi heller åpne den igjen når det blir mer aktuelt igjen (neste runde med horisontskanning).
