### ISSUE TITLE
Artens status - spørsmål 2

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#418]
Vi har besluttet å fjerne de to underspørsmålene på spørsmål to, slik at spm om takson-navn kommer med en gang ved svar "ja".

Vi bytter også ordlyd på hoved-spm:
1. Deler taksonet vurderinga med et annet takson?

![image](https://user-images.githubusercontent.com/58254444/152166291-86fc7be9-5078-4aa8-8202-cbe0c165c2d2.png)

Se også issue #417 ang. at dette spørmålet alltid skal ha skrivefelt. 

VIKTIG: Spørsmålet skal heller ikke lengre ha en effekt på videre flyt, vurderingskategori eller konklusjon på artens status. Alle som svarer "ja" skal nå videre til spørsmål 3 (og kan fortsatt ende opp med at arten skal risikovurderes).

**Comment by svetlnaumova** [comment]
@AneMarlene Jeg tror at jeg har fjernet all logikk som hørte til den og testet en del, men si ifra om du oppdager noe rart!

**Comment by AneMarlene** [comment]
@svetlnaumova Jeg finner foreløping ingenting rart :)
