### ISSUE TITLE
Naturtyper - endringer i ønsker for fritekstbokser

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#421]
Slik det er nå er det en tekstbokst synlig på G-kriteriet hele tiden, i tillegg til en logikk som gjør at hvis man sier at vurderingsgrunnlaget er fra utlandet (dok. eller obs.), så kommer det opp et tekstfelt på både F og G (dette kan gitt hele to tekstfelt på G). Nå ønsker vi kun ett tekstfelt på hver som er synlig hele tiden. Det er da viktig at det tekstfeltet som synes, er det samme som ev. tekst fra 2018 blir overført til. I 2018 var det imidlertid 2 felt, jeg er usikker på om noen hadde fylt ut i begge feltene.. sitkagran har hvertfall tekst i ett felt på F og ett på G (om du vil ha noen å se på). 

Her er slik det kan se ut nå: 
![image](https://user-images.githubusercontent.com/58254444/152344847-6185211f-835e-4d61-bb4a-35e2167229fe.png)

**Comment by svetlnaumova** [comment]
@AneMarlene hva skal stå i teksten over feltene nå? Bare "Beskriv eventuelle effekter på natur", uten "utlandet"?

**Comment by AneMarlene** [comment]
@svetlnaumova strålende forslag på tekst synes jeg. Kanskje kunne vi fjernet enda litt mer også, bare skrive: "Beskriv eventuelle effekter"
