### ISSUE TITLE
Utbredelse - migrering fra FAB3

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#422]
Nå er migreringen fra FAB3 borte på Regionvis utbredelse. F.eks. på Rosa rugosa ser det slik ut i 2018: 

![image](https://user-images.githubusercontent.com/58254444/152346205-366353f5-2f20-43d7-bdcc-6dfcfe96baae.png)

Og slik ut i fab4:
![image](https://user-images.githubusercontent.com/58254444/152346271-40a96d26-ebcb-4fb8-9281-3375650f33b8.png)

**Comment by steinho** [comment]
Ser ok ut nå? Etter jeg kopierte inn databasen fra drift.... kan ha blitt krøll på test....

**Comment by AneMarlene** [comment]
Yes, denne er ok. Jeg lukker.
