### ISSUE TITLE
Lagringsbug - relatert til artskartmodel

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#423]
Ny lagringsbug uten at man har gjort endringer har dukket opp: 

![image](https://user-images.githubusercontent.com/58254444/152348506-0203d2d1-4d67-4a8a-a457-ba0f14b6a578.png)

**Comment by steinho** [comment]
Ok . Jeg må patche vurderingene slik at de to artskartmodellene ligger der på forhånd.

Fant samtidig ett annet problem jeg ikke har forutsett - vi har endret litt på datamodellen - og det har blitt ordnet med migreringspatch - men denne koden er kun innom vurderinger som har en 2018 vurdering - ikke nye arter for 2023... Må gå over og sjekke at nødvendige endringer også skjer der...
