### ISSUE TITLE
Naturtyper - usikkerhet på F-kriteriet etter migrering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#424]
Et spørsmål angående migrering og/eller utregning av usikkerhet på F-kriteriet (og potensielt G-kriteriet?). 

Den ikke-marine invertebraten Finnmarkshops (regionalt fremmed) hadde F-kriteriet som utslagsgivende i 2018. Den skåret da 2 på F-kriteriet med usikkerhet ned mot 1. Ingen av de rødlistede naturtypene brukt i fab3 kan velges i fab4, og de vises dermed bare fram, og F-kriteriet må fylles ut på nytt. Likevel har usikkerheten på denne arten avhakning både på 1 og 2 når man går inn på den i fab4, _uten_ noen valgte naturtyper. Skal det være slik tro? 

![image](https://user-images.githubusercontent.com/58254444/152529109-eac737a8-33f4-40ad-9c5e-16f54eda131b.png)

**Comment by bugdriven** [comment]
@AneMarlene Dette er vel et resultat av at dere ønsker å beholde usikkerhetsavkryssinger fra 2018?

**Comment by AneMarlene** [comment]
@bugdriven , og da beholdes den også uten at dataen som ligger bak brukes i år (som her)? Hmm, kanskje jeg og @olgahil må tenkte over det.

**Comment by AneMarlene** [comment]
@bugdriven - har tatt en prat med Olga. Vi ønsker ikke at usikkerheten huskes i tilfeller hvor metode el. er endret slik at usikkerheten blir stående uten sammenheng. Det vil si at den ikke skal huskes på F-kriteriet.
