### ISSUE TITLE
Utbredelse -selvstendig reproduserende arter - Overføring av utbredelsesområde

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#426]
For selvstendig reproduserende arter (unntatt regionalt fremmed fisk), skal vi overføre utbredelsesområdet herfra:

![image](https://user-images.githubusercontent.com/58254444/152750511-a9610187-24d5-491f-a63a-4cf54e896add.png)

til hit:

![image](https://user-images.githubusercontent.com/58254444/152750577-4579e20d-b617-474e-9756-4cf282564afe.png)

**Comment by steinho** [comment]
Kom inn på gullsjakalen min nå...
![image](https://user-images.githubusercontent.com/3253353/152758775-dbfb002e-f975-4672-bb4a-636ebe1ed687.png)
