### ISSUE TITLE
Artens status - Hurra, nytt spørsmål! 👯 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#433]
Her kommer vi med enda en liten endring som gjelder spørsmål 2 på artens status. Der kommer det inn et nytt spørsmål **med** følger for konklusjonen og risikokategori. 

1. Navneendring. Spørsmålet skal nå hete "Vurderes taksonet sammen med et annet takson?" - Ellers er det ingen endringer i det som skjer når man svarer "ja" på denne.
2. Nytt spørsmål: "Vurderes taksonet på et høyere (artsnivå) eller lavere (underartsnivå) taksonomisk nivå?". Her er svaralternativene "ja" og "nei". Svarer de "ja" på denne, er konklusjonen at arten ikke skal risikovurderes, og arten får risikokategori NR. Ingen flere spørsmål stilles på fanen.

![image](https://user-images.githubusercontent.com/58254444/152810577-a1df11b5-d589-438d-9116-86889175eca4.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror denne er i orden nå, så det er bare å lukke hvis du ikke ser noen feil. Den nye spørsmålet kommer opp med en default check "Nei", er det farlig?

**Comment by AneMarlene** [comment]
@svetlnaumova det er greit. det er noen fra 2018 som default skulle hatt ja på denne. Det er de som tilhørte taxonIsEvaluatedInHigherRank under NotApplicable i 2018. Er dette en ok sak å føre på? Ev. for @steinho ? Alle utenom disse skal ha nei der.

**Comment by svetlnaumova** [comment]
@AneMarlene tror jeg skal få det til. Har du eksempler på arter som skal ha "ja" slik at jeg får teste?

**Comment by AneMarlene** [comment]
@svetlnaumova diskuterte det litt med Olga. Vi fant ut at det var mye hummer og kanari i den gruppa fra 2018, så bare la alle være "nei" likevel. Da lukker jeg denne :)
