### ISSUE TITLE
B-kriteriet - Migrering fra fab3

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#436]
Ved metoden "datasett med tid- og stedfestede observasjoner" migreres dataen til feil feit i fab4. 

Disse dataene fra fab3: 
![image](https://user-images.githubusercontent.com/58254444/152984399-2bf19b35-56c0-4647-a395-a53be31fecb4.png)

Skal til følgende felt i fab4 (ved metode chosenSpreadYearlyIncrease": "a", og bruk av feltene ExpansionSpeed, ExpansionLowerQ og ExpansionUpperQ):
![image](https://user-images.githubusercontent.com/58254444/152989726-d30552a4-0db7-4a6a-8288-e4f3c7bfdc88.png)

Og ikke til disse, som de feilaktig er migrert til nå (dette er felt for dørstokkarter, og heter Occurrences1Best, Occurrences1Low, Occurrences1High): 
![image](https://user-images.githubusercontent.com/58254444/152986812-daff1904-ec90-4f2f-9cf0-92168bd6acb4.png)

**Comment by steinho** [comment]
Denne kan sjekkes i test
