### ISSUE TITLE
Overføring av data D/E-kriteriet

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#443]
Overføring av data D/E-kriteriet
Eksempelart: Impatiens glandulifera (karplante) 2018

I tabellen fra 2018 er det seks avhakinger i kolonnen trua/sjeldne arter. Disse har ikke blitt overført til tabellen i 2023. Avhaking av dokumentasjon er heller ikke overført.
[Overføring av data D_E-kriteriet.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/8031692/Overforing.av.data.D_E-kriteriet.docx)

**Comment by steinho** [comment]
inkludert nøkkelart checkbox er ikke haket av - på data fra 2018

Vurderingsgrunnlag fra 2018: 
Gjelder doc norske forhold -> Vurderingsgrunnlag : skriftlig doc fra norge
dokumentert uten andre avhakinger -> Vurderingsgrunnlag : Skriftlig doc fra utlandet

![image](https://user-images.githubusercontent.com/3253353/153184787-5ceeac8f-92b8-4506-aa57-0ac80def64ed.png)
![image](https://user-images.githubusercontent.com/3253353/153184821-10445c57-5f7d-4a4f-97fd-18c7e0b590ad.png)

**Comment by steinho** [comment]
![image](https://user-images.githubusercontent.com/3253353/153185189-6d2515a6-375f-46a6-a33a-c128baec8c1e.png)
