### ISSUE TITLE
Migrering - A kriteriet 2018 - metode C

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/Fremmedartsbase2023#444]
Metode c) Rødlistekriterier  finnes ikke i 2023:

Sørge for at skår er tilgjengelig og vises i info teksten

![image](https://user-images.githubusercontent.com/3253353/153187032-dd5c7137-5195-4052-b4af-c01b432dd631.png)

**Comment by steinho** [comment]
@olgahil - kan straks testes - har lagt til ett ekstra felt for score og viser den kun hvis c) var brukt.....

**Comment by olgahil** [comment]
ok, flott

**Comment by olgahil** [comment]
Jeg har sjekket, men det står fortsatt "0" på A-kriteriet, f.eks. Abies balsamea

**Comment by steinho** [comment]
beklager - var ikke ute i test før nå - hadde ikke kjørt migreringen av data på nytt..
