### ISSUE TITLE
Artsinformasjon, kom til Fastlands-Norge fra

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#445]
Alternativene som kommer opp er ikke riktig for Fastlandsnorge med havområder. Der skal det stå Opprinnelsessted (utlandet) i stedet for Fastlands-Norge. Altså, det skal stå slik for vurderinger som gjelder Fastlands-Norge (slik det gjorde i 2018).

2018:
![image](https://user-images.githubusercontent.com/60972488/153190787-799c0ac9-f02b-4554-9dfc-f6a1d1ec1353.png)

**Comment by svetlnaumova** [comment]
@olgahil tror det er mer min oppgave enn Stein sin. Hvis jeg ikke husker feil, var det slik at det skulle stå Opprinnelsessted (utlandet) for "vanlige" arter og "Fastlands-Norge" for regional fremmede. Hvilken art var det du så på?

**Comment by olgahil** [comment]
Jeg så på Abies koreana. Og du husker riktig. Det skal også stå Fastlands-Norge for Svalbardartene, men det gjør det jo allerede. Jeg nevnte saken for Stein i dag og forsto det slik at han kunne fikse det, men han blir sikkert glad om du fikser :)

**Comment by steinho** [comment]
Kjempefint - Her var det ikke noe migreringsproblematikk  i tilegg? @olgahil

**Comment by svetlnaumova** [comment]
@olgahil er det greit å lukke den eller ser du noen migreringsfeil?

**Comment by olgahil** [comment]
Jeg testet 4-5 arter i går og fant ikke noen feil. Bare å lukke
