### ISSUE TITLE
Feil kobling mellom ja/nei og skjema, Spredningsveier

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#452]
Under fanen Spredningsveier står det nå:
![image](https://user-images.githubusercontent.com/60972488/153571265-963244c2-ad95-4eca-ba69-93783c26103f.png)

Der skal teksten endres til:

Spres arten utelukkende direkte til norsk natur (uten å gå veien om innendørs- eller produksjonsareal)?
o Ja
o Nei, arten spres til norsk natur kun/også via innendørs- eller produksjonsareal

**Comment by olgahil** [comment]
Her er det en liten feil:
Når du velger _ja_ så skal du gå direkte til _Introduksjon til natur_ og _Spredning i naturen_
Når du velger nei skal du gå til _innendørs- eller produksjonsareal._
Altså motsatt av slik det står nå.

**Comment by steinho** [comment]
@svetlnaumova snudde denne i #473 for noen dager siden .... jeg snur den tilbake....
