### ISSUE TITLE
Forskyving av tekst i Utbredelses i Norge, dørstokkarter

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#454]
Teksten må forskyves noen hakk nedover, som vist i figuren. Dette gjelder særlig Total forekomstareal 10 år etter....

![image](https://user-images.githubusercontent.com/60972488/153650832-77c098d9-80bd-4644-9ecd-d4a77a91dc53.png)

**Comment by svetlnaumova** [comment]
@olgahil hvilken art var det? Finner ingen dørstokkarter i testbasen.

**Comment by olgahil** [comment]
Ja, det var det da - jeg glemte å notere meg arten. Sier i fra om dette dukker opp igjen.

**Comment by svetlnaumova** [comment]
@olgahil jeg tror at denne er ordnet nå, men det var som sagt ikke mange dørstokkarter i testbasen, derfor fikk jeg nesten ikke testet. Jeg lukker den, men det er bare å åpne igjen hvis det viser seg at noe fremdeles ikke ser pent ut.
