### ISSUE TITLE
"Consent" skjerm under inlogging

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/Fremmedartsbase2023#46]
Man skal i følge GDPR egentlig godta en kopling mellom Autentiserings-tjenesten og Applikasjon.

@AneMarlene - hvordan vil dette bli mottatt - skal være aktivt nå

**Comment by AneMarlene** [comment]
Nå kommer jeg først til dette: 
![image](https://user-images.githubusercontent.com/58254444/128304106-1a6273f2-4f55-4432-98c3-390d1c2da750.png)

Og da jeg trykte "ja, godta" (eller noe lignende), så kom jeg rett inn. Ved neste innlogging, etter å ha lukket nettleseren og åpnet igjen, fungerte det som normalt. Dvs. jeg trengte ikke trykke på "oppdater" for å komme til inngangssiden lengre 👍 Da er vel alt som det skal være? :)

**Comment by steinho** [comment]
Vi velger å ta bort consent skjerm - forvirrer
