### ISSUE TITLE
Overføring fra HS-fane til Utbredelse i Norge -

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#462]
For dørstokkarter som kom via HS og som skåret 0 eller 1 på horisontskanningsens spørsmål om etableringspotensial skal 0 eller 1 overføres til feltet Occurences1Best: 

Karplanten Acer rubrum er et eks.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/58254444/153769133-c9f879b4-a020-4c6c-8235-89f5aac38ed0.png">

**Comment by steinho** [comment]
Tallet 0 eller 1 skal stå i Occurences1Best?

**Comment by AneMarlene** [comment]
ja, hvis de har svart 0 på etableringspotensialet - > 0 på Occurences1Best
1 på etableringspotensialet - > 1 på Occurences1Best
2 eller flere på etableringspotensialet gir ingen overføring til Occurences1Best

**Comment by steinho** [comment]
@AneMarlene kan testes

**Comment by AneMarlene** [comment]
@steinho Ser ut til å fungere i test, så da kan denne kjøres ut i drift. (Jeg sjekka en i drift i dag hvor det ikke fungerte, så regner med dette kun ligger i testbasen enda?!?)

**Comment by AneMarlene** [comment]
Mulig fiksen ikke er 100%? Ser i driftbasen at det er riktig på testarten skogfiol som skåret 0, og ingen overføring på  Corvus cornix, kråke, som også skåret 0.

**Comment by steinho** [comment]
Tja - på skogfial i json står dette:
![image](https://user-images.githubusercontent.com/3253353/154854849-6acea561-505a-4086-b65a-106a7f1bb9ac.png)

**Comment by steinho** [comment]
> Tja - på skogfial i json står dette: ![image](https://user-images.githubusercontent.com/3253353/154854849-6acea561-505a-4086-b65a-106a7f1bb9ac.png)

Her har @bugdriven gjort noen endringer - så det er ikke dette feltet som vises der - men noe avledet basert på denne formelen:
```
get AOO10yrBest() {
            const result =
                r.occurrences1Best === 0 && r.introductionsBest === 0
                ? 0
                : r.occurrences1Best === 0
                ? 4 * round(0.64 + 0.36 * r.introductionsBest)
                : 4 * round(r.occurrences1Best + Math.pow(r.introductionsBest,(r.occurrences1Best + 9)/10))
            //console.log("#AOO10yrBest " + r.occurrences1Best + "!" + r.introductionsBest + " result: " + result)
            return result
        },
```

For skogfiol er introductionsBest  = null ....
Slik jeg leser det 
- hvis begge er 0 - vises 0
og i dette tilfellet går det ikke bra fordi r.introductionsBest = null og da havner den på 4 * round(0.64 + 0.36 * r.introductionsBest) - som sikkert blir bananas

@bugdriven ?

**Comment by steinho** [comment]
Jeg konkluderer med at migreringen har ble riktig og som bestilt - og så må det gjøres noe i beregningen i frontend

**Comment by AneMarlene** [comment]
@steinho @bugdriven jeg _tror_ ikke koden Helge har lagt inn skal påvirke det som står i occurrences1Best. Den koden bestemmer hva som skal stå i feltet AOO10yrBest (en celle lengre ned på fanen). Så på meg virker det rart at en null i introductionsBest skal påvirke overføringen fra HS-fanen til occurrences1Best? Kan det skyldes noe annet, eller er jeg på bærtur nå?

**Comment by AneMarlene** [comment]
Jeg lukker denne. Den er nok som den skal være :)
