### ISSUE TITLE
Feilmelding - forekomstareal

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#466]
Jeg får opp feilmeldinger om at forekomstarealet ikke kan være 0, selv om alle felt for forekomstareal på utbredelsesfanen er > 0. I dette eksemplet (Abies concolor) er det valgt metode på B.-kriteriet som ikke bruker forekomstareal, så det kriteriet skulle ikke spilt inn. 

![image](https://user-images.githubusercontent.com/58254444/153884180-7090e010-8031-4339-a06e-8aef5b4d555e.png)

![image](https://user-images.githubusercontent.com/58254444/153884226-ff777e2a-cbae-46df-a53b-1311ac2a7b1d.png)

**Comment by svetlnaumova** [comment]
@AneMarlene den er nok ferdig nå som alle ikke-relevante feilmeldinger er fjernet?
