### ISSUE TITLE
B-kriteriet - en setning for mye i utmatingen for dørstokkarter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#471]
Setningen som er ringet rundt vet vi ikke hvor kommer fra, men vi tenker at den gjerne kan vises _hvis_ arten er selvstendig reproduserende & chosenSpreadYearlyIncrease == "b" & AOOfirstOccurenceLessThan10Years == "yes". 

Dette er derimot en dørstokkart, og her skal setningen bort: 
![image](https://user-images.githubusercontent.com/58254444/154075590-f1702d26-6e0b-40a6-8823-b49214a2122f.png)

**Comment by svetlnaumova** [comment]
@AneMarlene det var rart fordi den setningen hadde en id "BcritText.Doorknocker" i kodelisten. Men jeg husker ikke heller hvor den kom fra.
