### ISSUE TITLE
Økologisk effekt - oppdatere kategori på valgte rødlistevurderte arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#472]
Her trenger vi å oppdatere kategori på rødlistevurderte arter valgt i 2018. De kan ha endret seg fra LC og NT til en truet kategori eller omvendt i Rødlista 2021. Dette har betydning for kriterier. F.eks. på denne terrestriske invertebraten, hvor Ask har endra kategori til EN (dette eks. har ikke effekt på kriteriet som skal brukes, men andre kan ha det).

<img width="495" alt="image" src="https://user-images.githubusercontent.com/58254444/154262082-012ed993-97d9-4b3b-a0d0-71d0c58ae406.png">

**Comment by steinho** [comment]
@AneMarlene  Har endring av kategori betydning/utslag på andre data/kriterier?

**Comment by AneMarlene** [comment]
@steinho Det har utslag på D og E-kriteriet, og H og I-kriteriet. Så ja, det må også oppdateres under H- og I-kriteriet.

**Comment by steinho** [comment]
Har kjørt vask av kategori ut i drift (og test)

**Comment by AneMarlene** [comment]
@steinho Er denne vasken kjørt på alle kriteriene, D, E, H og I?

**Comment by steinho** [comment]
> @steinho Er denne vasken kjørt på alle kriteriene, D, E, H og I?

Nei. Som jeg nevnte i samtale med @olgahil . Vi har ingen kode for å beregne kriteriene på baksiden eller api-et. Disse blir beregnet kun når vurderingen åpnes i frontend - altså all kode for å beregne kategori og kriterie eksisterer kun i frontend. 
Vi antar at de skal innom alle vurderingene og at det da blir beregnet riktig - om de ikke endrer noe annet på vurderingen - vil de i disse tilfellene få beskjed om endring og advarsel om å lagre...

**Comment by AneMarlene** [comment]
@steinho mulig jeg ikke henger med, men prøver.. :) Jeg lurte på om _rødlistekategorien_ til de valgte rødlisteartene fra 2018 ble oppdatert til gjeldende rødlistekategori fra 2021 i tabellene under de fire kriteriene. Helt ok at skåren på selve kriteriet til _fremmedarten_ som vurderes først blir oppdatert i frontend når eksperten åpner vurderingen. :)

**Comment by AneMarlene** [comment]
Denne er rett på alle kriterier nå (sjekket på amerikahummer som påvirker hummer). Rødlistekategori på hummer var oppdatert. Jeg lukker.
