### ISSUE TITLE
Migrering - rullegardin i tabell for D og E-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#476]
Det har skjedd noe feil med migreringen for D- og E-kriteriet. Eks. kongekrabbe Paralithodes camtschaticus

Her har dokumenasjon fra norske forhold blitt til dokumentasjon fra utlandet: 

![image](https://user-images.githubusercontent.com/58254444/154643379-9182f4e0-b1b5-48a5-a6bc-233abe7e1c9b.png)

![image](https://user-images.githubusercontent.com/58254444/154643292-2ca312df-9074-43fb-b882-d3889e1853a8.png)

Riktig migrering for avhaking i _begge_ checkboksene "dokumentert" og "gjelder norske forhold" er: 
![image](https://user-images.githubusercontent.com/58254444/154643995-58ef458d-6192-42d8-bdfa-3e0d82ce678a.png)

**Comment by steinho** [comment]
@AneMarlene -  Henger sammen med det jeg gjorde for denne - #443 - jeg har sikkert misforstått dette.
Hvordan skal de tre avhakingene til høyre mappes om til fa4? Kanskje er det bare de to siste jeg skal ta hensyn til - men hvem -hvilken kombinasjon skal hvor...

**Comment by AneMarlene** [comment]
@steinho Ser ut som du hadde forstått rett i #443. Men det har blitt feil likevel.. Denne kommentaren er riktig (og den som gjelder norske forhold er den jeg omtaler i dette issuet): 
![image](https://user-images.githubusercontent.com/58254444/154907056-2db35e07-b8e1-4e5c-8e0b-30f99883ac74.png)

**Comment by AneMarlene** [comment]
Da virker denne rett - jeg lukker 👯
