### ISSUE TITLE
Artens status - varselsbug?

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#481]
På enkelte arter er det slik når man går inn på artens status. Altså at  det står en feilmelding om bytte av status uten at noen valg er gjort overhodet. F.eks. Testarten hund:

![image](https://user-images.githubusercontent.com/58254444/154678099-348b2aba-e524-4fa6-a921-1b56967679b4.png)

**Comment by svetlnaumova** [comment]
@bugdriven dette er fordi assessment.speciesStatus må ikke være null i reaction-funksjonen som sjekker endringen av alienSpeciesCategory, men jeg trenger litt hjelp med å forstå hvordan den testen skal skrives.

**Comment by svetlnaumova** [comment]
@AneMarlene varselet kommer ikke opp på vurderingen av hund eller noen andre som jeg har sett på. Jeg lukker denne, men det er bare å åpne igjen hvis det dukker opp.

**Comment by AneMarlene** [comment]
@svetlnaumova den dukka opp senest i går på en soppart i drift som ingen hadde gjort noen endringer på.. men jeg husker selvssagt ikke hvilken art det var.

**Comment by svetlnaumova** [comment]
@AneMarlene det er sannsynlig at versjonen som ligger i test er ikke dyttet ut i drift ennå. Hvis det er tilfelle, så skal det være rettet opp ved neste oppdatering av drift-versjonen.
