### ISSUE TITLE
Migrering - inngangsspørsmål på spredningsveier

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#482]
Inngangsspørsmålet under spredningsveier skal stå ubesvart for alle arter, unntatt de som hadde følgende avhaking i 2018. De skal ha forhåndsutfylt "no" på inngangsspørsmålet.  

Disse (eg. karplanten Abies mariesii):
![image](https://user-images.githubusercontent.com/58254444/154680427-25e2e552-0dc1-4908-914e-c09994385eea.png)

Skal ha dette: 
![image](https://user-images.githubusercontent.com/58254444/154680527-2be1747f-39e2-4b3d-a6c1-2b2b0be291ce.png)

Ellers kan det være slik; 
![image](https://user-images.githubusercontent.com/58254444/154681563-5bc465c7-b9f6-40e2-b8cb-16a7cba1078d.png)

**Comment by steinho** [comment]
m.a.o.: "indoorProduktion": null som standard,
de som på fab3 : ImportedToIndoorOrProductionArea == true - skal i fab 4 ha "indoorProduktion": "negative",

**Comment by AneMarlene** [comment]
@steinho Det var 100% rett ja - akkurat sånn vil vi ha det :)
