### ISSUE TITLE
Artskart zip-fil

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#484]
Er det mulig å fikse i "din ende" at punktum i datoer blir tolket på samme måte som "/", slik at vi slipper at enkelte celler vises som ####, eller er det noe man må gjøre lokalt på sin maskin? 

![image](https://user-images.githubusercontent.com/58254444/154699313-93595bc0-198b-4482-9590-59c6ec17ec3f.png)

**Comment by steinho** [comment]
Dette er egentlig en excel sak ... hvis du ser på csv fila i et rent tekst program - tipper jeg alle datoen følger en syntax ....?

Utfordringen er da om vi skal velge norsk cultureInfo eller noe annet - her er det vel ett mer engelsk format som fungerer fint internasjonalt - men mindre bra i norge...

**Comment by AneMarlene** [comment]
@steinho du har rett. Om jeg åpner i notepad så er den ok. Kan dermed lagre først i notepad, og så åpne i excel, så er den fin der også. Jeg lukker denne da:)
