### ISSUE TITLE
Artskart - Skrivefelt for begrunnelse når forekomster fjernes eller legges til

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#488]
Vi ønsker et skrivefelt under "Utbredelse" for selvstendig reproduserende arter som dukker opp _kun hvis_ eksperten har lagt til funn, fjernet funn og/eller brukt polygon i kartet. 

Her er bilde fra Rødlistebasen:
![image](https://user-images.githubusercontent.com/58254444/154954390-6431b083-a10d-4f5e-83bd-3fcf7ba873f1.png)

Vi ønsker feltet inn her: 
![image](https://user-images.githubusercontent.com/58254444/154956329-895296a4-9e12-4334-b6ad-cb67a390faa2.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror at denne er på plass nå. Bare å lukke hvis du ikke finner noen feil.
