### ISSUE TITLE
Usikkerhet på B-kriteriet - skal ikke være redigerbar

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#489]
Per nå er usikkerheten på B-kriteriet ved metoden "Anslått økning i forekomstareal" for selvstendig reproduserende arter redigerbar, og heter "angi skår og usikkerhet". Disse skal være utgrået (ikke redigerbare) og hete "Skår og usikkerhet oppsummert", uavhengig av om eksperten svarer "ja" eller "nei" på "inngangsspørsmålet". 

![image](https://user-images.githubusercontent.com/58254444/154982263-b8d6b640-cb95-404b-89ca-f1d19ea00686.png)

**Comment by bugdriven** [comment]
fixed
