### ISSUE TITLE
Oppsummeringen - Figur viser feil kategori ved bruk av rødlistekriterier på A-kriteriet i 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#49]
Da har jeg sett på et par arter hvor det ikke er gjort noen endringer av oss i år, men hvor figuren på oppsummeringen likevel ikke stemmer overens med kategori. F.eks. slik som dette:
![image](https://user-images.githubusercontent.com/58254444/128306470-5bd39325-fc66-4b91-9542-51aa9c0929f1.png)

Jeg har sjekket litt, og så vidt jeg kan se er dette relatert til at rødlistekriterier er utgått som estimeringsmetode. De artene jeg har sett mismatch på har A-kriteriet som utslagsgivende (men ikke i kombinasjon med C-kriteriet), og har brukt estimeringsmetode "rødlistekriterier" i 2018 . Det ser  slik ut inne på A-kriteriet for disse artene:

![image](https://user-images.githubusercontent.com/58254444/128309195-0667b6f4-52b1-485e-9f12-5d5ba1b7a5fb.png)

Hva blir løsningen for disse? Usikker på hvem av dere det er som tar dette, så jeg tagget dere begge :)

**Comment by AneMarlene** [comment]
@svetlnaumova @bugdriven dette var vi så vidt innom forrige møte. Issuet er her fortsatt, f.eks. på karplanten Abies nordmanniana, nordmannsedelgran. Jeg er usikker på om vi bare lar dette være, og godtar at matrisa nødvendigvis vil vise feil inntil nye valg er gjort på A og/eller B-kriteriet (ved bruk av utgåtte metoder på en av disse). I tilfelle kan vi lukke dette.

**Comment by bugdriven** [comment]
Går ut ifra at dette er riktig nå (etter alle endringer som er gjort på A og B kriteriet)
