### ISSUE TITLE
Inngangssiden - Filtre for ikke påbegynt, påbegynt og ferdigstilt - prosenter og antall

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#494]
Kan vi få inn prosenter og antall bak disse, ala det vi hadde under horisontskanningen? 

![image](https://user-images.githubusercontent.com/58254444/155275762-14cbe1d0-35ff-425c-81b4-321c30a0ce9c.png)

**Comment by steinho** [comment]
@svetlnaumova  - det ligger i søkeresultatet - likt som for hor-scan:
![image](https://user-images.githubusercontent.com/3253353/155281316-8e956d1d-5b39-42b3-bb30-db9b657fb220.png)
