### ISSUE TITLE
Naturtyper - data fra tidligere vurdering kan redigeres

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#495]
Jeg får til å redigere data fra tidligere vurdering her. Det må vi få skrudd av :) Eksempelart er fisken dvergmalle.

![image](https://user-images.githubusercontent.com/58254444/155285088-ed2d5e51-55bb-4698-baa9-c697c33ac831.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har fjernet redigeringsknappene fra tabeller med data fra tidligere vurderinger, men fikk ikke testet om dropdown-menyene er redigerbare eller ikke. Lukker den foreløpig, men det er bare å si ifra om denne ikke er helt ferdig ennå.
