### ISSUE TITLE
Artens status

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#5]

**Comment by olgahil** [comment]
[StatusH3 010221.docx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/5910439/StatusH3.010221.docx)

**Comment by AneMarlene** [comment]
@svetlnaumova Vi ønsker lagreknapp nederst på hver fane - slik som i rødlistebasen :) Tror det er avglemt i flere av forslagene.

**Comment by svetlnaumova** [comment]
@AneMarlene den er der nå, bare inaktiv foreløpig :)

**Comment by AneMarlene** [comment]
@svetlnaumova Da har vi gjort en liten endring. Det skal ikke lenger hete "produksjonsart", men "bruksart". Ergo, må navnet her endres:
![image](https://user-images.githubusercontent.com/58254444/120316568-dc07ed00-c2dd-11eb-97e5-07523aeed0e8.png)

**Comment by svetlnaumova** [comment]
Skal det byttes til "bruksart" også i filtreringen? Under "Ikke risikovurdert" er det en valgmulighet som heter "Tradisjonell produksjonsart".

**Comment by AneMarlene** [comment]
Ja, det var et godt spørsmål. i 2018 het det jo "produksjonsart", så kanskje er det rett å beholde den termen der, men igjen kan det være forvirrende... Her må vi få på @olgahil for en ekspertuttalelse.

**Comment by olgahil** [comment]
Hm, det var et godt spørsmål ja. I utgangspunktet så vil vi jo endre produksjonsart til bruksart alle steder, og det kan bli forvirrende å bruke produksjonsart i filtreringen. Da har vi plutselig to begrep med samme meningsinnhold. Er det mulig i filtreringen å skrive: bruksart (tidligere produksjonsart). Foreslår det så får vi heller endre etterpå.

**Comment by Hannemor** [comment]
Litt for å sjekke at dette funker fra meg, også (fikk epost-varsel om denne): Jeg tenker at man kanskje bør ta med begge termene for sikkerhets skyld? Samtidig er det jo produksjonsart og bruksart som er synonymer her; "tradisjonell" syfter jo på bruk fra år 1700, og det er ikke en del av definisjonen på bruksart så vidt jeg har forstått.

**Comment by Hannemor** [comment]
> Hm, det var et godt spørsmål ja. I utgangspunktet så vil vi jo endre produksjonsart til bruksart alle steder, og det kan bli forvirrende å bruke produksjonsart i filtreringen. Da har vi plutselig to begrep med samme meningsinnhold. Er det mulig i filtreringen å skrive: bruksart (tidligere produksjonsart). Foreslår det så får vi heller endre etterpå.

Det blir fort forvirrende uansett hva man bruker her, så jeg tenker det er en god idé å bruke begge begrepene slik du foreslår, men passe på at "forordet" tradisjonell ikke blir en del av definisjonen på produksjonsart/bruksart, men at det mer er en presisering av et subset av produksjons/bruksartene.

**Comment by AneMarlene** [comment]
Enig med Olga og Hannemor her ;) Og bra at du fikk epost-varsling, Hanne 👍

**Comment by AneMarlene** [comment]
@svetlnaumova Detalj: skrivefeltene på denne siden kan gjerne bli vesentlig mindre. Kanskje ikke større enn skrivefeltet jeg skriver i akkurat nå her inne på github :)

![image](https://user-images.githubusercontent.com/58254444/120751443-4a2ff800-c508-11eb-9b5f-aed98435f595.png)

**Comment by AneMarlene** [comment]
@svetlnaumova Ny detalj: Spørsmålet om arten er en bruksart skal opp på samme nivå som "Hvilken status har arten i Norge?" og lignende. Altså på "første nivå".

**Comment by AneMarlene** [comment]
@svetlana: Her kommer litt mer (Den nedereste "kommentaren" er av samme type som min forrige kommentar) : 

![image](https://user-images.githubusercontent.com/58254444/120752117-6d0edc00-c509-11eb-9a5d-625ef34c63ce.png)

**Comment by AneMarlene** [comment]
@svetlnaumova Her hadde det vært fint om alle boksene kom rett under hverandre (illustrert med oransje boks), samt at det skal stå "Usikkerhet" over de små avhakingsboksene (illustrert med blå krusseduller og piler) :D

![image](https://user-images.githubusercontent.com/58254444/120752817-91b78380-c50a-11eb-8a03-e1f6953b79aa.png)

**Comment by svetlnaumova** [comment]
> @svetlnaumova Detalj: skrivefeltene på denne siden kan gjerne bli vesentlig mindre. Kanskje ikke større enn skrivefeltet jeg skriver i akkurat nå her inne på github :)
> 
> ![image](https://user-images.githubusercontent.com/58254444/120751443-4a2ff800-c508-11eb-9b5f-aed98435f595.png)

Det er helt sikkert noe som henger igjen etter Rødlista, der var det noen av ekspertene som ønsket seg et større felt for kommentarer :) I fix.

**Comment by AneMarlene** [comment]
> > @svetlnaumova Detalj: skrivefeltene på denne siden kan gjerne bli vesentlig mindre. Kanskje ikke større enn skrivefeltet jeg skriver i akkurat nå her inne på github :)
> > ![image](https://user-images.githubusercontent.com/58254444/120751443-4a2ff800-c508-11eb-9b5f-aed98435f595.png)
> 
> Det er helt sikkert noe som henger igjen etter Rødlista, der var det noen av ekspertene som ønsket seg et større felt for kommentarer :) I fix.

Jepp, der var det behov for større felt noen plasser husker jeg ja :) Det blir det nok noen plasser i FAB også, men ikke i denne fanen tror jeg :)

**Comment by svetlnaumova** [comment]
> @svetlnaumova Her hadde det vært fint om alle boksene kom rett under hverandre (illustrert med oransje boks), samt at det skal stå "Usikkerhet" over de små avhakingsboksene (illustrert med blå krusseduller og piler) :D
> 
> ![image](https://user-images.githubusercontent.com/58254444/120752817-91b78380-c50a-11eb-8a03-e1f6953b79aa.png)

Hva med selve boksene - har de ok størrelse eller bør de være større / mindre?

**Comment by AneMarlene** [comment]
> > @svetlnaumova Her hadde det vært fint om alle boksene kom rett under hverandre (illustrert med oransje boks), samt at det skal stå "Usikkerhet" over de små avhakingsboksene (illustrert med blå krusseduller og piler) :D
> > ![image](https://user-images.githubusercontent.com/58254444/120752817-91b78380-c50a-11eb-8a03-e1f6953b79aa.png)
> 
> Hva med selve boksene - har de ok størrelse eller bør de være større / mindre?

De kan kanskje være litt mindre, da det bare skal stå et årstall i hver. Så om det er plass til å skrive 2020 (med bittelitt rom) er nok det bra nok :)

**Comment by AneMarlene** [comment]
@bugdriven I dokumentet som ligger her inne er det en god del kommentarer som forteller om logikk på siden. Enkelte spørsmål vises kun hvis tidligere spørsmål på fanen er besvart på en viss måte. Svarene som gis på denne fanen har også følger for andre faner. F.eks. om det hukes av for at arten er en bruksart, vil dette få følger for hvilke kategorier som vises inne på fanen spredningsveier.

**Comment by svetlnaumova** [comment]
Jeg lukker denne issuen fordi det ser ut for min del som funksjonaliteten i den fanen stemmer overens med det som er beskrevet i .docx-filen. Vi får åpne nye issuer hvis det er noen bugs eller noe som mangler der.

**Comment by AneMarlene** [comment]
Bare for å ha det skrevet her på Github: Denne fanen virker å fungere nøyaktig slik den skal, både for "vanlig fremmede" og for dørstokkarter. Den fungerer også slik den skal om vi krysser av for regionalt fremmed. Foreløpig ligger det ikke inne noen arter som på baksiden har egenskapen regionalt fremmed, så jeg har ikke fått testet om det vil få en effekt. Har heller ikke fått sjekket om valg på denne fanen får riktig følger før andre faner - det er enklest å teste inne på de andre fanene etter hvert som de er ferdige.
