### ISSUE TITLE
Utbredelsesfanen - feilmeldinger 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#503]
Feilmeldingene (alle) som gjelder forekomstareal har forsvunnet. 

*F.eks. her hvor jeg har satt lavt > best > høyt. Lavt kan ikke være større enn best, best kan ikke være større enn høyt (men alle tre kan være like). 

Enda viktigere, hvis tallet som settes inn ikke er delbart med 4 (som tallet 501 under her) må det komme opp ett varsel (det er ikke lov å bruke tall som ikke er delbare med 4 (dvs. gir et tall uten desimaler når det deles på 4, e.g. 8/4 = 2 er ok, men 9/4 = 2,25 er ikke ok). Det hadde vi tidligere også, men jeg tror vi skal endre ordlyden i varselet. F.eks. "Forekomstarealet er ikke gyldig. Det må være delbart med 4 (forekomstareal = antall forekomster x 4km^2)".

![image](https://user-images.githubusercontent.com/58254444/155944916-a6605607-4d02-4270-81d6-41e6f76c4cc2.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg tror at det er nå i orden, mulig at det kommer til og med alt for mange feilmeldinger.

**Comment by AneMarlene** [comment]
@svetlnaumova nå ble det rødt igjen om jeg skriver f.eks. 501 ja, men jeg tror feilmeldingene som gjelder disse feltene gjør seg best på siden (ikke under oppsummeringen). Kan de heller komme opp som rød tekst ved siden av feltene?

**Comment by AneMarlene** [comment]
Kanskje f.eks. her: 
![image](https://user-images.githubusercontent.com/58254444/155974985-d6143f50-0a68-49d9-a5c8-878b3120f3bc.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg har prøvd å legge dem til, men mistenker at det kan fort bli stygt hvis det kommer opp masse feilmeldinger samtidig. Jeg lar det være som det er foreløpig og tenker på bedre stylingen litt senere.

**Comment by svetlnaumova** [comment]
@AneMarlene jeg lukker den fordi den ser ut til å være fikset, men det er bare å åpne igjen hvis det kommer opp for mange eller for få feilmeldinger.

**Comment by AneMarlene** [comment]
@svetlnaumova ser ut som den fungerer nå ja :) Eneste vi kunne fått inn i tillegg er et varsel på AOOknown om det ikke er en multippel av 4, og varselsbeskjeden for disse kan endres til "Forekomstarealet er ikke gyldig. Det må være delbart med 4 (forekomstareal = antall forekomster x 4km^2)"
