### ISSUE TITLE
Spredningsveier - tekster fra 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#504]
Her må vi sørge for at teksten blir lesbar i sin helhet og ikke forsvinner ut av vinduet, som for denne algen, Aglaothamnion halliae:

![image](https://user-images.githubusercontent.com/58254444/155515673-58c1a7ab-3509-4b7b-9db0-f5095936700f.png)

Her er teksten i sin helhet i fab3: 

![image](https://user-images.githubusercontent.com/58254444/155515786-2783df0b-4573-4cb2-9a66-8412d0413119.png)

**Comment by svetlnaumova** [comment]
@AneMarlene nå kan det hende at det er noe som ikke ser helt fint ut (ekstra kommaer og lignende), men teksten burde i hvert fall vises i sin helhet.
