### ISSUE TITLE
JSON-fanen tilgjengelig for eksperter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#505]
Skal vi kanskje fjerne denne fanen for ekspertene, per nå er den synlig for alle? 

![image](https://user-images.githubusercontent.com/58254444/155522252-aadd4b43-160e-41a9-af54-d36e3d67a5e6.png)

**Comment by svetlnaumova** [comment]
@AneMarlene jeg får ikke testet selv fordi jeg ikke har en ekstern bruker, men tror at det burde være fikset nå.

**Comment by AneMarlene** [comment]
@svetlnaumova Huff, for en sløvpeis jeg er. Stein mente at det kanskje var ok/lurt at den fanen vistes for alle. Glemte helt å fjerne issuet. Men uansett, da gjør det egentlig ikke noe om fanen er synlig.. så da spørs det om den burde åpnes for alle igjen eller om vi nå bare skal la det være skjult og lukke issuet? (unnskyld rotet..)

**Comment by svetlnaumova** [comment]
@AneMarlene det er ikke vanskelig å få rulle det tilbake til hvordan det var, så bare gi beskjed hvis dere ønsker det. Men nå er det slik (hvis det ble som jeg tenkte) at alle kan se at JSON-fanen eksisterer, den bare er disabled for dem som ikke har ADB-epost. Så kanskje vi kan ha det slik foreløpig, og hvis noen av eksterne får behov for å se fanen, kan vi gi dem tilgang?
