### ISSUE TITLE
Utbredelse dørstokkarter - Utblanking vs. ikke utblanking av felt etter oppdateringer i driftbasen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#506]
For dørstokkarter skjer det av og til en delvis utblanking av felt på utbredelsesfanen etter oppdateringer i drift. Det som er ført inn på spm om antall forekomster og antall introduksjoner er ofte blanket ut, mens det som står i de ikke-redigerbare feltene (som utregnes basert på de redigerbare feltene) er ikke utblanket. Det virker likevel ikke å skje med alle arter. Her er 3 eksempler. 

Testedyr - skogranke, sist lagret av meg den 14.02, ble blanket ut etter oppdatering av drift i går kveld:
![image](https://user-images.githubusercontent.com/58254444/155523811-b0982491-8d00-4136-a3df-23301bc00ff3.png)
 
Limniske invertebrater - Cambarellus chapalanus, sist lagret av Stein Johnsen 23.02 - ser ut som den er blanket ut:
![image](https://user-images.githubusercontent.com/58254444/155523980-d42024c7-7173-444d-8ff9-c091efefda1e.png)

Limniske invertebrater - kinaullhåndskrabbe, sist lagret av Gaute Velle 23.02 - ble ikke blanket ut: 
![image](https://user-images.githubusercontent.com/58254444/155524254-88e108ed-154f-40e3-bf5d-213831b7b31c.png)

**Comment by steinho** [comment]
Tidlig i går til senere på dagen på Cambarellus chapalanus i drift 

![image](https://user-images.githubusercontent.com/3253353/155563259-ae47e247-7ad2-4245-bd13-b6b74442372d.png)

Mange som har gått fra ett tall til null..

![image](https://user-images.githubusercontent.com/3253353/155563603-48d45d12-0584-41d6-9d73-b168eba04706.png)

**Comment by steinho** [comment]
> Tidlig i går til senere på dagen på Cambarellus chapalanus i drift
> 
> ![image](https://user-images.githubusercontent.com/3253353/155563259-ae47e247-7ad2-4245-bd13-b6b74442372d.png)
> 
> Mange som har gått fra ett tall til null..
> 
> ![image](https://user-images.githubusercontent.com/3253353/155563603-48d45d12-0584-41d6-9d73-b168eba04706.png)

og endret denne: 
![image](https://user-images.githubusercontent.com/3253353/155564014-7918caa0-1d40-4f09-b89b-4f1837059689.png)
som er direkte knytt til hvilke felt som vises

**Comment by AneMarlene** [comment]
@bugdriven Dette vet du antagelig, men nevner et eks. likevel. Gikk inn på terrestrisk invertebrat Aedes aegypti og endret _kun_  tall i IntroductionsBest. 

JSON bekrefter:
![image](https://user-images.githubusercontent.com/58254444/155582354-95a0b210-2429-40c7-b0e4-ed8c429adf7f.png)

Jeg lagret, gikk ut av arten, refreshet og inn igjen, og feltene ser slik ut (de så også slik ut umiddelbart etter at jeg satte inn tallet 3, OG de ser slik ut etter å ha redigert Occurences1Best, Low og High og gjort disse feltene blanke igjen). 
![image](https://user-images.githubusercontent.com/58254444/155582684-30b737ce-f696-4020-bd0f-e2889623a951.png)

For the record: Nå har jeg lagret tall i alle celler på testarten min musespurv i drift, så kan jeg følge med om noen av de forsvinner etter en senere oppdatering av driftbasen.

**Comment by bugdriven** [comment]
Regner med at dette er fikset med den oppdaterte håndteringen av blanke felt. Lukker.
