### ISSUE TITLE
Utbredelse - dørstokkarter - justering av felt

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#509]
For dørstokkarter er de tre feltene knyttet til det andre spørsmålet mye lengre opp enn selve spørsmålet. Kunne vi fått flyttet disse feltene ned slik at de kom på linje med spørsmålet sitt? 

![image](https://user-images.githubusercontent.com/58254444/155973608-0628c6ac-ca05-4886-80e5-a28eb766e9f1.png)

**Comment by svetlnaumova** [comment]
@AneMarlene den burde være litt bedre nå, så hvis dere er fornøyde, kan den nok lukkes.

**Comment by AneMarlene** [comment]
@svetlnaumova Tror det har skjedd noe litt utilsiktet her, eller så forklarte jeg meg ganske dårlig?
![image](https://user-images.githubusercontent.com/58254444/156555939-7083f88a-fe1a-45a3-83da-8aa8408abf0c.png)

**Comment by svetlnaumova** [comment]
@AneMarlene hvilken art er det? Tror at jeg skjønte hva du mente, men noe gikk galt.
