### ISSUE TITLE
Oppsummeringen - Årsak til endring

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#51]
Avkrysning på årsak til endring bør kun være mulig om kategori i 2023 er en annen enn kategori i 2018. Dvs, ikke når de er like som i her: 

![image](https://user-images.githubusercontent.com/58254444/128349880-aa865f65-3efc-41d4-b85b-7985ace3afa4.png)

**Comment by svetlnaumova** [comment]
@AneMarlene Jeg tror at denne er i orden nå, men fant ingen arter som har byttet kategori - kunne du gi beskjed hvis du oppdager at noe ikke fungerer som det skal? Ellers tror jeg det er bare å lukke den :)
