### ISSUE TITLE
Taksonomisk sti mangler for noen arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#514]
Den taksonomiske stien mangler for enkelte arter. Hvorfor det tro? Dette kan nok skape litt krøll for ekspertgruppene som deler arter mellom seg basert på taksonomi.

F.eks. denne fuglen, Anser canagicus: 
![image](https://user-images.githubusercontent.com/58254444/156131661-5692dc50-0deb-4bfc-bc1b-8101bd01eb58.png)

**Comment by steinho** [comment]
Virker i orden for fugler nå
