### ISSUE TITLE
Bytte mellom faner - automatisk starte øverst på neste fane

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#532]
når man bytter mellom faner/underfaner i FAB, så havner man "der hvor man var" på forrige fane. Det er ønsket av eksperter å havne øverst på fanen man går inn på - uavhengig av hvor man var på forrige fane. 

Ett eks. Om jeg er her på Utbredelse i det jeg skal gå til Naturtyper:
![image](https://user-images.githubusercontent.com/58254444/157467960-3157bb98-e78a-41b2-b14c-de4958aaed9f.png)

...så havner jeg nå her på Naturtyper: 
![image](https://user-images.githubusercontent.com/58254444/157468054-e2ec7674-006b-4f46-acd9-ee4f099d59bf.png)

...men jeg ønsker altså å havne her:  
![image](https://user-images.githubusercontent.com/58254444/157468139-dd69b449-0ea1-4962-9ef2-9f3438a32c1e.png)

**Comment by svetlnaumova** [comment]
@AneMarlene denne henger sammen med issuet #467 som jeg har fikset nå, så begge ser ut til å være i orden.

**Comment by AneMarlene** [comment]
@svetlnaumova wow, du har så rett! Dette blir deilig å få ut i driftbasen 🤩
