### ISSUE TITLE
Regionalt fremmede fisk - regionvis utbredelse

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#534]
Det er et par ting som mangler for regionalt fremmede fisk under regionvis utbredelse: 

1. De trenger beskrivelser over kartene som for øvrige arter: 
![image](https://user-images.githubusercontent.com/58254444/157652128-4742db95-06ba-43cb-bd08-062552614267.png)

altså disse beskrivelsene:
![image](https://user-images.githubusercontent.com/58254444/157652185-bc9df93b-1a78-4190-99a7-b8321a10012f.png)

2. fargene i kartene (se skjermdumpene over) er ikke helt lik fargene for øvrige arter. De virker bleikere (!?), og bør endres til samme fargekoder som for øvrige arter. 

3. Beskrivelser og angivelser av fargekoder mangler - både ved visning av vannregioner og vannområder
![image](https://user-images.githubusercontent.com/58254444/157653046-db0cae4e-8f37-496b-9c50-00195e5f8ce7.png)
![image](https://user-images.githubusercontent.com/58254444/157653224-ffe0296d-c25a-4143-a162-0fd1acfdbb05.png)

Vi trenger å få inn dette både ved visning av vannregioner og vannområder: 
![image](https://user-images.githubusercontent.com/58254444/157652926-31090df8-a401-4e3f-93a4-16395e740c35.png)

**Comment by bugdriven** [comment]
Regner med at denne er ok
