### ISSUE TITLE
Filer til vurderingen - reagere på fila fra Artskart

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#538]
Får vi det til at denne beskjeden forsvinner når zip-fila fra Artskart dukker opp? 

![image](https://user-images.githubusercontent.com/58254444/157668771-3fcb9473-2a7f-4fcb-93f0-fce38927be7b.png)

**Comment by svetlnaumova** [comment]
@AneMarlene hvilken art kan jeg teste på? :)
