### ISSUE TITLE
spredningsveier - Rømning/forvilling disabled for arter som ikke går via innendørsanlegg/prod.areal

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#539]
Hovedkategorien "Rømning/forvilling" under Introduksjon til naturen ønsker vi å få disabled/grået ut for arter som svarer "ja" på inngangsspørsmålet.

![image](https://user-images.githubusercontent.com/58254444/157680685-e521ccd4-cb81-4875-97e8-462b78391c7c.png)

**Comment by svetlnaumova** [comment]
@AneMarlene er det ikke bedre å bare fjerne den fra menyen?

**Comment by svetlnaumova** [comment]
@AneMarlene da har jeg bare grået den ut, men si ifra hvis dere ønsker å fjerne/skjule den når den skal være disabled for å ikke skape forvirring.

**Comment by AneMarlene** [comment]
@svetlnaumova tusen takk - og nei, vi ønsket at den skulle være synlig slik at de kan tenke over om det var riktig å svare "ja" på inngangsspørsmålet ;)
