### ISSUE TITLE
Visning av underfaner

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#54]
Jeg lurer på om vi skulle gjort en liten endring på hvordan underfaner vises. Kanskje er det bare meg, men jeg synes det er litt vanskelig å se "raden" med underfanene (jeg blir alltid stående noen sekunder og lete etter de), og tror kanskje det handler om at bakgrunnen er hvit, slik som resten av nettside-bakgrunnen. Det jeg lurer på er derfor om vi kunne prøve at de dukket opp som en ekstra rad med grå bakgrunn (slik som bak hovedfanene), men at det nå skilles med en horisontal strek (f.eks. mørk grå strek - slik jeg har skriblet under), slik at det blir tydelig at vi har et nytt nivå. Jeg vet ikke om jeg har kommet opp med den beste løsningen, så her må du gjerne prøve noe annet, Svetlana, men det hadde muligens hjulpet om bakgrunnen ikke var helt hvit og uavgrenset (for sånne som meg). :) 

![image](https://user-images.githubusercontent.com/58254444/128476414-79b71656-7655-4537-9cb1-709422741eca.png)

btw, pekeren var over "Horisontskanning" akkurat i det jeg screenshottet, så ikke tenk på at den ser mørk ut...

**Comment by svetlnaumova** [comment]
Jeg tror at jeg har gjort en forbedring og derfor lukker issuen, men si gjerne ifra om du er misfornøyd!
