### ISSUE TITLE
Flytte vurdering over på nytt artsnavn - funksjonalitet mangler

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#540]
Tiden har kanskje kommet da det går å prioritere å få ferdig denne funksjonaliteten?

![image](https://user-images.githubusercontent.com/58254444/158154476-98a5dd19-389a-4607-a967-a4f861d80517.png)

**Comment by bugdriven** [comment]
fixed
