### ISSUE TITLE
Utbredelse - selvstendig reproduserende arter - varsler 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#546]
@svetlnaumova om du rekker det før du drar, følgende varsler som ikke allerede er der ønskes inn på utbredelsesfanen (kun det inni "" skal med i varslene): 

AOOtotalBest == 0 gir FEILMELDING "En selvstendig reproduserende art må ha et forekomstareal på minst 4_km²!"
AOOtotalBest < AOOknown gir FEILMELDING "Det beste anslaget på det totale nåværende forekomstarealet kan ikke være mindre enn det kjente!"
AOO50yrLow > AOO50yrBest gir FEILMELDING "Lavt anslag kan ikke være større enn beste anslag!"
AOO50yrHigh < AOO50yrBest gir FEILMELDING "Beste anslag kan ikke være større enn høyt anslag!"
AOO50yrBest < AOOtotalBest gir ADVARSEL "Er det korrekt at det er forventet en nedgang i artens forekomstareal i løpet av de neste 50&nbsp;år?"

**Comment by bugdriven** [comment]
done
