### ISSUE TITLE
Legg til ny art - fjern art knapp

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#55]
Hvis man skriver inn en art, og den allerede finnes i artslisten, eller man ser at man valgte feil art fra rullegardinen, så hadde det vært fint med et synlig kryss (eller noe) man kunne trykket på for å fjerne den.  Slik det er nå blir arten bare blå når man peker over den, og så blir den borte når man klikker, men tror det er mer intuitivt om det er en synlig "fjern meg" knapp? 

![image](https://user-images.githubusercontent.com/58254444/128477710-9e699678-99f0-499f-878b-a50a7e17cdbf.png)

**Comment by svetlnaumova** [comment]
Har laget noe som ligner på det du tegnet, så lukker issuen, men ser at den ikke er helt perfekt, så skal prøve å få den til å se litt bedre ut senere.
