### ISSUE TITLE
A-kriteriet - metode brukt i 2018

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#551]
Vi har fått tilbakemeldinger fra eksperter om at de ønsker at denne beskjeden skal vises hele tiden, også etter at ny metode er valgt. Kan vi få til det? Per nå forsvinner beskjeden når en metode er valgt. 

![image](https://user-images.githubusercontent.com/58254444/159636533-40d29eb1-e1ea-4ccd-a6e6-4b65c41bf6bc.png)

**Comment by bugdriven** [comment]
Det jeg kan gjøre med denne er å la teksten stå så lenge sesjonen med denne vurderingen er aktiv, altså helt til man går ut av vurderingen (selv om mann velger ny metode og lagrer)
Dvs. hvis eksperten lagrer ny metode og går ut - så vil ikke teksten vises neste gang vurderingen åpnes.
Dette skal være rimelig lett å implementere. 
Er dette et ok kompromiss?

**Comment by bugdriven** [comment]
@AneMarlene Glemte å referere deg i forrige kommentar

**Comment by AneMarlene** [comment]
@bugdriven - det er jo definitivt et langt steg på veien (tror jeg hvertfall), så dur på med det! :)
