### ISSUE TITLE
Navnevask karplanter 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#553]
Karplantekomiteen ønsker automatisk vask av alle navneendringer/synonymiseringer som ligger inne i artsnavnebasen (etter nye Lids).

**Comment by steinho** [comment]
Har kjørt en test på vask mot karplanter og karp svalbard i test....

**Comment by AneMarlene** [comment]
@steinho De ønsker at vi venter til Tiril er ferdig med navneendringene mot Lids før vi tar vasken i basen. Jeg tror det er lurt å gjøre som du sa at vi kjører hele FAB mot navnebasen slik at vi får en oppdatering på alle potensielle navneendringer

**Comment by AneMarlene** [comment]
![image](https://user-images.githubusercontent.com/58254444/167596789-e23f4550-480a-40bb-b493-7be0347cfbb9.png)

**Comment by AneMarlene** [comment]
![image](https://user-images.githubusercontent.com/58254444/167777447-b5deaa6e-376a-4f3e-a597-8bce79dc024f.png)
