### ISSUE TITLE
B-kriteriet selvstendig reproduserende arter - varsel

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#555]
Vi ønsker et varsel hvis perioden som velges er enten mindre enn 10 år (som på skjermdumpen), eller den er over 20 år. Varselet kan være likt i begge tilfeller og kan settes inn under tabellen (indikert med oransje i skjermdumpen).

Varselet: "Valgt periode (t2-t1) kan ikke overstige 20 år eller være mindre enn 10 år. Juster perioden."

![image](https://user-images.githubusercontent.com/58254444/160075164-2088a011-8298-4d58-ba2b-58f9c59e718b.png)

**Comment by bugdriven** [comment]
fixed
