### ISSUE TITLE
utbreldelseshistorikk fra 2018 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#59]
Her kommer et lite issue til på den fronten. 

1. Er det mulig å kun vise tabellen med tilhørende kart hvis de hadde lagt til noe i 2018? . For de som ikke hadde fylt inn noe historie, kunne vi kanskje bare hatt en liten tekst "Utbredelseshistorikk i Norge var ikke lagt til i 2018" (kanskje med en bedre formulering etterhvert...)

2. Det som er krysset bort her kan bort også for de som har lagt til historikk i 2018: 
![image](https://user-images.githubusercontent.com/58254444/128507484-6205b763-237b-49dd-afa0-48f4f2ed1aef.png)

**Comment by svetlnaumova** [comment]
@bugdriven Tabellen med historikken skal ikke vises hvis det ikke var noe data i 2018, men spreadHistory ser ut som den gjør i screenshoten. Kan du se på det?

![image](https://user-images.githubusercontent.com/43623201/132710205-f2173149-b76e-4d6c-bcdf-f6303e9341a0.png)

**Comment by svetlnaumova** [comment]
@AneMarlene ser ut som den er ferdig for min del - er det greit å lukke?

**Comment by AneMarlene** [comment]
Mulig det er mye arbeid for lite, men er det mulig å fylle inn på "Fylker" også? 
![image](https://user-images.githubusercontent.com/58254444/146504512-831ae1a0-58ae-489f-a620-b4bd95855b8b.png)

Slik er det for samme arten i FAB4 (karplanten Abies alba): 
![image](https://user-images.githubusercontent.com/58254444/146504758-f4def588-e6c3-473f-8f8c-625bedb8196f.png)

**Comment by svetlnaumova** [comment]
@AneMarlene er kartene fine nok nå eller er det noe mer som skal gjøres her?

**Comment by svetlnaumova** [comment]
@AneMarlene jeg lukker denne også hvis det ikke er noe mer å fikse her.
