### ISSUE TITLE
Dørstokkarter - null i forekomstareal, men likevel skår på A- og B-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#595]
Da har noen greid å fylle ut på "juster skår" på A-kriteriet og brukt B-kriteriet uten å ha fylt inn noe på forekomstareal på en dørstokkart. Jeg innser derfor at vi må skjule resultatet på A- og B-kriteriet og heller vise et varsel der i slike tilfeller. Varselet kan dukke opp der resultatteksten ellers ville stått på kriteriene. 

Varsel: "Informasjon om forekomstareal må legges inn under fanen Utbredelse før denne metoden kan brukes"

Eksempel på kromisten Phytophthora amnicola på A-kriteriet
<img width="682" alt="image" src="https://user-images.githubusercontent.com/58254444/165235669-daa0d499-3451-4386-a24d-67a64a7b30d2.png">

**Comment by bugdriven** [comment]
Opprettet nye feilmeldinger i errorDefinitions
