### ISSUE TITLE
Inngangsfanen (med artsliste)

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#6]
[Inngangsside_29.04.21GitHub_OH_AMM.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/6451511/Inngangsside_29.04.21GitHub_OH_AMM.pptx)

**Comment by AneMarlene** [comment]
@svetlnaumova : Denne fanen er en av de som må på plass først. Her er nok ikke fargevalg etc. helt som vi har tenkt, så ikke bry deg om de detaljene (tror jeg da).  Denne siden er også svært stor og kompleks med mange valg og filtre. Ikke nøl med å spørre :)

**Comment by svetlnaumova** [comment]
På side 1 står det "Legg til ny art" helt til venstre i menyen, mens på sider 2o g 3 er det "Velg vurdering" som er første fra venstre. Er det siste versjonen som er riktig? :)

**Comment by AneMarlene** [comment]
@svetlnaumova Jeg fikk ikke til å redigere inne på lysarket, så da ble det klipp og lim i stedet.. Der hvor jeg har satt inn en checkboks med en rød pil, skal filtreringen "Potensiell dørstokkart som ikke skal vurderes" inn :) Dette gjelder filtrering på nåværende vurdering. 

![image](https://user-images.githubusercontent.com/58254444/119505842-a6a75080-bd6d-11eb-8bf0-291f3c656c56.png

**Comment by svetlnaumova** [comment]
I filtreringen på artens status er det kanskje mer naturlig å gjøre om "Risikovurdert" og "Ikke risikovurdert" til radioknapper for de ikke kan være haket av samtidig?

**Comment by AneMarlene** [comment]
Det kommer litt an på oppsettet rent teknisk tror jeg.. For det kan f.eks. hende at eksperten ønsker å hake av "Dørstokkart" (under risikovurdert) og "Dørstokkart som ikke skal vurderes" (under ikke risikovurdert) samtidig. MEN det vil ikke være logisk å huke av på "Risikovurdert" og "Ikke risikovurdert" samtidig uten å gå på neste nivå for å velge ut noen underkategorier.  Gav det mening?

**Comment by bugdriven** [comment]
Jeg tenker at filtrering bør ut i egen isue, som ikke er 1.pri (filtreringen er jo ikke kritisk for hverken å teste basene eller å begynne å jobbe)

**Comment by olgahil** [comment]
Sant nok, og blir dette for krevende ut ifra den tida vi har må vi gå for en enklere løsning i filtreringen. Det er nok lurt å jobbe videre med de andre fanene for å få et overblikk. Mange av de er også veldig krevende og vi har bare tida og veien!

**Comment by AneMarlene** [comment]
@svetlnaumova "Per, Pål og Astrid" er bare eksempelnavn brukt for å illustrere at navnene på de som vurderer arter innad i en ekspertgruppe skal inn her: 
![image](https://user-images.githubusercontent.com/58254444/120750203-426f5400-c506-11eb-9f5e-aec80965c1cb.png)

Er det slikt du gjør, å få inn navnene på komitemedlemmene der, eller er det mer "back end"?

**Comment by AneMarlene** [comment]
To spørsmål: 
1. Helt generelt, er det mulig å  øke "innhakket", slik at det blir tydeligere at noen kategorier hører til under en hovedkategori? 
2. Der hvor det står "bruksart (tidligere produksjonsart)", så mangler ordet "tradisjonell". Det ble sikkert litt forvirrende det vi skrev angående dette, men det bør nok stå "Tradisjonell bruksart (tidligere tradisjonell produksjonsart)"

**Comment by AneMarlene** [comment]
@svetlnaumova Legg til ny art-siden virker helt super på dette stadiet med mine øyne 👍

**Comment by svetlnaumova** [comment]
> @svetlnaumova "Per, Pål og Astrid" er bare eksempelnavn brukt for å illustrere at navnene på de som vurderer arter innad i en ekspertgruppe skal inn her:
> ![image](https://user-images.githubusercontent.com/58254444/120750203-426f5400-c506-11eb-9f5e-aec80965c1cb.png)
> 
> Er det slikt du gjør, å få inn navnene på komitemedlemmene der, eller er det mer "back end"?

Jeg kan legge til funksjonalitet (f.eks. menyen) for at brukere kunne gjøre et valg, men selve listen av medlemmer i ekspertgrupper legges på baksiden og det ser ut for meg som den mangler foreløpig (under "Brukere" på administrasjonssiden ser jeg bare en tom liste). Mulig den bare er gjemt et sted, men foreløpig tror jeg det kan stå eksempelnavn der :)

**Comment by svetlnaumova** [comment]
@AneMarlene Og nå har jeg lagt merke til at på administrasjonssiden står det "Ekspertgruppe", mens på "Legg til ny art" - "Ekspertkomité". Det burde kanskje være samme begrepet overalt?

**Comment by svetlnaumova** [comment]
> To spørsmål:
> 
> 1. Helt generelt, er det mulig å  øke "innhakket", slik at det blir tydeligere at noen kategorier hører til under en hovedkategori?
> 2. Der hvor det står "bruksart (tidligere produksjonsart)", så mangler ordet "tradisjonell". Det ble sikkert litt forvirrende det vi skrev angående dette, men det bør nok stå "Tradisjonell bruksart (før: Tradisjonell produksjonsart)" eller noe slikt. Det blir kanskje veldig langt?
>    ![image](https://user-images.githubusercontent.com/58254444/120750916-71d29080-c507-11eb-8b9c-7c1a3e3febd9.png)

Det blir mye tekst ja, men det går an å legge til "break-line" slik at linjen ikke blir for lang. Skal skyve nederste checkboksene litt til høyre :)

**Comment by AneMarlene** [comment]
> @AneMarlene Og nå har jeg lagt merke til at på administrasjonssiden står det "Ekspertgruppe", mens på "Legg til ny art" - "Ekspertkomité". Det burde kanskje være samme begrepet overalt?

Det har du helt rett i! Her bør det stå "Ekspertkomité" overalt :)

**Comment by steinho** [comment]
@olgahil @AneMarlene - noe som står igjen her...? Eller kan den lukkes?
