### ISSUE TITLE
Utbredelse i Norge - skrivefelt for årstall  - selvstendig reproduserende arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#62]
Vi trenger et skrivefelt for årstall (se oransje tekst på bildet). Jeg tror plasseringen må bli mer mellom forekomstareal i dag og forekomstareal om 50 år for at det skal se ryddigere ut. Årstallene er knyttet til forekomstareal i dag. 
![image](https://user-images.githubusercontent.com/58254444/128998348-fbcc19f9-df0f-47bd-bf15-b312ad06218a.png)

Vi ønsker at årstallene skal overføres fra filtrene som er brukt i Artskart-løsningen i basen (om de bruker den, ellers må eksperten få legge inn årstallene manuelt). Altså, at disse feltene overføres inn (dette er screenshot fra rødlistebasen): 
![image](https://user-images.githubusercontent.com/58254444/128998796-17b926eb-38b2-4965-89af-a48db3f2b534.png)

Det er disse to årstallene som videre skal overføres til B-kriteriet for selvstendig reproduserende arter. Både i tabell og i tekst. 

Med det samme jeg snakker om nye skrivefelt, så har jeg og Olga lurt på om det kanskje blir estetisk penere om alle slike skrivefelt har rette kanter (ikke avrundede). Er det en enkel sak å endre?

**Comment by AneMarlene** [comment]
vi prøver å ha det jeg har skrevet inn med oransje helt øverst i stedet for i midten. Altså, at årstallene/perioden kommer før kjent forekomstareal i dag :)

**Comment by svetlnaumova** [comment]
Skal fikse rette kanter straks - det er kanskje lurt å gjøre dem rette på knapper også slik at alt ser likt ut?
