### ISSUE TITLE
Artskart.zip - CSV-fila mangler kobling mot polygon. 

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#629]
Når funn er ekskludert vha. polygon, dukker de opp i zip-fila som "included". De skal være "removed".

**Comment by AneMarlene** [comment]
@steinho Eksempel karplanten abies alba: 
![image](https://user-images.githubusercontent.com/58254444/174017798-2908a888-1acd-4959-b052-2f02b5b24410.png)

Her er toppen av observations-fila (den fortsetter med kun "incuded" hele veien): 
![image](https://user-images.githubusercontent.com/58254444/174017989-d651c01c-d106-4e12-ac27-8d324cf4a542.png)

**Comment by steinho** [comment]
Ok. Enten timeout på å lage ny datafil og den man får er en gammel - eller en bug på tagging i tilfelle polygon (slik jeg husker koden uten å ha sett på den - virker det litt rart - men ser på den i morgen)

**Comment by AneMarlene** [comment]
Ok. Jeg har gått ut av arten og refresha flere ganger før jeg åpna .zip-fila (i tilfelle det bare skulle gå treigt..), men kan teste på en art til i tilfelle den bare har hengt seg.
