### ISSUE TITLE
Legg til ny art - får beskjed om at arter allerede er i listen

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#63]
Når jeg søker opp en art for å legge til, får jeg beskjed om at arten allerede finnes i listen. Dette gjelder uavhengig av om den fantes i Fremmedartslista 2018 eller ikke:

![image](https://user-images.githubusercontent.com/58254444/129033503-0c754b02-5770-477d-b800-807453761f57.png)

**Comment by AneMarlene** [comment]
Denne må på plass før horisontskanningen starter. @svetlnaumova tror jeg har spurt om det før, men er dette noe du kan gjøre?

**Comment by svetlnaumova** [comment]
Akkurat denne feilmeldingen om at arten allerede finnes i listen er nå borte, men man får uansett en feilmelding når man trykker på "Legg til ny art" - dette er nok noe på baksiden. @steinho kan kanskje hjelpe med det?

**Comment by AneMarlene** [comment]
Ja, nå er det slik hos meg også. Jeg er både leder og har skriverrettigheter til komiteen jeg prøver å legge til en art på, men får feilmelding på lagring: 

![image](https://user-images.githubusercontent.com/58254444/134646820-8cac4bb6-a2fb-4bde-8a93-85f36ea16c34.png)

**Comment by steinho** [comment]
@svetlnaumova og @bugdriven : formålet med denne ble litt omdefinert. Den fyller nå også muligheten til å flytte en vurdering fra full risikovurdering til fra horisonscan (hvis den allerede eksisterer) og opprette blank vurdering for arten hvis den ikke eksisterer for ekspertgruppen. Og i øyeblikket ikke noen test i klienten på hvilke av dem det kommer til å bli....

**Comment by AneMarlene** [comment]
@steinho den nye muligheten fungerer ikke i testbasen enda. Er det fordi den ikke er kjørt ut, eller har det skjedd noe muffins på veien?
