### ISSUE TITLE
Naturtyper - kartleggingsenheter legges til i tabellen som hovedtype

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#630]
Hvis jeg prøver å legge til en kartleggingsenhet i lista, så dukker den opp i tabellen som hovedtype: 

F.eks. blir dette valget i lista:
![image](https://user-images.githubusercontent.com/58254444/174025535-8e04f797-c6de-4d75-8988-58081b4fdf7d.png)

Til dette i tabellen: 
![image](https://user-images.githubusercontent.com/58254444/174025686-5c22045d-f894-4714-893c-a05003839872.png)

**Comment by bugdriven** [comment]
Fixed
