### ISSUE TITLE
Naturtyper - grunntyper registreres som hovedtyper

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#631]
Under følgende naturtyper blir grunntyper ignorert i tabellen. De legges inn i tabellen som hovedtyper: 

[listen oppdateres fortløpende]
- Marine vannmasser (alle)
- Saltvannsbunnsystemer (alle)
- Limniske systemer: 
![image](https://user-images.githubusercontent.com/58254444/174255736-bc48a8d9-6911-467f-bc2a-bb52090c5b64.png)

**Comment by bugdriven** [comment]
Fixed
