### ISSUE TITLE
Dørstokkarter - negativ ekspansjonshastighet på B-kriteriet

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#645]
På B-kriteriet **for dørstokkarter** (ikke selvstendig reproduserende arter) ønsker vi at ev. negative ekspansjonshastigheter skal vises som 0 m/år i teksten på kriteriet. Som f.eks. for fuglen hyrdestær: 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/58254444/182137453-34c5b762-da99-4287-a892-a0d96ff07da8.png">

**Comment by bugdriven** [comment]
Fixed
