### ISSUE TITLE
Horisontskanningfanen

### ISSUE THREAD

**Issue by olgahil** [Artsdatabanken/Fremmedartsbase2023#7]
[Horisontskanning_020221.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/5910515/Horisontskanning_020221.pptx)

**Comment by svetlnaumova** [comment]
Den tror jeg er på plass nå inkludert logikken. Ønsker dere at det kommer opp en beskjed / feilmelding hvis man ikke har valgt noe under etableringspotensial eller økologisk effekt, men prøver å gå videre?

**Comment by olgahil** [comment]
Ja, det funker. Så bra :)
Kanskje legge til følgende bak setningen til slutt sånn at det står:
Arten skal risikovurderes som dørstokkart. Gå videre til Artens status

**Comment by olgahil** [comment]
Ja, det høres lurt ut med en feilmelding. Foreslår følgende setning:

Før du går videre må du gjør valg for artens etableringspotensial og økologiske effekt

**Comment by olgahil** [comment]
En ting til:
Jeg ser at denne kommentaren kommer opp uten at noe er valgt:
"Arten faller utenfor avgrensningen og skal ikke risikovurderes som dørstokkart".
Det hadde vært fint om den ikke kom opp, før etter at noe er valgt (og dette er svaret)

**Comment by svetlnaumova** [comment]
Ja, det er nettopp derfor jeg lurte på om det burde stå noe annet når man ikke har gjort et valg :)

**Comment by olgahil** [comment]
Ja, nå skjønner jeg :)

I begge de to skrivefeltet bør det stå: Utfyllende informasjon 
Teksten kan gjerne plasseres øverst til venstre i skrivefeltet. Jeg er usikker på hvor mange linjer som skal være synlige i skrivefeltet. Veldig bra med skrollemulighet i skrivefeltet, men kanskje 3 linjer kan være synlig, ikke bare 1? Her har vi god plass i alle fall.

**Comment by svetlnaumova** [comment]
Ja, enig - ser at skrivefeltene er litt for små og vurderte å gjøre noe med det.

**Comment by svetlnaumova** [comment]
Nå er det kanskje et dumt spørsmål, men skal "Gå videre til Artens status" stå der selv om arten ikke skal risikovurderes som dørstokkart? Den kan jo vurderes som noe annet?

**Comment by olgahil** [comment]
At de to boksene Etableringspotensial og Økologisk effekt sto ved siden av hverandre i powerpointarket vi laget, var nok mer styrt av formatet på powerpointen enn av noe annet. Jeg kan i alle fall ikke huske at noen av oss argumenterte for at de skulle stå ved siden av hverandre. I de andre fanene er bokser plassert under hverandre og jeg tror det er best og være konsekvent og gjøre det samme i alle fanene. Hvis det ikke er for mye jobb å endre kan du plassere økologisk effekt under etableringspotensial så ser vi hvordan det blir.

**Comment by olgahil** [comment]
"Gå videre til Arten status"
Det var et veldig godt spørsmål. For det kan faktisk tenkes at den skal risikovurderes som noe annet. Det burde stå bare: 

"Arten skal risikovurderes. Gå videre til Artens status".

"Arten faller utenfor avgrensningen og skal ikke risikovurderes".

**Comment by svetlnaumova** [comment]
Synes at den ser ganske ok ut, så jeg lukker issuen - bare å åpne igjen eller gi beskjed hvis noe ikke fungerer som det skal her.
