### ISSUE TITLE
Issue i taksonomiske grupper i filteret

### ISSUE THREAD

**Issue by tanjakofodpetersen** [Artsdatabanken/Fremmedartsbase2023#708]
Helene fant et issue filteret på artsgruppe (noe som jeg har surret i).
Gruppen Maxillopoda under Krepsdyr i ikke anerkjent i navnebasen. De artene som skulle ha ligget der hører til under hoppekreps (Copepoda) og Rankefortinger (Thecostraca/Cirripedia).
I tillegg bør havedderkopper vel teknisk sett legges inn under krepsdyr.

Vedlagt fil med oversikt over artene som er påvirket
[TaksonomiTrøbbel.csv](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/10793393/TaksonomiTrobbel.csv)

**Comment by AneMarlene** [comment]
denne skulle ligget under FAL og ikke FAB. Lukker den derfor her.
