### ISSUE TITLE
Utbredelse - regionalt fremmede arter

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#72]
For regionalt fremmede arter vil bolken med "Fylkesvis utbredelse" både hete noe annet, og ha andre kart og annen tabell enn for øvrige arter. Et utkast på hvordan dette blir seende ut på fanen (med gamle fylkeskart som bilde) er her: 

[FAB - kart - regionalt fremmede arter.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7021505/FAB.-.kart.-.regionalt.fremmede.arter.pptx)

Her er det helt sikkert flere ting som kanskje ikke er landet/optimalisert. Så bare spør. Blant annet må man lande avmerking i kartet. Her blir det jo to nivå å merke av på (vannregion vs vannområde). Hvordan løse dette i praksis?

**Comment by olsoybakk** [comment]
@AneMarlene Hva avgjør at vi skal vise vannområder i kartet? Ligger det i modellen, eller skal brukeren velge det?

**Comment by AneMarlene** [comment]
@olsoybakk Slik vi har tenkt det, er det artsnavet som avgjør det. Altså, for komiteen Fisker er det 16 artsnavn som er regionalt fremmede. Er det mulig å sette en if-setning på det? Eller om det er andre kommandoer som eventuelt egner seg bedre?!Her er lista med artsnavnene: 

[Regionalt fremmede fisk - artsliste.xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7159334/Regionalt.fremmede.fisk.-.artsliste.xlsx)

**Comment by AneMarlene** [comment]
Jeg har for så vidt ikke fundert over om fiske-komiteen kunne finne på å ønske å vise vannområder for øvrige fremmede fisker også...  Tror jeg må ta en liten prat med Olga. ;)

**Comment by AneMarlene** [comment]
@olsoybakk Vi lander på at i artskart i basen er det kun for regionalt fremmede fisk det er aktuelt å vise vannområder. Får du også til å legge inn vannregioner der? Når det kommer til "fylkeskartene" lengre ned på fanen derimot, hadde det beste vært om alle fisker fikk opp vannregioner og vannområder i stedet for fylker. :)

**Comment by olsoybakk** [comment]
Rødliste har 5 nivå:
![image](https://user-images.githubusercontent.com/10737686/136002304-83328548-f86f-4795-a24b-b1027a60ff08.png)

Nå skal det vel være 3 nivå?
![image](https://user-images.githubusercontent.com/10737686/136002378-caf8dece-abfe-4982-a46f-cc00d7f0c0bd.png)

**Comment by olsoybakk** [comment]
@AneMarlene Nå har dere 3 regionkart og sjekkbokser i tabellen. Funker dette for dere?

**Comment by steinho** [comment]
Mener denne er i boks
