### ISSUE TITLE
Onchocleidus sp. mangler scientificNameFormatted

### ISSUE THREAD

**Issue by matssa** [Artsdatabanken/Fremmedartsbase2023#739]
I fremmedartslista mangler en vurdering formatert vitenskapelig navn: Onchocleidus sp.
Det gjør at denne flatormen mangler kursiv i epitetet. 
![image](https://github.com/Artsdatabanken/Fremmedartsbase2023/assets/15391193/1a7b82ed-35e5-4148-97aa-91d6dc70e19f)

**Comment by AneMarlene** [comment]
Denne er fikset, så jeg lukker.
