### ISSUE TITLE
Naturtypefane: import av truede eller sjeldne naturtyper fra 2018.

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#74]
Per i dag ligger det gamle data av truede naturtype i naturtypefanen. Dette skal byttes til det ny som er hentet fra rødlista naturtyper eksport med filtering av truete naturtyper og NT med kriteria B (sjeldne). Dette er excel skjema som legges under her i issue.
- [ ] Laste inn data 
- [ ] Gruppere per "tema" slik som er gjort i rødliste naturtyper nettsider. (https://www.artsdatabanken.no/rodlistefornaturtyper) 
- [ ] Under hvert tema listes det opp  naturtyper som da kan velges og ekstra informasjon om tidshorisont osv. kan gis. 

Se også powerpoint lysark for issue.

**Comment by EveliinaP** [comment]
@AneMarlene skal finne ut hvis det er behov for videre filtrering vekk av "landformer"

**Comment by EveliinaP** [comment]
Landformer som er truete skal være med og skal ikke filtreres vekk fra liste. Nå er dette avklart og dette kan jobbes videre med.

**Comment by EveliinaP** [comment]
[Truede eller sjeldne naturtyper.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7487439/Truede.eller.sjeldne.naturtyper.pptx)

**Comment by EveliinaP** [comment]
[Truet og sjeldne naturtyper2018.xlsx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7487440/Truet.og.sjeldne.naturtyper2018.xlsx)
Liste av truede og sjelde naturtyper som er hentet som eksport fra rødliste 2018

**Comment by EveliinaP** [comment]
- Typene arrangeres under temaer (pilen peker til side og når den er valgt da ned. 
- To av temanavner må gis nytt navn: 
          Svalbard -> Svalbard terrestrisk 
          Marint gruntvann -> Svalbard, kystvann
-  Typene vises med "kortnavn" fra eksport fil og hvilke rødliste kategori de ha. 
- Når en har valgt en type så skal det komme opp videre valg box der man velger tidshorisont, kolonisert areal % osv. likt som i noen andre plasser (se pp fil som jeg delt før).
- Mulig vi skal vise fram noe andre koder også om hver type men jeg skal finne ut hva vi ønsker å vise. 
![truedeNaturtyper_presentasjon1](https://user-images.githubusercontent.com/25793207/142993778-07dbcd82-f608-425a-85b2-02468fcee343.png)

**Comment by svetlnaumova** [comment]
@EveliinaP er det rekkefølgen av typene i screenshoten din som gjelder eller må de sorteres alfabetisk (som de gjør nå)?

**Comment by EveliinaP** [comment]
Alfabetisk er bra det. Kunne du byttet typene slik at alle vises under hver andre? Nå er det noen som er ved siden av hver andre. Og så de kodene er litt for komplisert å vise slik de er nå. Vi kan diskutere med @AneMarlene  hvordan vi skal vise dem.

**Comment by svetlnaumova** [comment]
Ja, ser at det er litt krøll med visningen av undernivåer, men det skal jeg fikse.

**Comment by EveliinaP** [comment]
Lurer på om dette er ferdig nå? Skal vi stenge issue @svetlnaumova?

**Comment by svetlnaumova** [comment]
Tror at det fungerer som det skal. Ser at det trenges små endringer i tabellen med naturtyper, men det er vel en annen sak?
