### ISSUE TITLE
Naturtypefane: import av data om "øvrige" naturtyper

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#75]
- [x] Importere data fra natursystem. Data kan hentes fra https://nin-kode-api.artsdatabanken.no/swagger/index.html,  get: koder/allekoder. Sterkt endret naturtypene bli med her men er ikke med i beregning av kriterier. 
- [x] Gruppere data hierarkisk under hovedtypegrupper -> hovedtyper ->kartleggingsenheter (1:5000) -> grunntyper. Notere at det er noen grunntyper som er ikke med i kartleggingsenheter og disse kan listes under kartleggingsenheter.
- [x] Ekspertene skal da kunne velge naturtyper i de tre forskjellige nivåer (hovedtyper, kartleggingsenheter eller/og grunntyper)

**Comment by EveliinaP** [comment]
Obs. Der tilgjengelig brukes det kartleggingsenheter 1: 5000 og demmes koder, ikke grunntyper og demmes koder.

**Comment by EveliinaP** [comment]
[Forslag for regional naturvariasjon.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7136771/Forslag.for.regional.naturvariasjon.pptx)

**Comment by EveliinaP** [comment]
Det har vært videre diskusjon med Hanno om vi skulle bruke kartleggingsenheter (1:5000) eller grunntyper. Det som vi tenker nå er at hvis det bli gjennomførbart innen tidsfrist så inkludere vi begge slik at man gå fra hovedtypegruppe til hovedtype til kartleggingsenhet og har videre mulighet å velge grunntyper innen kartleggingsenheter. Jeg limer nedenfor Hanno sin beskrivelse av prosessen: 
1) Når man kommer på fanen, vises bare hovedtypegruppene.
2) Når man klikker på en hovedtypegruppe, vises dens hovedtyper.
3) Så kan man enten krysse av en hel hovedtype eller klikke for flere underenheter.
4) Gjør man det siste, vises hovedtypens kartleggingsenheter.
5) Så kan man enten krysse av en hel kartleggingsenhet eller klikke for flere underenheter.
6) Gjør man det siste, vises kartleggingsenhetens grunntyper.
7) Så kan man krysse av enkelte grunntyper.

**Comment by EveliinaP** [comment]
[Forslag.for.regional.naturvariasjon.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7486615/Forslag.for.regional.naturvariasjon.pptx)
Oppdatert beskrivelse av beksrivelsesvariabler som skal legges til i tillegg til hovedtyper/kartleggingsenheter/grunntyper

**Comment by EveliinaP** [comment]
[Øvrige_naturtyper.pptx](https://github.com/Artsdatabanken/Fremmedartsbase2023/files/7487162/Ovrige_naturtyper.pptx)

**Comment by EveliinaP** [comment]
@runningbones du hadde vel noe måte for å få ekskludert "sterkt endret natur" fra naturtypelistene?

**Comment by bugdriven** [comment]
Jeg er litt usikker på det med grunntyper under kartleggingsenheter. Det er jo ingen link der, - alle grunntyper ligger under hovedtyper. Jeg skal gjøre et forsøk så får vi se om det blir slik dere tenker.

**Comment by runningbones** [comment]
@runningbones og @olsoybakk jobber med ny versjon av nin-kodebase hvor lkm, grunntyper og kartleggingsenehter kobles (og ikke bare henger å dingler på hovedtypene)

**Comment by runningbones** [comment]
@bugdriven: Kodebasen er nå oppdatert. Ny teknologi, og ny versjon av NiN (v2.3 er ny og default): https://nin-kode-api.artsdatabanken.no/swagger/index.html 

Her finner du nå kobling mellom kartleggingsenheter og grunntyper.

**Comment by EveliinaP** [comment]
Siste punkt om regional variasjon er nå laget som eget issue siden det ble endring i det (bør være lettere å gjennomføre nå)
