### ISSUE TITLE
Naturtyper: overføring av naturtype data til risikovurdering og beregning av tall

### ISSUE THREAD

**Issue by EveliinaP** [Artsdatabanken/Fremmedartsbase2023#77]
Når ekspertene har valgt hvilke naturtyper fremmedeart kan kolonisere og påvirke skal dette data overføres automatisk til risikovurderinger 
- invasjonspotensiale fane: C kriteriet- kolonisert naturtypeareal
- økologisk effekt fane: F kriteriet- effekt på truede/sjelden naturtyper og G-kriteriet: effekter på øvrige naturtyper. 

Slik jeg har forstått skal disse data overføres og beregnes likt som det var gjort i 2018. Vi må huske å ekskludere "sterkt endret natur" fra påvirket natur tall. 
Fyll in detaljer om hvordan dette skal gjøres! Se #11

**Comment by EveliinaP** [comment]
@AneMarlene Jeg lagd denne issue lenge siden. Er dette noe du følger med fortløpende? Er det noe vi skal definere mer eller jeg skal hjelpe med eller skal vi close denne issue?

**Comment by AneMarlene** [comment]
@EveliinaP Ut i fra hva jeg kan se er denne riktig nå, så da lukker jeg.
