### ISSUE TITLE
Artsgruppen "mangler"

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#82]
Her er det noe feil som ikke er rett. Artsgruppen "mangler" inneholder mange arter fra forskjellige artsgrupper:

![image](https://user-images.githubusercontent.com/58254444/131124316-77c5e0d7-b2aa-4de9-b053-4dea8c9d1047.png)

Skal tro hva som har skjedd?

**Comment by AneMarlene** [comment]
@steinho Hvordan går det med denne? "mangler" finnes fortsatt hos meg i test.

**Comment by steinho** [comment]
@AneMarlene du kan sjekke nå som ny database er ute...

**Comment by AneMarlene** [comment]
@steinho Nå er den borte, så da lukker jeg denne :)
