### ISSUE TITLE
layout - detalje-flisespikkeri

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#84]
Kunne vi fått hjørnene på "faneboksen" like firkantet som hjørnene på underfane-boksen? 

![image](https://user-images.githubusercontent.com/58254444/131126335-f470c33c-0ee3-4021-b80c-801e07367abd.png)

....og uten skygge:

![image](https://user-images.githubusercontent.com/58254444/131126556-ac3bf893-a0b1-40e3-8902-92f0de1e026c.png)

**Comment by AneMarlene** [comment]
@svetlnaumova Nå er hjørnene vakre - men fortsatt skygge på høyre side hos meg? 

![image](https://user-images.githubusercontent.com/58254444/131301864-4fc4e78c-4147-46ce-8950-32ee1ce3106c.png)

**Comment by svetlnaumova** [comment]
@AneMarlene tror at den er fikset nå :)
