### ISSUE TITLE
Økologisk effekt - tabeller

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#87]
Et par ønskede endringer på tabeller under økologisk effekt: 

![image](https://user-images.githubusercontent.com/58254444/131352262-2f72b929-ce55-4450-a949-979467f0505c.png)

1. Kolonnen i lilla kan endres til en rullegardinmeny - om eksperten skal velge flere interaksjoner, må hen legge inn arten/naturtypen flere ganger. 
2. Kolonnen i oransje ønsker vi med funksjonalitet som i innsynet på rødlista, altså at alternativer som ikke er avhuket for den gitte arten/naturtypen er skjult (her screenshot fra innsynet).

![image](https://user-images.githubusercontent.com/58254444/131352651-2d95f547-2797-4999-8813-3c51ef325d07.png)

**Comment by svetlnaumova** [comment]
Jeg lukker denne fordi det ser ut som funksjonaliteten er på plass - tror at eneste vi må bli enige om er hva som skal stå ved siden av knappen som åpner menyen med valgmuligheter ("Skriftlig dokumentasjon...", "Ingen valgt" eller noe annet).
