### ISSUE TITLE
Fritekstfelt i basen - jusering

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#89]
En del (eller alle?) fritekstfelt i basen er trukket mer mot venstre enn mot høyre. Vi ønsker at de forstørres mot høyre, slik at avstanden mot den grå kanten blir lik på venstre og høyre side: 

![image](https://user-images.githubusercontent.com/58254444/131469409-18f0fe6b-07c6-4486-ace4-579dc3331219.png)

Om det er mulig :)

**Comment by svetlnaumova** [comment]
Det er mulig at de har blitt litt for store nå - gi gjerne beskjed om jeg burde gjøre dem mindre :)

**Comment by AneMarlene** [comment]
Jeg synes i første omgang det ser greit ut 👍 . La merke til at feltene på horisontskanningen og oppsummeringen ikke endret seg? De må kanskje endres i separate koder?

**Comment by svetlnaumova** [comment]
Skal se på det - mulig det er programmert annerledes.
