### ISSUE TITLE
Bokser for å legge til spredningsveier eller naturtyper

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#91]
På fanene Naturtyper og Spredningsveier, er det "pop-up" bokser hvor informasjon legges til om hver naturtype eller spredningsvei man ønsker å knytte til vurderingene. Disse fungerer foreløpig ikke som tiltenkt (bildeeksempel tatt fra spredningsveier):

![image](https://user-images.githubusercontent.com/58254444/131481901-9738843e-790c-4852-8876-6c168149a555.png)

**Comment by svetlnaumova** [comment]
Jeg lukker denne siden selve pop-up boksene har nå fått den funksjonaliteten de skal ha. Det er fremdeles en del jobb med bl.a. styling og redigering av tabeller, men dette kommer om ikke så lenge.
