### ISSUE TITLE
Kartet i basen - bug

### ISSUE THREAD

**Issue by AneMarlene** [Artsdatabanken/Fremmedartsbase2023#98]
underfanen blir med inn i kartet. Før helga gjaldt dette bare i chrome (det var iallefall ikke slik i Edge på min pc hjemme), men nå ser det slik ut uavhengig av browser - så kanskje var problemet relatert til noe annet... 

![image](https://user-images.githubusercontent.com/58254444/132170077-f79fcc94-cee8-4759-b0eb-71adacebfa84.png)

Assigner du noen andre på IT om dette er noen andres bord, @olsoybakk ? :)

**Comment by olsoybakk** [comment]
Jeg har fiksa det og ser den har kommet tilbake. Ser på dette når jeg er ferdig med å oppdatere noe på NiN i dag.

**Comment by olsoybakk** [comment]
@AneMarlene Jeg har fikset denne feilen (i går)

**Comment by AneMarlene** [comment]
Supert, @olsoybakk :) Jeg lukker denne da.
